### DISCUSSION TITLE
zrepl and ZFS boot environments

### DISCUSSION THREAD

**Discussion by avg-I** [zrepl/zrepl#571] [Q&A]
I have a few questions related to issues that I encountered in my use of zrepl.
It's quite possible that I just didn't figure out how to set up zrepl properly for my use case.  But maybe there is something that can be improved in zrepl as well.

In my setup I have several machines that act as backup clients and a single backup server.  The client machines all use push mode for their backups.
Also, the clients use ZFS boot environments for OS upgrades and major package upgrades.  Backed up datasets include datasets within and outside of a boot environment hierarchy.

Here is a typical client configuration:
```yaml
jobs:
  - name: backup
    type: push
    connect:
      type: tls
      address: trant.home.arpa:7888
      ca: /usr/local/etc/zrepl/ca.crt
      cert: /usr/local/etc/zrepl/xxx.home.arpa.crt
      key: /usr/local/etc/zrepl/xxx.home.arpa.key
      server_cn: "trant.local"
    filesystems: {
      "rpool/ROOT<": true,
      "rpool/usr/home<": true,
      "rpool/var/log": true,
      "rpool/var/mail": true,
      }
    snapshotting:
      type: periodic
      prefix: zrepl-
      interval: 8h
    pruning:
      keep_sender:
        - type: not_replicated
        - type: regex
          negate: true
          regex: "^zrepl-"
        - type: last_n
          count: 12
      keep_receiver:
        - type: grid
          grid: 1x24h(keep=all) | 7x1d | 4x7d | 3x30d
          regex: "^zrepl-"
```

All reported issues / questions are for zrepl 0.4.
