### DISCUSSION TITLE
zrepl pruning and (older) snapshots from other tools

### DISCUSSION THREAD

**Discussion by gdevenyi** [zrepl/zrepl#585] [Q&A] [answered]
I have snapshots from a previous snapshotting tool (zfs-auto-snapshot) that I'd like to participate in the `grid` `keep_sender` and `keep_reciever` strategy, that is, right now I have historical snapshots that I expect zrepl will eventually dispose of as it generates its own under the `grid` method, but retain them until they expire out.

I thought I could do this by simply omitting the `regex:` filter component, but it seems it's required, which I guess I can use `.*` for.

I have no manual snapshots I wish to protect.

So I'm trying to confirm here, if I do something like:
```
    keep_sender:
    - type: not_replicated
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: ".*"
```

Will zrepl treat my preexisting snapshots, named like `@zfs-auto-snap_{frequent,hourly,daily,weekly,monthly}-<datecode>` as valid for participation in the grid retention stategy?
