### DISCUSSION TITLE
The receiver's latest snapshot is not present on sender

### DISCUSSION THREAD

**Discussion by Ramblurr** [zrepl/zrepl#636] [Q&A]
I seem to have gotten myself into a tricky situation.

1. I initially setup a sync job that omitted the `mountpoint=none`, `readonly=true`, and `canmount=off` properties. 
2. I then changed my config so these properties were overriden, but I realized this wasn't applying to already created snapshots (as I was still getting `destination pool/dataset has been modified` errors)
3. So I manually unmounted each replicated dataset on the receiver, and `zfs set` those flags
4. Then I `zfs rollback`ed the latest snapshot on the receiver

However now my zrepl daemon is stuck with PLANNING-ERROR:

```
the receiver's latest snapshot is not present on sender:
  last common: @zrepl_20220910_144458_000

  sender-only:
   .. a large large list of zrepl_ snapshots
```

Is there anyway to recover without deleting all zrepl snapshots on the receiver? I'd rather not transfer all the data again, it took quite a while.

### siteA - source

```yaml
jobs:
- name: siteA_source
  type: source
  serve:
    type: tls
    listen: "10.9.4.10:3478"
    ca: /usr/local/etc/zrepl/siteB.crt
    cert: /usr/local/etc/zrepl/backups.crt
    key:  /usr/local/etc/zrepl/backups.key
    client_cns:
    - siteB
  filesystems: {
    "tank<": true,
    "tank/.system<": false,
    "tank2<": true,
    "tank2/replication<": false,
  }
  snapshotting:
    type: periodic
    interval: 60m
    prefix: zrepl_

```

### site B - pull job

```yaml
jobs:
- name: pull_siteA
  # pull siteB to siteB
  type: pull
  connect:
    type: tls
    address: "ip.siteA.com:3478"
    ca: /usr/local/etc/zrepl/backups.crt
    cert: /usr/local/etc/zrepl/siteB.crt
    key:  /usr/local/etc/zrepl/siteB.key
    server_cn: "backups"
  recv:
    properties:
      override:
        mountpoint: none
        canmount: off
        readonly: on
    placeholder:
      encryption: inherit
  root_fs: "tank/replication/siteA"
  interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 1
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 14x1d
      regex: "^zrepl_.*"
    # keep snapshots not created by zrepl
    - type: regex
      negate: true
      regex: "^zrepl_.*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d | 2x365d
      regex: "^zrepl_.*"
    # keep snapshots not created by zrepl
    - type: regex
      negate: true
      regex: "^zrepl_.*"
  replication:
    concurrency:
      steps: 16
      size_estimates: 16
```

**Comment by problame** [comment]
Sorry for the late reply.

What you need to do to resolve this conflict is to make it so that the latest receiver snapshot exists on the sender.
Then zrepl will resume incremental replication from there.

You can achieve that by carefully comparing the snapshot lists on both sides, then issue the right set of `zfs destroy $snapshot` operations.

Alternatively, you can `zfs rename` the receiving-side dataset to the side. Then, zrepl will do a full replication of the latest snapshot.

**Reply by Ramblurr** [reply]
> You can achieve that by carefully comparing the snapshot lists on both sides, then issue the right set of zfs destroy $snapshot operations.

This might be the technically correct answer, but when there are dozens of filesystems and hundreds of snapshots per filesystem, it is not easy to do this by hand :(

**Comment by Ramblurr** [comment]
@problame This issue still plagues me deeply even years later. Using the `zfs-abstraction release-all` cli feature makes deleting the snapshots easy with a `zfs destroy -r`, however why does this consistently happen to me?

I have a pull job. The puller has:

```yaml
  pruning:
    keep_receiver:
    - grid: 1x24h(keep=all) | 7x1d(keep=1) | 30x1d(keep=1) | 6x30d(keep=1) | 1x365d(keep=1)
      regex: ^zrepl_.*
      type: grid
    - negate: true
      regex: ^zrepl_.*
      type: regex
    keep_sender:
    - type: not_replicated
    - count: 7
      type: last_n
    - grid: 1x24h(keep=all) | 7x1d(keep=1) | 30x1d(keep=1) | 6x30d(keep=1) | 1x365d(keep=1)
      regex: ^zrepl_.*
      type: grid
    - negate: true
      regex: ^zrepl_.*
      type: regex
```

The source has a snapshotting setting of:

```yaml
  snapshotting:
    interval: 6h
    prefix: zrepl_
    type: periodic
```

The source occasionally goes offline for extended periods, so snapshot windows can be missed. I am constantly running in to this error making zrepl basically worthless. 

I assume this is some sort of configuration issue aka a skill issue on my part. Do you have the cycles to explain it to me?

```
...
rpool/encrypted/safe/vms                     PLANNING-ERROR (step 0/0, 0 B/0 B) the receiver's latest snapshot is not present on sender:
last common: @zrepl_20250604_131338_000
sender-only:              
@zrepl_20250604_191338_000
@zrepl_20250605_011338_000
@zrepl_20250605_071338_000
@zrepl_20250605_131338_000
@zrepl_20250605_191338_000
@zrepl_20250606_011338_000
@zrepl_20250606_071338_000
@zrepl_20250606_131338_000
@zrepl_20250606_191338_000
@zrepl_20250607_011338_000
@zrepl_20250607_071338_000
@zrepl_20250607_131338_000
@zrepl_20250607_191338_000
@zrepl_20250608_011338_000
@zrepl_20250608_071338_000
@zrepl_20250608_131338_000
@zrepl_20250608_191338_000
@zrepl_20250609_011338_000
@zrepl_20250609_071338_000
@zrepl_20250609_131338_000
@zrepl_20250609_191338_000
@zrepl_20250610_011338_000
@zrepl_20250610_071338_000
@zrepl_20250610_131338_000
@zrepl_20250610_191338_000
@zrepl_20250611_011338_000
@zrepl_20250611_071338_000
@zrepl_20250611_131338_000
@zrepl_20250611_191338_000
@zrepl_20250612_011338_000
@zrepl_20250612_071338_000
@zrepl_20250612_131338_000
@zrepl_20250612_191338_000
@zrepl_20250613_011338_000
@zrepl_20250613_071338_000
@zrepl_20250613_131338_000
@zrepl_20250613_191338_000
@zrepl_20250614_011338_000
@zrepl_20250614_071338_000
@zrepl_20250614_131338_000
@zrepl_20250614_191338_000
@zrepl_20250615_011338_000
@zrepl_20250615_071338_000
@zrepl_20250615_131338_000
@zrepl_20250615_191338_000
@zrepl_20250616_011338_000
@zrepl_20250616_071338_000
@zrepl_20250616_131338_000
@zrepl_20250616_191338_000
@zrepl_20250617_011338_000
@zrepl_20250617_071338_000
@zrepl_20250617_131338_000
@zrepl_20250617_191338_000
@zrepl_20250618_011338_000
@zrepl_20250618_071338_000
@zrepl_20250618_131338_000
@zrepl_20250618_191338_000
@zrepl_20250619_011338_000
@zrepl_20250619_071338_000
@zrepl_20250619_131338_000
@zrepl_20250619_191338_000
@zrepl_20250620_011338_000
@zrepl_20250620_071338_000
@zrepl_20250620_131338_000
@zrepl_20250620_200527_000
@zrepl_20250623_054323_000
@zrepl_20250623_114323_000
@zrepl_20250623_174323_000
@zrepl_20250623_234323_000
@zrepl_20250624_054323_000
@zrepl_20250624_172918_000

receiver-only:
@zrepl_20250605_131351_000
@zrepl_20250606_191349_000
@zrepl_20250608_011355_000
@zrepl_20250609_071338_000
@zrepl_20250612_011338_000
@zrepl_20250613_011353_000
@zrepl_20250615_071349_000
@zrepl_20250616_071357_000
@zrepl_20250618_131347_000
@zrepl_20250620_011349_000
@zrepl_20250621_071356_000
@zrepl_20250622_131352_000
@zrepl_20250623_131350_000
@zrepl_20250623_191351_000
@zrepl_20250624_011357_000
@zrepl_20250624_071348_000
@zrepl_20250624_131342_000
```
```
