### DISCUSSION TITLE
Need a hand getting started

### DISCUSSION THREAD

**Discussion by ovizii** [zrepl/zrepl#710] [Q&A]
I failed right from the start. I thought I'd start with a "snap" type job to get a feel for zrepl and to have local snapshtos available. 

I edited  /etc/zrepl/zrepl.yml on a Debian Bulls Eye and here is my config after reading many, many help pages from here: https://zrepl.github.io/configuration/jobs.html#job-type-snap-snapshot-prune-only 

```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: frequent
  type: snap
  filesystems: {
     "sixer/Documents": true,
     "sixer/Pictures": true
  }
  snapshotting:
    type: manual
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: last_n
        count: 600
```

Unfortunately zrepl is unhappy with something.

```
zrepl signal wakeup frequent
could not parse config: yaml: unmarshal errors:
  line 16: field prefix not found in type config.SnapshottingManual
  line 17: field interval not found in type config.SnapshottingManual
  line 18: field timestamp_format not found in type config.SnapshottingManual
  line 7: field snapshotting is required but has zero value
  line 0: field jobs is required but has zero value
```

Does anyone have any idea what I am doing wrong? Those fields it is complaining about are present in my config.

**Comment by ovizii** [comment]
oh, I noticed I should remove: "interval: 15m" since that is a leftover from when I tried a "periodic" type job.

**Comment by kpfleming** [comment]
The error message isn't telling you what it appears to be telling you... the wording could probably be improved.

In each place where you see "not found in type" replace that with "not allowed in type". As an example, when you specify `type: manual` in the `snapshotting` section, you cannot specify `prefix` because zrepl won't be making the snapshots (something outside zrepl will, which is what `manual` is used for).

**Reply by ovizii** [reply]
> In each place where you see "not found in type" replace that with "not allowed in type". As an example, when you specify `type: manual` in the `snapshotting` section, you cannot specify `prefix` because zrepl won't be making the snapshots (something outside zrepl will, which is what `manual` is used for).

Thanks, that helped a lot "not allowed in type" is way clearer now :-) 

After reading https://zrepl.github.io/configuration/snapshotting.html#job-snapshotting-spec seeing:

> ...Or, if you want to decouple snapshot management from replication using a zrepl snap job....

I seem to have misunderstood that part, but it is clear now. Will repost here with my end result for others to find.

**Comment by ovizii** [comment]
Hm, I might need another pointer. I am currently only looking for a proper management of local snapshots so no replication yet. 

I read in the manual that it is recommended to create snapshots within the same filesystem declaration (can't find the link atm) but now I am wondering if or how I can have different pruning rules for different datasets. 

Lets take this config as a sample for now:

```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: frequent
  type: snap
  filesystems: {
     "sixer/Documents": true,
     "sixer/Pictures": true
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: last_n
        count: 600
```

Let's say I'd like to have different pruning rules for Documents than for Pictures. Any hints where to start looking or how to achieve this? It looks like the "regex" solution only differentiates by the snapshot name and not by the source. So should I create different jobs then?

**Reply by kpfleming** [reply]
Yep.

**Comment by ovizii** [comment]
One last question hopefully:

works:
```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: Documents
  type: snap
  filesystems: {
     "sixer/Documents": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: last_n
        count: 600
```

This one though:
```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: Documents
  type: snap
  filesystems: {
     "sixer/Documents": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: grid
        grid: 1x1h(keep=4) | 24x1h(keep=1) | 7x1d(keep=1) | 4x1w(keep=1) | 12x4w(keep=1) | 1x53w(keep=1)
```

Gives this error:

```
zrepl configcheck
could not parse config: yaml: unmarshal errors:
  line 21: field regex is required but not given
  line 18: field keep is required but has zero value
  line 7: field pruning is required but has zero value
  line 0: field jobs is required but has zero value
```

The only difference is I replaced 
```
    keep:
      - type: last_n
```
with 
```
      -     keep:
      - type: grid
```
I thought the docs specifically mentioned this type of job:
![image](https://github.com/zrepl/zrepl/assets/837902/77877f71-c369-4934-8bd1-af7761605147)


Also, apparently there is s,m,h,d,w - no months or years available for pruning?
