### DISCUSSION TITLE
How to setup snapshots and pruning with zrepl without any replication (yet)

### DISCUSSION THREAD

**Discussion by ovizii** [zrepl/zrepl#711] [Q&A] [answered]
This is my first simple try which keeps 600 latest snapshots, so I don't lose any old ones while testing. It works.

```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: Documents
  type: snap
  filesystems: {
     "sixer/Documents": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: last_n
        count: 600
```

Next I would like to add a better pruning strategy so I tried replacing 
```
  pruning:
    keep:
      - type: last_n
        count: 600
```
with 
```
  pruning:
    keep:
      - type: grid
        grid: 1x1h(keep=4) | 24x1h(keep=1) | 7x1d(keep=1) | 4x1w(keep=1) | 12x4w(keep=1) | 10x53w(keep=1)
```
Unfortunately a `zrepl configcheck` gives this error:
```
could not parse config: yaml: unmarshal errors:
  line 21: field regex is required but not given
  line 18: field keep is required but has zero value
  line 7: field pruning is required but has zero value
  line 0: field jobs is required but has zero value
```

So I am wondering what I am doing wrong here. I need some pointers please.

I thought the docs specifically mentioned this type of job:
![image](https://github.com/zrepl/zrepl/assets/837902/614a6ebb-d1c6-404f-9cbe-94179b888503)

Btw. I am not treating this as a backup, I just really don't want to lose any old snapshots until I arrive at the replication step hence the `4x1w(keep=1) | 12x4w(keep=1) | 10x53w(keep=1)` part

**Comment by kpfleming** [comment]
The error message is telling you what is wrong. The `grid` policy of `keep` requires a `regex` and you haven't supplied it. That makes the `keep` section invalid, so all of the sections above it become invalid as well.

Please take some time to review the [documentation](https://zrepl.github.io/configuration/prune.html#policy-grid) thoroughly, as it shows you how the sections should be structured.

**Reply by ovizii** [reply, marked as answer]
Thanks for pointing out my mistake. I did not read the documentation as "requiring a regex rule" - I mistakenly read it as an option. 

So after adding a regex, here is what happens:

```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: Documents
  type: snap
  filesystems: {
     "sixer/Documents": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: regex
        regex: "^zrepl_.*"
      - type: grid
        grid: 1x1h(keep=4) | 24x1h(keep=1) | 7x1d(keep=1) | 4x1w(keep=1) | 12x4w(keep=1) | 1x53w(keep=1)
```
zrepl configcheck

```
could not parse config: yaml: unmarshal errors:
  line 21: field regex is required but not given
  line 0: field jobs is required but has zero value
```
I think I have found the problem. This example here:  https://zrepl.github.io/configuration/prune.html
```
    pruning:
      keep_sender:
        # make sure manually created snapshots by the administrator are kept
        - type: regex
          regex: "^manual_.*"
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_.*" 
```

**shows 2 types of pruning: regex and grid and grid itself also seems to need a regex. I couldn't tell from the error message that "type: grid" needs the regex option. It looked like the pruning job needed a type: regex**

So I seem to have fixed my issue with this config:

```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: Documents
  type: snap
  filesystems: {
     "sixer/Documents": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
    timestamp_format: human
  pruning:
    keep:
      - type: grid
        grid: 1x1h(keep=4) | 24x1h(keep=1) | 7x1d(keep=1) | 4x1w(keep=1) | 12x4w(keep=1) | 1x53w(keep=1)
        regex: "^zrepl_.*"
      - type: regex
        negate: true
        regex: "^zrepl_.*"
```
