### DISCUSSION TITLE
zrepl 0.6.1 - Pre_snapshot/post_snapshot hooks not running as expected

### DISCUSSION THREAD

**Discussion by rkelleyrtp** [zrepl/zrepl#746] [Q&A]
Greetings all,

I am running zrepl 0.6.1 on Debian 12 and am having problems getting the pre and post snapshot hooks working.  For context, I have a simple setup - 2x ZFS servers using a push configuration with the following configs:

#### Sender config file:
```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: zrepl-01__data-01
  type: push
  connect:
    type: tcp
    address: "192.168.100.102:8888"
  filesystems: { "mypool/data-01<": true, }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 1m
    hooks:
    - type: command
      path: /etc/zrepl/hooks/my_hook.sh
      timeout: 30s
      err_is_fatal: false
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 3
    keep_receiver:
    - type: last_n
      count: 3
```

#### Receiver config file:
```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: zrepl-02 backup dataset
  type: sink
  serve:
    type: tcp
    listen: ":8888"
    clients: {
       "192.168.101.101" : "zrepl-01"
    }
  recv:
    properties:
      override:
        readonly: on
        canmount: on
        snapdir: visible
      inherit:
        - encryption
  root_fs: "mypool"
```

### The issue
Running the script manually works as expected, however, it does not work with zrepl.  That said, **if the script is missing or has a syntax error, zrepl will report an error**.  Thus, successful runs of the script don't appear to work.  The `/etc/zrepl/hooks/my_hook.sh` script simply outputs the shell environment to a test file.  Like this:
```
#!/usr/bin/bash
set -e
printenv > /tmp/1
```

Any hints/clues?
