### DISCUSSION TITLE
ERROR: replication cursor bookmark does not exist (one successful replication is required before pruning work)

### DISCUSSION THREAD

**Discussion by ChristophSchmidpeter** [zrepl/zrepl#804] [Q&A] [answered]
I want to backup all files on source pool `ZfsRoot` to USB connected destination `ZfsBackup1/Backup` .  I want to simply have it copy all my snapshots from source to destination. If filesystems do not exist in destination it should of course create them.
This is my YAML
```
jobs:
  - name: backup_job
    type: push
    connect:
      type: local
      listener_name: backuppool_sink
      client_identity: vbm
    snapshotting:
      type: manual  # disable periodic snapshots
    pruning:
      keep_sender:
        - type: regex
          regex: ".*"  # keep all existing snapshots on the sender side
      keep_receiver:
        - type: regex
          regex: ".*"  # keep all existing snapshots on the receiver side
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    filesystems:
      "ZfsRoot<": true
    conflict_resolution:
      initial_replication: all
    send:
      encrypted: true

  - name: backuppool_sink
    type: sink
    root_fs: "ZfsBackup1/Backup"
    serve:
      type: local
      listener_name: backuppool_sink
```
For each subfilesystem I have snapshots:
`$sudo zfs snap -r ZfsRoot@MySnapshot1`

I restart the service:
`$sudo systemctl restart zrepl.service`
And trigger the backup:
`$sudo zrepl signal wakeup backup_job`
Then I look into zrepl status:
`$sudo zrepl status`

And for each filesystem under `ZfsRoot` it says:
`ERROR: replication cursor bookmark does not exist (one successful replication is required before pruning work`

```
FILTER                                                                                                                                
┌────────────────────┐╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
│jobs                │║Job: backup_job                                                                                               ║
│├──backup_job       │║Type: push                                                                                                   ▒║
│└──backuppool_sink  │║                                                                                                             ▒║
│                    │║Replication:                                                                                                 ▒║
│                    │║   Attempt #1                                                                                                ▒║
│                    │║   Status: planning-error                                                                                    ▒║
│                    │║   Last Run: 2024-07-21 13:19:16 +0200 CEST (lasted 0s)                                                      ▒║
│                    │║   Problem: rpc error: code = Unknown desc = root_fs does not exist                                          ▒║
│                    │║                                                                                                             ▒║
│                    │║Pruning Sender:                                                                                              ▒║
│                    │║   Status: ExecErr                                                                                           ▒║
│                    │║   ZfsRoot                                           ERROR: replication cursor bookmark does not exist (one s▒║
│                    │║                                                                                                             ▒║
│                    │║   ZfsRoot/home                                      ERROR: replication cursor bookmark does not exist (one s▒║
│                    │║                                                                                                             ▒║
│                    │║   ZfsRoot/home/Darling                              ERROR: replication cursor bookmark does not exist (one s▒║
│                    │║                                                                                                             ▒║
│                    │║   ZfsRoot/home/Key                                  ERROR: replication cursor bookmark does not exist (one s▒║
│                    │║                                                                                                             ▒║
│                    │║   ZfsRoot/home_230401BeforeMergeMediaIntoHome       ERROR: replication cursor bookmark does not exist (one s▒║
│                    │║                                                                                                             ▒║
│                    │║   ZfsRoot/home_240210SafetySnap                     ER


```
I don't know what that means. Why would I need a bookmark? I have already made snapshots. All I want it to do is create a backup.

How can I fix this issue?
