### DISCUSSION TITLE
How to keep "Sunday" snapshots using Grid policy

### DISCUSSION THREAD

**Discussion by rkelley-psna** [zrepl/zrepl#807] [General]
Greetings all,

I am reviewing the grid policy documentation and don't see the option to keep a specific day's snapshot.  My requirement is to snapshot each day at 6am, keep 14 days of snapshots, and keep 24 weeks of Sunday snapshots.  So far, I have been working with this:

```
  snapshotting:
    type: cron
    prefix: zrepl_
    cron: "0 6 * * *"
  pruning:
     grid: 14x1d | 24x1w
     regex: '^zrepl_'
```

But, this config does not let me dictate which weekly day to keep.  Maybe I missed it in the docs.

Any pointers?
