### DISCUSSION TITLE
1-to-many Fanout - Replication doesn't trigger on snapshot

### DISCUSSION THREAD

**Discussion by GauntletWizard** [zrepl/zrepl#823] [Q&A]
I followed the [instructions in the docs](https://zrepl.github.io/configuration/overview.html#two-or-more-machines) for setting up one-to-many replication of my desktop machine. The snapshots are working correctly, and I have no problems sending, but it doesn't trigger automatically - A manual signal for the job to "Wakeup" causes replication to happen, but it doesn't happen on each snapshot.

Is there a way to set a schedule or to configure the snapshotting job to wake the push replication jobs?

```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn
  monitoring:
    - type: prometheus
      listen: ':9811'

jobs:
  # This is fairly exact from https://zrepl.github.io/quickstart/continuous_server_backup.html#configure-server-prod
  - name: toph
    type: push
    filesystems:
      "toph/home<": true
    send:
      encrypted: false
    connect:
      type: tls
      address: "tylee:8826"
      ca: /etc/zrepl/ca.crt
      cert: /etc/zrepl/zrepl.crt
      key:  /etc/zrepl/zrepl-key.pem
      server_cn: "tylee"

    # The actual config is below at rootsnaps
    snapshotting:
      type: manual
    pruning:
      keep_sender:
        - type: not_replicated
        - type: regex
          regex: ".*"
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
        regex: "^zrepl_"

  - name: chartulary
    type: push
    filesystems:
      "toph/home<": true
    send:
      # I don't trust chartulary far - It's not in my physical control. Therefore, it gets encrypted sends.
      encrypted: true
    connect:
      type: tls
      address: "chartulary:8826"
      ca: /etc/zrepl/ca.crt
      cert: /etc/zrepl/zrepl.crt
      key:  /etc/zrepl/zrepl-key.pem
      server_cn: "zrepl"

    # The actual config is below at rootsnaps
    snapshotting:
      type: manual
    pruning:
      keep_sender:
        - type: not_replicated
        - type: regex
          regex: ".*"

      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
        regex: "^zrepl_"

  - name: rootsnaps
    type: snap
    filesystems:
      "toph<": true
      "toph/steamlibrary<": false
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 5m
    pruning:
      keep:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 15x1d | 3x30d
        regex: "^zrepl_"

```

**Comment by GauntletWizard** [comment]
I found my answer in #672, and understand now how the multi-fanout is supposed to work. However, it seems unintuitive to have a hook call an external wrapper to signal the push jobs. Would there be interest in adding a "signal" hook type that internally signals the other job?

**Reply by dsh2dsh** [reply]
> it seems unintuitive to have a hook call an external wrapper to signal the push jobs.

JFYI this feature already implemented in my fork https://github.com/dsh2dsh/zrepl
Feel free to use it:

Replication jobs (without periodic snapshotting) can be configured for periodic run. See https://github.com/zrepl/zrepl/pull/758. Configuration example:

```yaml
- name: "zroot-to-server"
  type: "push"
  interval: "1h"
  snapshotting:
    type: "manual"
```

Both pull and push job types support configuration of periodic run using cron specification. For instance:

```yaml
- name: "zroot-to-server"
  type: "push"
  cron: "25 15-22 * * *"
  snapshotting:
    type: "manual"
```
