### DISCUSSION TITLE
Zrepl snapshots count.

### DISCUSSION THREAD

**Discussion by varun-munjal** [zrepl/zrepl#835] [Q&A]
Hello!

We've tried few combinations of grid in pruning in zrepl but unable to setup the manual custom snapshots count of lets say hourly x number and daily snapshots count of y number. Can anyone assist with this please? TIA!

Below config we tried for keeping 90 hourly snapshots but its not keeping the mentioned count:

```yaml
  - name: snapjob_test_hourly
    type: snap
    filesystems: {"testhost/test1": true, }
    snapshotting:
      type: periodic
      interval: 60m
      prefix: test1snap_
      hooks:
        - type: command
          path: /usr/local/scripts/snapshot_rename_rajesh_testing.sh
          filesystems: {"testhost/test1": true, }
          timeout: 30s
          err_is_fatal: false
    pruning:
      keep:
        - type: grid
          grid:  24x1h(keep=90)
          regex: ^snapshot.hourly*
        - type: regex
          negate: true
          regex: ^snapshot.hourly*
```

and below for 90 days nightly/daily snapshots:

```yaml
 - name: snapjob_test_nightly
    type: snap
    filesystems: {"testhost/test1": true, }
    snapshotting:
      type: periodic
      interval: 24h
      prefix: test1snapnightly_
      hooks:
        - type: command
          path: /usr/local/scripts/snapshot_rename_rajesh_testing.sh
          filesystems: {"testhost/test1": true, }                                                  
          timeout: 30s
          err_is_fatal: false
    pruning:
      keep:
        - type: grid
          grid:  90x1d
          regex: ^snapshot.nightly*
        - type: regex
          negate: true
          regex: ^snapshot.nightly*
```

Thanks.
