### DISCUSSION TITLE
Need help with Fan-in replication using TLS

### DISCUSSION THREAD

**Discussion by rkelleyrtp** [zrepl/zrepl#836] [Q&A] [answered]
Greetings all,

I need some assistance configuring Fan-in replication using TLS. I have followed the [official zrepl documentation](https://zrepl.github.io/configuration/transports.html#id6), but I'm still a little confused.  I have three local servers (backup-server-1, backup-server-2, and backup-server-3) that need to push their backups to a remote zrepl server (offsite-backup-server) via TLS.  

I followed the instructions in the "[Certificate Authority using EasyRSA](https://zrepl.github.io/configuration/transports.html#id6)" section and have generated the "key" and "crt" files for all 4 servers - in addition to a "ca.key" file.  The problem is, I don't know how to configure the TLS section on the sink side for all three remote servers.  

**This is the directory structure after generating the keys via 'easyrsa':**
```
root@offsite-backup-server:~/easy-rsa/easyrsa3/pki# ls -la private/
total 32
drwx------ 2 root root 4096 Aug  9 13:07 .
drwx------ 8 root root 4096 Aug  9 13:07 ..
-rw------- 1 root root 1704 Aug  9 13:03 backup-server-1.key
-rw------- 1 root root 1704 Aug  9 13:03 backup-server-2.key
-rw------- 1 root root 1704 Aug  9 13:03 backup-server-3.key
-rw------- 1 root root 1704 Aug  9 13:02 ca.key
-rw------- 1 root root 1708 Aug  9 13:07 offsite-backup-server.key

root@offsite-backup-server:~/easy-rsa/easyrsa3/pki# ls -la issued/
total 48
drwx------ 2 root root 4096 Aug  9 13:07 .
drwx------ 8 root root 4096 Aug  9 13:07 ..
-rw------- 1 root root 4638 Aug  9 13:03 backup-server-1.crt
-rw------- 1 root root 4635 Aug  9 13:03 backup-server-2.crt
-rw------- 1 root root 4638 Aug  9 13:03 backup-server-3.crt
-rw------- 1 root root 4652 Aug  9 13:07 offsite-backup-server.crt
```

Per the [TLS Transport documentation](https://zrepl.github.io/configuration/transports.html#tls-transport), the offsite-backup-server should have something like this:
```
jobs:
  - type: sink
    root_fs: "backup-data"
    serve:
      type: tls
      listen: ":8888"
      ca:   /etc/zrepl/ca.crt
      cert: /etc/zrepl/prod.fullchain    <-- WHAT/WHERE IS THIS FILE?
      key:  /etc/zrepl/prod.key          <-- WHAT/WHERE IS THIS FILE?
      client_cns:
        - "backup-server-1"
        - "backup-server-2"
        - "backup-server-3"
	...
	...
	...
```

...and the backup-server-1 config should look like this:
```
jobs:
- type: pull
  connect:
    type: tls
    address: "remote-offsite-server:8888"
    ca:   /etc/zrepl/ca.crt
    cert: /etc/zrepl/backupserver.fullchain     <-- WHAT/WHERE IS THIS FILE?
    key:  /etc/zrepl/backupserver.key           <-- WHAT/WHERE IS THIS FILE?
    server_cn: "remote-offsite-server"
```

For the backup-server-1 side, I suspect the "cert" file should be `/etc/zrepl/offsite-backup-server.crt` and the `key` file should be `/etc/zrepl/offsite-backup-server.key`.

But, **how do I create the "fullchain" and "prod.key" files for the sink server that includes all the crt and key files for remote clients**?  It seems this part was left out of the guide.
