### DISCUSSION TITLE
zrepl 0.6.1 reporting "callback channel is full" -- annoying warning or something serious?

### DISCUSSION THREAD

**Discussion by gdevenyi** [zrepl/zrepl#844] [Q&A]
My syslog regularly reports this message from zrepl

```
Oct 28 02:43:50 cicss05 zrepl[2757610]: [cicss05_to_cicss06][snapshot][/gth$ouJw$oNrA$oNrA./YcN]: callback channel is full, discarding snapshot update event
```

I'm running a pretty standard "snapshot and push replicate" job
```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: cicss05_to_cicss06
  type: push
  replication:
    concurrency:
      steps: 4
      size_estimates: 8
  connect:
    type: tls
    address: "cicss06:8888"
    ca: /etc/zrepl/cicss06.crt
    cert: /etc/zrepl/cicss05.crt
    key:  /etc/zrepl/cicss05.key
    server_cn: "cicss06"
  filesystems: {
    "<": true,
    "data": false,
    "data/scratch2": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: ".*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 30x1d | 3x30d
      regex: ".*"
```

Is this something to be concerned with?
