### ISSUE TITLE
pruner: filesystems with no correspondence on sink should not be pruned

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#126]
Hi,

in my tests, I have now run into a strange problem where zrepl first complained this:

```
2019-03-02T11:39:54+01:00 [ERRO][backup_system][pruning]: cannot get replication cursor prune_side="receiver" fs="zfsintern/Users" err="endpoint does not allow access to filesystem zfsintern/Users" invocation="1"
2019-03-02T11:39:54+01:00 [ERRO][backup_system][pruning]: entering error state after error invocation="1" prune_side="receiver" err="endpoint does not allow access to filesystem zfsintern/Users" state="ErrPerm"
```

this was the config at the time:

```
jobs:
  - type: sink
    name: "local_sink"
    root_fs: "zfssnaps/encRoot"
    serve:
      type: local
      listener_name: localsink

  - type: push
    name: "backup_system"
    connect:
      type: local
      listener_name: localsink
      client_identity: SergeantPepperSenior
    filesystems: {
      "zfsintern/Users/justin/Cloudy<": true,
      "zweischock/temp<": true
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix: zrepl_
    pruning:
      keep_sender:
      - type: last_n
        count: 10
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h(keep=1) | 35x1d(keep=1) | 6x30d(keep=1) | 24x30d(keep=1) | 6x90d(keep=1)
        regex: "zrepl_.*"

```

and this is the output of zfs list

```
zfssnaps                                                                             1,03T   476G  2,55M  none
zfssnaps/encRoot                                                                     41,7G   476G   152K  none
zfssnaps/encRoot/SergeantPepperSenior                                                41,7G   476G   152K  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern                                      36,8G   476G   152K  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users                                4,10G   476G   184K  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin                         4,10G   476G   184K  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin/Cloudy                  4,10G   476G   101M  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin/Cloudy/dataset1  1,06G   476G  1,03G  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin/Cloudy/dataset2      1,43G   476G  1,43G  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin/Cloudy/dataset3          1014M   476G   897M  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin/Cloudy/dataset4              247M   476G   247M  none
zfssnaps/encRoot/SergeantPepperSenior/zfsintern/Users/justin/Cloudy/dataset5
```

zrepl is run with `sudo`, so there shouldn't be any access problems on a local job

I now *removed* all references to zfsintern from the config but it somehow still wants to access it? Where does zrepl keep state? This is the new config but the error is still the same?

```
jobs:
  - type: sink
    name: "local_sink"
    root_fs: "zfssnaps/encRoot"
    serve:
      type: local
      listener_name: localsink

  - type: push
    name: "backup_system"
    connect:
      type: local
      listener_name: localsink
      client_identity: SergeantPepperSenior
    filesystems: {
      "zweischock/temp": true
    }
    snapshotting:
      type: periodic
      interval: 1m
      prefix: zrepl_
    pruning:
      keep_sender:
      - type: last_n
        count: 10
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h(keep=1) | 35x1d(keep=1) | 6x30d(keep=1) | 24x30d(keep=1) | 6x90d(keep=1)
        regex: "zrepl_.*"

```

where does it **now**, without any mention of zfsintern/Users get the idea that it should try to access that? I can access the filesystems myself - this is rather weird
