### ISSUE TITLE
Receive side pruning appears to mismatch jobs

### ISSUE THREAD

**Issue by raybeck95** [zrepl/zrepl#135]
I am using FreeBSD 12 with zrepl 0.1.0rc3.  I have a config file with 3 jobs.  The first job is called "nextcloud" and backs up a dataset called "nextcloud".  The third job is called "documents" and backs up a number of things including a dataset called "development".  The receive side pruner fails because it appears to get these mixed up.  I am using ssh+stdinserver transport, with a Ubuntu machine on the other side, same zrepl 0.1.0rc3.

`Mar 12 07:06:23 fileserver zrepl[38476]: 2019-03-12T07:06:23-04:00 [ERRO][nextcloud][pruning]: cannot get replication cursor fs="zfspool/development" invocation="1" err="endpoint does not allow access to filesystem zfspool/development" prune_side="receiver"`

```Job: documents                                                                                                                                                                                
    Type: push                                                                                                                                                                                
    Replication:                                                                                                                                                                              
        Status: Completed                                                                                                                                                                     
        Progress: [===========================>] 0 B / 0 B @ 0 B/s                                                                                                     
          zfspool/development Completed (step 0/0, 0 B/0 B)                                                                                                                                   
          zfspool/shareddocs  Completed (step 0/0, 0 B/0 B)                                                                                                                                   
    Pruning Sender:                                                                                                                                                                           
        Status: Done                                                                                                                                                                          
        Progress: [>] 0/0 snapshots                                                                                                                                                           
        zfspool/development Completed  (destroy 0 of 44 snapshots)                                                                                                                            
        zfspool/shareddocs  Completed  (destroy 0 of 149 snapshots)                                                                                                                           
    Pruning Receiver:                                                                                                                                                                         
        Status: ErrPerm                                                                                                                                                                       
        Error: endpoint does not allow access to filesystem zfspool/nextcloud                                                                                                                 
                                                                                                            
Job: nextcloud                                                                                                                                                                                
    Type: push                                                                                                                                                                                
    Replication:                                                                                                                                                                              
        Status: Completed                                                                                                                                                                     
        Progress: [============================>] 624 B / 624 B @ 0 B/s                                                                                                 
          zfspool/nextcloud Completed (step 1/1, 624 B/624 B)                                                                                                                                 
    Pruning Sender:                                                                                                                                                                           
        Status: Done                                                                                                                                                                          
        Progress: [>] 0/0 snapshots                                                                                                                                                           
        zfspool/nextcloud Completed  (destroy 0 of 4 snapshots)                                                                                                                               
    Pruning Receiver:                                                                                                                                                                         
        Status: ErrPerm                                                                                                                                                                       
        Error: endpoint does not allow access to filesystem zfspool/development```

**Comment by problame** [comment]
Could you post the zrepl.yml for both the sending and receiving side?
Note that the line prefix contains the job name, not the dataset name: `[LOG_LEVEL][JOB_NAME][SUBSYSTEM]`. In zrepl 0.0.*, the line prefix would also contain the dataset name. This will be gone in 0.1.

**Comment by jbliesener** [comment]
Could that be another instance of the filesystem moving/renaming/zrepl:placeholder problem mentioned in #126 ?

**Comment by raybeck95** [comment]
```
global:
  logging:
    - type: "stdout"
      level:  "error"
      format: "human"
    - type: "syslog"
      level:  "debug"
      format: "logfmt"

jobs:
 - type: push
   name: "nextcloud"
   connect:
      type: ssh+stdinserver
      host: backup
      user: root
      port: 22
      rpc:
         timeout: 60s
      identity_file: /root/.ssh/backup.pem
   filesystems: {
      "zfspool/nextcloud": true
   }
   snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 4h
   pruning:
      keep_sender:
       - type: not_replicated
       - type: grid
         grid: 1x1d(keep=all) | 7x1d | 4x7d | 999999x180d
         regex: "^zrepl_.*"
      keep_receiver:
       - type: grid
         grid: 1x1d(keep=all) | 7x1d | 4x7d | 999999x180d
         regex: "^zrepl_.*"

 - type: push
   name: "machines"
   connect:
      type: ssh+stdinserver
      host: backup
      user: root
      port: 22
      identity_file: /root/.ssh/backup.pem
      rpc:
         timeout: 60s
   filesystems: {
      "zfspool/proxmox": true,
      "zfspool/oldmachines": true,
      "zfspool/vms": true
   }
   snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 24h
   pruning:
      keep_sender:
       - type: not_replicated
       - type: grid
         grid: 5x1d | 3x30d | 999999x360d
         regex: "^zrepl_.*"
      keep_receiver:
       - type: grid
         grid: 5x1d | 3x30d | 999999x360d
         regex: "^zrepl_.*"

 - type: push
   name: "documents"
   connect:
      type: ssh+stdinserver
      host: backup
      user: root
      port: 22
      identity_file: /root/.ssh/backup.pem
      rpc:
         timeout: 60s
   filesystems: {
      "zfspool/development": true,
      "zfspool/shareddocs": true
   }
   snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 1h
   pruning:
      keep_sender:
       - type: not_replicated
       - type: regex
         regex: "^auto-.*"
       - type: grid
         grid: 1x8h(keep=all) | 30x1d | 999999x7d
         regex: "^zrepl_.*"
      keep_receiver:
       - type: regex
         regex: "^auto-*"
       - type: grid
         grid: 1x8h(keep=all) | 30x1d | 999999x7d
         regex: "^zrepl_.*"
```

**Comment by raybeck95** [comment]
```
jobs:
 - type: sink
   name: sinkjob
   root_fs: zfsbackup
   serve:
      type: stdinserver
      client_identities:
       - "fileserver"
```
