### ISSUE TITLE
zrepl status: the progress bar never finish but the job is complete

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#165]
* Another detail in the replication job, the progress bar never finish but the job is completed:

```
Job: zfsnode                                                                                                                                                                                                                                   
    Type: push                                                                                                                                                                                                                                  
    Replication:                                                                                                                                                                                                                                
        Status: Completed                                                                                                                                                                                                                       
        Progress: [=================================================>-] 59.6 GiB / 60.4 GiB @ 0 B/s                                                                                                                                             
          APool/px Completed (step 1/1, 29.7 GiB/30.1 GiB)                                                                                                                                                                               
          BPool/px Completed (step 1/1, 30.0 GiB/30.3 GiB)  
```

-- originally reported as part of https://github.com/zrepl/zrepl/issues/162#issue-425513076

**Comment by problame** [comment]
This situation is the result of under-estimation by `zfs send -n`, which can happen. So, `Status: Completed` should just force progress to 100% iff no errors occured during replication.

**Comment by lapo-luchini** [comment]
Me, on the other hand, seem to always have the opposite effect?
When job is ended my progress is always more than expected.

```
Job: backup
    Type: push
    Replication:
        Attempt #1
        Status: done
        Progress: [==================================================>] 526.3 MiB / 487.6 MiB @ 0 B/
```
