### ISSUE TITLE
goroutine leak if receive-side pool is not imported

### ISSUE THREAD

**Issue by JMoVS** [zrepl/zrepl#174]
Hi,
my zrepl uses incredible amounts of memory over time:

<img width="1128" alt="Bildschirmfoto 2019-04-27 um 13 38 08" src="https://user-images.githubusercontent.com/7354506/56849200-e0d56800-68f1-11e9-9a66-6c21ea09d54c.png">

And after a restart it's back to 3MB...

**Comment by problame** [comment]
next time, please don't restart it:

```
zrepl pprof on 127.0.0.1:12345
go tool pprof -alloc_space path/to/binary/zrepl 'http://127.0.0.1:12345/debug/pprof/heap'
```

Please attach the SVG as mention in this or similar posts: https://flaviocopes.com/golang-profiling/

**Comment by JMoVS** [comment]
ok, will keep a look out for it. Happened a few times by now, so chances are high I will run into it again ;-)

**Comment by JMoVS** [comment]
hmm, I don't know how to generate an image. There is no mention of an svg in the post but I have an pb.gz file here now. Does that help?

**Comment by JMoVS** [comment]
Here is the pdf! https://d.pr/free/f/dl5Eut

**Comment by JMoVS** [comment]
I was wondering, might this be the status viewer leaking memory?

**Comment by problame** [comment]
I'll start zrepl status in a tmux session on my setup...
By the way: for continuous monitoring, Prometheus + Grafana would probably be appropriate (there is a read-made dashboard, including a momentary memory allocation gauge): https://zrepl.github.io/configuration/monitoring.html?highlight=grafana

**Comment by JMoVS** [comment]
it's more like I forgot to close it 😆

**Comment by problame** [comment]
No change in allocated system memory on my systems after ~22 hours of continously open `zrepl status`. Must be something else.

**Comment by JMoVS** [comment]
I run zrepl exclusively with local plans and often a source job's pool missing and also the sink-job's pool missing, maybe it's a weird combination of that?

**Comment by problame** [comment]
> I run zrepl exclusively with local plans and often a source job's pool missing and also the sink-job's pool missing, maybe it's a weird combination of that?

Replicated that in a VM, too:
* prometheus listener job
* local sink job
* local source job
  * 0.5s replication interval
* plug-in plug-out pool every 2s 
* watch `watch 'curl 192.168.122.128:6789/metrics | grep heap` number's don't seem to rise

**Comment by JMoVS** [comment]
hmmm

![grafik](https://user-images.githubusercontent.com/7354506/58170718-892de080-7c94-11e9-9d2f-580eeb6bd41d.png)


that happened when I didn't have encryption keys loaded for a drive (both a source and another drain without loaded encryption keys)

**Comment by problame** [comment]
What happened at around 12:07 where the 'number of goroutines' curve becomes flat?
Was that when you connected the `zfssnaps` (right name?) external zpool?

**Comment by JMoVS** [comment]
yes

**Comment by problame** [comment]
ref #195

**Comment by JMoVS** [comment]
Here is the zip as discussed on IRC:

https://d.pr/free/f/M97vVA

**Comment by JMoVS** [comment]
```
jobs:
  - type: sink
    name: "local_sink"
    root_fs: "SeaOfTime/encRoot"
    serve:
      type: local
      listener_name: localsink

  - type: push
    name: "backup_system"
    connect:
      type: local
      listener_name: localsink
      client_identity: SergeantPepperSenior
    filesystems: {
      "ocean<": true,
      "ocean/Users/justin/Library/ApplicationSupport/MobileSync": false
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix: zrepl_
    pruning:
      keep_sender:
      - type: regex
        regex: "zrepl_.*"
        negate: true
      - type: last_n
        count: 20
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h(keep=1) | 35x1d(keep=1) | 6x30d(keep=1) | 24x30d(keep=1) | 6x90d(keep=1)
        regex: "zrepl_.*"
  - type: push
    name: "backup_zweischock"
    connect:
      type: local
      listener_name: localsink
      client_identity: externalDisks
    filesystems: {
      "zweischock/encRoot/zweischock<": true
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix: zrepl_
    pruning:
      keep_sender:
      - type: regex
        regex: "zrepl_.*"
        negate: true
      - type: last_n
        count: 20
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h(keep=1) | 35x1d(keep=1) | 6x30d(keep=1) | 24x30d(keep=1) | 6x90d(keep=1)
        regex: "zrepl_.*"
  - type: snap
    name: snapjob
    filesystems: {
      "ocean/Users/justin/Library/ApplicationSupport/MobileSync": true,
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix: zrepl_
    pruning:
      keep:
      - type: last_n
        count: 60

```
