### ISSUE TITLE
`Job Type pull`: Add filesystem selection like `Job Type source`

### ISSUE THREAD

**Issue by ole-db** [zrepl/zrepl#221]
Please add filesystem selection to `Job Type pull`.  

Example use case:
* many hosts containing virtual machines vm/<uuid>
* central backup host
* all VM backups shoud end up in backup/<uuid> on backup host

**Comment by problame** [comment]
I do not understand how this is not served by `root_fs` ATM:
```
jobs:
- ...
  root_fs=backup/vmhost1
  connect: # ... to vmhost 1
- ...
  root_fs=backup/vmhost2
  connect: # ... to vmhost2
```
