### ISSUE TITLE
Debian / Ubuntu packaging

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#222]
We we want zrepl to be easily usable ref #219 

Tooling:

* fpm (Ruby, ...)
* https://github.com/goreleaser/nfpm (Go only)
  The following config is a draft, but when uninstalling the package, it moves a customized config to .rpmsave instead of leaving it in place
   Untested on Debian
  ```
  # nfpm example config file
  name: "zrepl"
  arch: "amd64"
  platform: "linux"
  version: "v0.2.0"
  section: "default"
  priority: "extra"
  maintainer: "Christian Schwarz <me@cschwarz.com>"
  recommends:
  - zfs
  - zfsutils-linux
  description: |
    FooBar is the great foo and bar software.
      And this can be in multiple lines!
  vendor: "FooBarCorp"
  homepage: "http://eaxmple.com"
  license: "MIT"
  bindir: "/usr/bin"
  files:
    ./artifacts/zrepl-linux-amd64: "/usr/bin/zrepl"
    ./dist/systemd/zrepl.service: "/usr/lib/systemd/system/zrepl.service"
  config_files:
    ./config/samples/local.yml: "/etc/zrepl/zrepl.yml"
  ```
