### ISSUE TITLE
Allow hooks to run before/after group of filesystems/pools

### ISSUE THREAD

**Issue by ltning** [zrepl/zrepl#232]
NOTE: I have not yet tested zrepl with triggers; I'm basing this on the documentation.

Currently, hooks are executed before/after snapshotting of individual datasets. This means that if e.g. MySQL is configured to place data, logs, tables, binary logs, etc. on different datasets or even pools, the provided hooks for flushing tables will not achieve the intended coherent snapshots.

Suggestion: Add a parameter to hooks, e.g. `atomic`; if `true`, and more than one filesystem is listed in the corresponding filesystems: {} block, run the hook before/after snapshots for all the listed filesystems have been created instead of individually before/after each.

Note: This needs to work also for filesystems on different pools. These can not be listed in a single `zfs snapshot ...` command, despite what the man page says - so individual `zfs snapshot` commands must be used. I don't know how `zfs snapshot` is invoked by zrepl so unsure whether this is an issue or not.

**Comment by ltning** [comment]
Can't the mysql hook (or any other hook) be specified several times, with different dsn and a different list of filesystems?

About the multiple pools: Using channel programs won't help here; the operator (me) will have to decide if (s)he is willing to accept the implications of running several snapshot commands during the lock (in order to snapshot filesystems on different pools).

My thinking is that the "atomic" parameter should be available for any type of hook. The naming might be misleading; it isn't atomic per se (epsecially if crossing pools), so a different name may be necessary to avoid false marketing..

**Comment by problame** [comment]
> Can't the mysql hook (or any other hook) be specified several times, with different dsn and a different list of filesystems?

Yes it can. Any reasonable use-case for the *current* state of the hook feature would have disjoint sets of matching filesystems per hook.

> About the multiple pools: Using channel programs won't help here; the operator (me) will have to decide if (s)he is willing to accept the implications of running several snapshot commands during the lock (in order to snapshot filesystems on different pools).

Yes, I'm aware. But channel programs for the single-pool-use-case can actually guarantee atomicity for a group of filesystems, for which we have other reasonable use-cases.

> My thinking is that the "atomic" parameter should be available for any type of hook. The naming might be misleading; it isn't atomic per se (epsecially if crossing pools), so a different name may be necessary to avoid false marketing..

Yep, wasn't happy with that name, but also couldn't figure out a better name.

---

I was also thinking a little bit about my idea of introducing the concept of filesystem groups.
What do you think about the syntax below?
Would you find it easy to explain / understand just from the docs?
How would you deal with the `???` in the last `hook` specification?

```yaml
snapshotting:
  type: periodic
  prefix: zrepl_
  interval: 10m
  groups:
    - name: mysql
      atomic: acknowledge_not_possible # config parser would complain otherwise
                                       # because `filesystems` contains patterns
                                       # that potentially match multiple pools
      filesystems: {
        "hddstorage/mysql/db<": true,
        "ssdstorage/mysql/log": true,
        # "<" # not allowed because config parser cannot extract pool name
      }
    - name: system
      atomic: true # default, no need to specify this
      filesystems: {
        "system/ROOT/fedora": true,
        "system/ROOT/fedoara/var/cache": true,
      }
  hooks:
  - type: command
    path: /etc/zrepl/hooks/zrepl-notify.sh
    timeout: 30s
    err_is_fatal: false
    # no `filesystems`, no `group` => matches any filesystem that is snapshotted

  - type: postgres-checkpoint
    dsn: "host=localhost port=5432 user=postgres password=yourpasswordhere sslmode=disable"
    filesystems: {
        "p1/postgres/data11": true
    }
    # `filesystems` still works, fully backward-compatible

  - type: mysql-lock-tables
    dsn: "zrepl_lock_tables:yourpasswordhere@tcp(localhost)/"
    group: "mysql"
    # `filesystems` and `group` are mutually exclusive (???)

```
