### ISSUE TITLE
Extremely slow performance

### ISSUE THREAD

**Issue by johnramsden** [zrepl/zrepl#240]
I've noticed extremely slow performance, with the transfer rate stuttering between 0 B /s for up to 10 seconds, and then going back to B / s or KB / s.

I'm using pull replication on a FreeNAS server pulling snapshots from two Arch Linux systems.

On the sender machine with the slower connection, I still hit around 60 megabit per second transfer to the server on average using iperf3.

## Versions

- Clients: `zrepl version=arch-0.2.0 GOOS=linux GOARCH=amd64 Compiler=gc`
- Pull server: `zrepl version=v0.2.0 GOOS=freebsd GOARCH=amd64 Compiler=gc`

## Configuration

Server

```yaml
global:
  logging:

    - type: "stdout"
      level:  "info"
      format: "human"

jobs:
  - name: wooly
    type: pull
    connect:
      type: tls
      address: "172.20.20.3:8888"
      ca: "/mnt/tank/system/root/etc/zrepl/wooly.ramsden.network.crt"
      cert: "/mnt/tank/system/root/etc/zrepl/lilan.ramsden.network.crt"
      key: "/mnt/tank/system/root/etc/zrepl/lilan.ramsden.network.key"
      server_cn: "wooly.ramsden.network"
    root_fs: "tank/replication/wooly"
    interval: 15m
    pruning:
      keep_sender:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 30x1d
          regex: "zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 60x1d | 24x30d
          regex: "zrepl_.*"
  - name: enix
    type: pull
    connect:
      type: tls
      address: "172.20.20.2:8888"
      ca: "/mnt/tank/system/root/etc/zrepl/enix.ramsden.network.crt"
      cert: "/mnt/tank/system/root/etc/zrepl/lilan.ramsden.network.crt"
      key: "/mnt/tank/system/root/etc/zrepl/lilan.ramsden.network.key"
      server_cn: "enix.ramsden.network"
    root_fs: "tank/replication/enix"
    interval: 15m
    pruning:
      keep_sender:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 60x1d
          regex: "zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 60x1d | 24x30d
          regex: "zrepl_.*"
```

Client:

```yaml
global:
  logging:

    - type: "syslog"
      level:  "info"
      format: "human"

jobs:
- name: pull_source
  type: source
  serve:
    type: tls
    listen: ":8888"
    ca: /etc/zrepl/lilan.ramsden.network.crt
    cert: /etc/zrepl/wooly.ramsden.network.crt
    key:  /etc/zrepl/wooly.ramsden.network.key
    client_cns:
        - "lilan.ramsden.network"
  filesystems: {
    "vault/sys/wooly<": true,
    "vault/sys/wooly/ROOT/default": true,
    "vault/sys/wooly/ROOT<": false,
    "vault/data<": true,
    "vault/sys/wooly/var/cache": false,
    "vault/sys/wooly/var/lib": false,
    "vault/sys/wooly/var/lib/docker": false,
    "vault/sys/wooly/home/john/local/share/Steam<": false,
    "vault/sys/wooly/var/lib/postgres<": false,
    "vault/sys/wooly/var/lib/mysql<": false,
    "vault/sys/wooly/var/lib/lxd<": false,
    "vault/sys/wooly/var/lib/lxc<": false,
    "vault/sys/wooly/var/lib/machines<": false,
    "vault/sys/wooly/var/lib/systemd/coredump<": false,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 5m
```
