### ISSUE TITLE
could not parse config: yaml: line 14: did not find expected key

### ISSUE THREAD

**Issue by Fossil01** [zrepl/zrepl#247]
So I'm following along the 10 min tutorial, except I'm using plain TCP as the traffic is local. Below is my backup server zrepl.yml but when doing the configcheck I get this:

`could not parse config: yaml: line 14: did not find expected key`

I'm not sure what key it expects. Any pointers? :-)

```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: sink
  type: sink
  serve:
     type: tcp
     listen: "10.10.10.2:8888"
  root_fs: "backup/replicated"
   clients: {
     "10.10.10.1" : "production"
   }
```

```
root@backup:~# zfs list
NAME                           USED  AVAIL  REFER  MOUNTPOINT
backup                         955K  10.5T  34.4K  none
backup/localdata              32.9K  10.5T  32.9K  /home
backup/replicated             65.8K  10.5T  32.9K  /backup
```

**Comment by Fossil01** [comment]
Oh this is the job on  the production box by the way:

```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: prod_to_backups
  type: push
  connect:
    type: tcp
    address: "backup.private:8888"
  filesystems: {
    "rpool/mysql": true,
    "rpool/var/www<": true,
    "rpool/files": true,
    "rpool/covers": true
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 1h
  pruning:
    keep_sender:
    - type: not_replicated
    - type: regex
      regex: "^manual_.*"
    - type: last_n
      count: 12
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
```
