### ISSUE TITLE
Active/standby replication of the same volume

### ISSUE THREAD

**Issue by calmh** [zrepl/zrepl#253]
I'm trying to set up a pair of active/standby servers using zrepl. Under normal operations the active server will have its volumes mounted and services running. The standby server does not run services and doesn't mount its volumes. Zrepl should perform replication from the active to the standby, and when the active fails the standby will take over.

However, I can't find any combinations of jobs that will allow me to replicate `somepool/somevol` on one machine to `somepool/somevol` on the other -- the destination includes at least the full source path, becoming `somepool/somepool/somevol` or the full source path plus device name (`somepool/active-server/somepool/somevol`).

Is this by design or am I missing some trivial setting? Has this been deemed "doing it wrong" and I should so something else?

I can play games with `zfs rename` on both sides when starting zrepl, but this seems fragile and annoying.

**Comment by problame** [comment]
> However, I can't find any combinations of jobs that will allow me to replicate somepool/somevol on one machine to somepool/somevol on the other -- the destination includes at least the full source path, becoming somepool/somepool/somevol or the full source path plus device name (somepool/active-server/somepool/somevol).

You observed correctly that zrepl only supports replicating to a *subtree* below an *existing* `root_fs`, and that `root_fs` cannot be empty.

I suppose that you'd want something like `root_fs: ""` in order to have an exact mirror of your dataset hierarchy on the receiving side. However, zrepl can't create the recv-side root dataset / pool for you. And it can't replace the root dataset  (not 100% sure though).

A more general solution would be to allow the receive side to arbitrarliy map send-side filesystem names to receive-side filesyste names, i.e. a generalized form of rewriting of dataset paths like `zfs recv -d` or `zfs recv -e`.

The main problem with (arbitrary) re-writing instead of simple prefixing (like `root_fs` does) is that arbitrary re-writing is not unambigously reversible, and that's currently required for the replication protocol because the replication engine expects the receiver to present the send-side's dataset paths when it asks the receiver to list received filesystems.
If we assigned replication-invariant GUIDs to filesystems so that we can unambiguously match sender and receiver filesystems during replication, reversibility of rewrites would not be a concern.

**Comment by budachst** [comment]
Just wanted to chime in, that I am facing a very similar issue and I do think, that this is not that uncommon. `A zfs revc -d` like functionality would be very handy to have.

**Comment by candlerb** [comment]
I have a similar use case, i.e. replicate `zfs/data` to `zfs/data`.

Even if `root_fs: ""` were allowed, this still won't work with push jobs because at the sink side the target dataset currently includes the client identity as a prefix: `$root_fs/$client_identity/$source_path`

> A more general solution would be to allow the receive side to arbitrarliy map send-side filesystem names to receive-side filesyste names, i.e. a generalized form of rewriting of dataset paths like zfs recv -d or zfs recv -e.

Since the sender may have multiple sets of filesystems to send, it would be useful if the rewrite were specified at the sender side (even if the implementation would require passing the rule to the client, for the client to apply as an option to `zfs recv`)

This could perhaps be done as an extension of the [filter](https://zrepl.github.io/v0.3.0-rc1/configuration/filter_syntax.html) mechanism, e.g. instead of filter returning true/false it could return the replacement path prefix:

```
filesystems:
  "zfs/foo<": "bar"
  "zfs<": "+"
  "zfs/secret<": "-"
```

With the above:

- `zfs/foo/qux` becomes `<root_fs>/bar/qux`
- `zfs/baz/bap` stays `<root_fs>/zfs/baz/bap` as today
- `zfs/secret/qux` is excluded

Obviously it's impossible to have an unnamed dataset, although you might want

```
"zfs/foo<": ""
```
so that `zfs/foo/baz` becomes `<root_fs>/baz`; it would have to skip `zfs/foo`.

On a related point, I find myself doing the following:

```
    filesystems:
      "zfs/vm<": true
      "zfs/vm": false
      "zfs/lxd/containers<": true
      "zfs/lxd/containers": false
      "zfs/k8s<": true
      "zfs/k8s": false
```

It could be useful to have another metacharacter which means "descendants excluding the parent"

**Comment by problame** [comment]
---
Another user described their use case for this feature in https://github.com/zrepl/zrepl/issues/330
---

> 
> Since the sender may have multiple sets of filesystems to send, it would be useful if the rewrite were specified at the sender side (even if the implementation would require passing the rule to the client, for the client to apply as an option to zfs recv)
> 
> This could perhaps be done as an extension of the filter mechanism, e.g. instead of filter returning true/false it could return the replacement path prefix:
> 
> filesystems:
>   "zfs/foo<": "bar"
>   "zfs<": "+"
>   "zfs/secret<": "-"
> 

I had plans for this right from the beginning when I started developing zrepl.
I'd love to see more syntax suggestions, maybe inspired by pattern matching from functional languages.
However, I fear that in the end, we have the following options to provide ultimate flexibility (but a more complex / less out-of-the-box use experience:
* Use Rego rules (known from Open Policy Agent => embed it as a lib into zrepl). Previously suggested by @smithx10 for IP ACLs https://github.com/zrepl/zrepl/issues/235#issuecomment-544629284
  * I was (and still am reluctant), but OPA seems to grow rapidly in the "cloud-native" ecosystem, don't know how great the overlap with the ZFS community is, though
* Embed Lua or similar (lua-go is usable AFAIK)
* Allow users to shell out to an arbitrary executable (i.e. shell script) that implements the mapping function

**With regards to the main problem arbitrary mappings abovehttps://github.com/zrepl/zrepl/issues/253#issuecomment-562330471 (Read that last paragraph in that post and the come back here)**:
I have experimented with zrepl-assigned filesystem GUIDs (for a new graph-based replication engine that can support ZFS clones) and think that they are the right approach.
I assume that 0.4 will start assigning & using them, which would enable arbitrary mappings + filters.

**Comment by candlerb** [comment]
Maybe anchored regexs, inspired by prometheus label rewriting?

```
# Like: "zfs/foo<": true, "zfs/foo": false
- include: "(zfs/foo/.+)"

# Changing the path
- include: "zfs/foo/(.+)"
  target: "bar/$1"

# Like: "zfs/secret<": false
- exclude: "zfs/secret(/.+)?"

# Like: "zfs<": true
- include: "zfs(/.+)?"
```

**Comment by problame** [comment]
Regexes in filter left-hand-sides has been requested in some other issue. What should happen if regexes overlap, though? At the moment, the most-specific rule wins, similar to how a routing table works.

**Comment by candlerb** [comment]
I'd say test them sequentially, with first match wins - hence a YAML list.

**Comment by problame** [comment]
First-match-wins is good for the sender-to-receiver-mapping.
But we also need the ability to turn that sender-to-receiver-mapping into a filter for *receive*-side datasets so that the receiver knows which receive-side datasets are part of the job and allowed to be considered to receive data from the sender.

**Comment by candlerb** [comment]
That sounds like a question of authorization: i.e. the receiver doesn't trust all clients equally, and needs to enforce what a given client can do.

Today, that's done with `root_fs: foo/bar`, which means "prepend `foo/bar/<client>` to dataset name".  As a first step it could be kept, but changed to mean "allow any dataset under `foo/bar/<client>`"; that is, it would become the sender's responsibility to specify the full target dataset name.

A more flexible mechanism might be a pattern matching ACL, with first-match wins, with a similar sort of syntax as proposed for senders:

```
- permit: "foo/scratch/.+"
- permit: "foo/bar/$client/.+"
- deny: "foo/bar(/.*)?"
# implied default: deny ".*"
```

In terms of applying ACLs, I think there is a limitation in zrepl's architecture with push/pull and source/sink jobs.  AFAICS, the same client can't belong to multiple sink jobs unless each sink job is bound to a different listening port.  If you wanted to specify a distinct ACL per client, then right now it would be a separate job and port per client.

Maybe it would be better to be able to apply ACLs to individual clients under a job - or better, groups of clients which can share the same ACL (which may be because there are multiple addresses for the same client).  e.g.

```
  client_groups:
    - clients:
        "2001:db8::11": "nuc1"
        "2001:db8::12": "nuc2"
        "10.12.255.11": "nuc1"
        "10.12.255.12": "nuc2"
      rules:
        - permit: "storage1/backups/$client"
```

although ideally I'd want a stronger way of identifying a client than their source IP address (e.g. TLS certificate identity), which would make it much more usable when the client is on a dynamic IP.

**Comment by problame** [comment]
So you are suggesting to require the user to specify both the
* sender-filesystem-name-to-receiver-filesystem-name mapping _and_
* an ACL per client on the receiver
?
I suppose you are implicitly suggesting that it's the user's responsibility to keep these in sync?

**Comment by candlerb** [comment]
There would be several options for the sink side:

1. If they trust the push client entirely, then the ACL can allow everything (i.e. push to any pool and dataset)
2. Or the ACL can allow a certain subtree or subtrees, so anything under those is up to the push client
3. Or the sink ACL can be as tight as possible and list only specific datasets.  In this case, it is true that new ACL entries would be required on the sink side whenever changing the push side.

In effect zrepl currently implements (2), where the allowed subtree is only `<rootfs>/<clientid>`

**Comment by problame** [comment]
The conceptual model of zrepl right now is that the `push` side doesn't know the file system hierarchy on the receiver.
The receiver re-maps sender-side filesystem names to their receiver-side names (i.e. currently `sink`  prepends `$rootfs/$clientid`).
This goes so far that when the `push` job requests a list of filesystems and their snapshots from the `sink`, the `sink` job presents the sender the send-side filesystem names (by only listing filesystems under `$rootfs/$clientid` and stripping the `$rootfs/$clientid` prefix).

I have given this issue some thought and have the following proposal:
* Give the sender the ability to define the receive-side file system path
* Limit the sender's access to the receiver, allow the sink to define an ACL that limits what the receiver can see to a certain scope When the sink is requested to list filesystems and snapshots, the results would be limited to that scope.
* And when the push job attempts to push a filesystem to a path prohibited by the ACL, the push job would
  1. not see that there is a file system because it's not in the sink ACL
  2. and consequently attempt initial replication
  3. but the sink would deny the initial replication request with an ACL error.

Proposal for syntax:

```yaml
- type: push
  filesystems: {
    "prodpool<": "backups/zrepl/db1"  # prodpool/foo/bar lands in backups/zrepl/db1/foo/bar
    # "prodpool<": "backups/zrepl/db1/" # prodpool/foo/bar lands in backups/zrepl/db1/prodpool/foo/bar
    # "<": "backups/zrepl/db1" # forbidden, use backups/zrepl/db1/
    # "prodpool<": bool # throws config error indicating to user to run `zrepl migrate config:flexible_filesystem_mapping` for config suggestion
  }

- type: sink
  serve:
    type: tls
    # ...
    client_cns:
    - db1
    - db2
  root_fs: backups/zrepl # throws config error indicating to user to run `zrepl migrate config:flexible_filesystem_mapping` for config suggestion
  acl:
    # This is how things are now: limit the client with client identity $client_id to $root_fs/$client_id
    type: legacy_root_fs
    root_fs: backups/zrepl

    type: rulechain
    default: deny
    rules:
      - permit: "foo/scratch/.+"
      - permit: "foo/bar/$client/.+"
      - deny: "foo/bar(/.*)?"
      # implied default: deny ".*"
    
    type: filesystem_property
    name: com.example:zreplsinkacl:$client
    value_regex: "^on$"

    type: script
    path: /etc/zrepl/sinkacl.bash # $client , $jobid etc are made available as env vars
```

I think `type: script` and `type: filesystem_property` go a bit too far but if the rulechain turns out to be insufficient we can add them in the future.

How do people who subscribe to this issue like this proposal?
Also, I'd ~~encourage~~ ask you to think about how this impacts
* the other two job types `pull` and `source`
* how this impacts usability (e.g. ACL doesn't match, could frustrate new users)
* how a backwards-compatible config could look like if you are content with the general idea of this proposal.

**Comment by workshopit** [comment]
This is the only thing stopping me from using this.
I need to organise my destination datasets a particular way so having the full path added to the destination with no ability to define them is a show stopper.
I really hope this feature is added soon.

**Comment by problame** [comment]
@workshopit which of the syntax proposals would suit your needs? Or do you have another idea for syntax?

**Comment by workshopit** [comment]
@problame I've only got as far as setting up a push task and a corresponding sink task to test zrepl out and I stopped their due to this limitation. This means I'm not too familiar with the current syntax let alone all the features and considerations you've already added but looking at the suggestions so far your last proposal seems acceptable.

**Comment by InsanePrawn** [comment]
Kind of a sidenote, @problame:

> Proposal for syntax:
> 
>     type: rulechain
>     default: deny
>     rules:
>       - permit: "foo/scratch/.+"
>       - permit: "foo/bar/$client/.+"
>       - deny: "foo/bar(/.*)?"
>       # implied default: deny ".*"

Looks like you're reinventing the filesystem filter? How about we add proper syntax for `a/b/c(/.+)?` and `a/b/c/.+` (note how 1 includes c itself. are there more things that need placeholder symbols?) to the existing filesystem filter syntax instead and use one here?

I suspect people would like to mix strings and wildcards like regex `lxd_pool/containers/stable_plsbackup_.+` when other software dictates the dataset layout :(, so we should probably enable that at the same time if possible.

**Comment by problame** [comment]
Request for this feature on reddit: https://www.reddit.com/r/zfs/comments/mt9xw6/zrepl_04_now_available/gv0s3p7/?utm_medium=android_app&utm_source=share&context=3

**Comment by b3niup** [comment]
I'm currently managing quite complex zfs environment and I'd really love to have this feature! 
Any chances it'll be implemented anytime soon?

**Comment by jailbird777** [comment]
This is the one thing keeping us from moving from our ancient zfs-auto-snapshot + syncoid combo to zrepl. We're using basically a fanout to replicate one primary machine to multiple HA/DR machines. As part of this, we keep the source and target pool/filesystem names identical. It not only helps keep things the same, but it also makes having to reverse the syncs much easier.

**Comment by problame** [comment]
@jailbird777 how do you deal with the top-level dataset on the receiver, then? I.e, the dataset that has the same name as the pool. Do you recv -F on it for initial replication?

**Comment by haozhangphd** [comment]
Can we allow `push` job type to **omit** the `client_identity` config field as well? This way the filesystems are received to `$root_fs/$source_path` of the sink, instead of `$root_fs/$client_identity/$source_path`.

Right now there is an obvious asymmetry between `pull` and `push` job types, as `pull` job types do not have this `client_identity`  field. This assymetry makes the snapshot names quite ugly when we have both `push` and `pull` jobs on a same machine.

**Comment by problame** [comment]
Sure. If we're going to allow arbitrary mappings, then you'd be free to use / not use `$client_identity` in the mapping.

**Comment by Halfwalker** [comment]
Just waking this one up again - has there been any progress ?  This is pretty much the only thing keeping me from a full conversion to zrepl.  At least for the replication part ...

I have laptop backups working fine - two systems going to a backup server, which in turn then sends to a pair of paranoid backup servers.  But other datasets need to be replicated to the same dataset naming/hierarchy ...

**Comment by lukas2511** [comment]
I ran into the same roadblock while trying to use zrepl for fan-out replication of media.ccc.de mirrors. My idea was to have one primary mirror with writable filesystem, use zrepl for snapshots and fanout, and in case anything goes wrong I'd just reconfigure another mirror to become writable and reconfigure zrepl accordingly. But for that to work paths on all systems would need to be identical.

**Comment by deajan** [comment]
+1

**Comment by Gui13** [comment]
+1

**Comment by codeedog** [comment]
It's 2026; bumping this feature request.

**Comment by Smithx10** [comment]
Has anyone started to work on this?

@problame,

I've got some time to do the implementation,  last time PR I believe you best communicated what you wanted via writing  a few quick tests I could run my PR against...

If you have an idea of what you'd like the tests to look like or want to write them for the following implementation,  I think I can get this done.

```
- type: push
  filesystems: {
    "prodpool<": "backups/zrepl/db1"  # prodpool/foo/bar lands in backups/zrepl/db1/foo/bar
    # "prodpool<": "backups/zrepl/db1/" # prodpool/foo/bar lands in backups/zrepl/db1/prodpool/foo/bar
    # "<": "backups/zrepl/db1" # forbidden, use backups/zrepl/db1/
    # "prodpool<": bool # throws config error indicating to user to run `zrepl migrate config:flexible_filesystem_mapping` for config suggestion
  }

- type: sink
  serve:
    type: tls
    # ...
    client_cns:
    - db1
    - db2
  root_fs: backups/zrepl # throws config error indicating to user to run `zrepl migrate config:flexible_filesystem_mapping` for config suggestion
  acl:
    # This is how things are now: limit the client with client identity $client_id to $root_fs/$client_id
    type: legacy_root_fs
    root_fs: backups/zrepl

    type: rulechain
    default: deny
    rules:
      - permit: "foo/scratch/.+"
      - permit: "foo/bar/$client/.+"
      - deny: "foo/bar(/.*)?"
      # implied default: deny ".*"
    
    type: filesystem_property
    name: com.example:zreplsinkacl:$client
    value_regex: "^on$"

    type: script
    path: /etc/zrepl/sinkacl.bash # $client , $jobid etc are made available as env vars
```
