### ISSUE TITLE
PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions

### ISSUE THREAD

**Issue by Fossil01** [zrepl/zrepl#256]
So I added another datastore to zrepl.conf and ran `zrepl signal wakeup`. When looking at `zrepl status` it shows this (removed some other datastores for privacy):

```
Job: prod_to_backups
    Type: push
    Replication:
        Attempt #1
        Status: filesystem-error
        Problem: one or more of the filesystems encountered errors
        Progress: [==================================================>] 0 B / 0 B @ 0 B/s
          rpool/covers            DONE (step 0/0, 0 B/0 B)
          rpool/home/USERNAME_REMOVED    PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
          rpool/mysql             DONE (step 0/0, 0 B/0 B)
          rpool/var/www           DONE (step 0/0, 0 B/0 B)
    Pruning Sender:
        Status: ExecErr
        Progress: [>] 0/0 snapshots
        rpool/covers            Completed  (destroy 0 of 12 snapshots)
        rpool/home/USERNAME_REMOVED
            ERROR: replication cursor bookmark does not exist (one successful replication is required before pruning works)
        rpool/mysql             Completed  (destroy 0 of 12 snapshots)
        rpool/var/www           Completed  (destroy 0 of 12 snapshots)
    Pruning Receiver:
        Status: Done
        Progress: [>] 0/0 snapshots
        rpool                   skipped: filesystem is placeholder
        rpool/covers            Completed  (destroy 0 of 54 snapshots)
        rpool/mysql             Completed  (destroy 0 of 54 snapshots)
        rpool/var               skipped: filesystem is placeholder
        rpool/var/www           Completed  (destroy 0 of 54 snapshots)
    Snapshotting:
        Status: SyncUp
        Sleep until: 2019-12-20 16:57:54 +0100 CET

```

/etc/zrepl/zrepl.yaml
```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: prod_to_backups
  type: push
  connect:
    type: tcp
    address: "backup.private:8888"
  filesystems: {
    "rpool/mysql": true,
    "rpool/var/www<": true,
    "rpool/covers": true,
    "rpool/home/USERNAME_REMOVED": true
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 1h
    hooks:
    - type: mysql-lock-tables
      dsn: "zrepl_lock_tables:REMOVED_PASSWORD@tcp(localhost)/"
      filesystems: {
        "rpool/mysql": true
      }
  pruning:
    keep_sender:
    - type: not_replicated
    - type: regex
      regex: "^manual_.*"
    - type: last_n
      count: 12
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
```

I have no clue why this happens though...
