### ISSUE TITLE
Command hook throws "Read-only file system" error

### ISSUE THREAD

**Issue by schulzh** [zrepl/zrepl#258]
Hello,

I have a simple command hook set up to backup my boot folder (its on a separate partition so I dont have to boot from zfs, also EFI boot):
```bash
#!/usr/bin/env bash
set -xe
[[ "$ZREPL_HOOKTYPE" != pre_snapshot ]] && exit 0
[[ -d /boot_back ]] && rm -r /boot_back
cp -r /boot /boot_back
```
```yaml
jobs:
- name: desktop_to_homesrv
  type: push
  [...]
  snapshotting:
    [...]
    hooks:
    - type: command
      path: /etc/zrepl/hooks/backup-boot.sh
      timeout: 30s
      filesystems: {
        "zroot/encr/ROOT/default": true
      }
```
The script works just fine when I execute it manually, however when it gets executed by zrepl, it fails with lots of:
`rm: cannot remove '/boot_back/vmlinuz-linux-custom': Read-only file system`

`/boot_back` is just a normal folder, and the root filesystem is, of course, mounted writable:
```
[...]
/dev/nvme1n1p1 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
zroot/encr/ROOT/default on / type zfs (rw,noatime,xattr,posixacl)
```
Zrepl version:
```
client: zrepl version=v0.2.0 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.2.0 GOOS=linux GOARCH=amd64 Compiler=gc
```
OS is Arch Linux.
