### ISSUE TITLE
zrepl intermittent socket connection errors

### ISSUE THREAD

**Issue by johnramsden** [zrepl/zrepl#262]
## Summary

I've been having intermittent slowdowns of the daemon on the pull side, it seems to occur after the daemon has been running for several hours. It is noticeable in the status page where errors flash about the Unix socket and `EOF`, or trailer.

Once this starts occurring there seems to be a significant slowdown, and after restarting the demon normal performance is seen again.

## System

**Server:**

* OS: FreeNAS-11.2-U7
* `server: zrepl version=v0.2.0 GOOS=freebsd GOARCH=amd64 Compiler=gc`

**Client:**

* Arch Linux 5.4.10-arch1-1
* `client: zrepl version=arch-0.2.1 GOOS=linux GOARCH=amd64 Compiler=gc`

## Configuration

Here's my configuration on the pull server side, I have multiple hosts I'm pulling from but their configuration is all identical.

```
global:
  logging:

    - type: "stdout"
      level:  "info"
      format: "human"

jobs:
  - name: wooly
    type: pull
    connect:
      type: tls
      address: "172.20.20.3:8888"
      ca: "/mnt/tank/system/root/etc/zrepl/wooly.ramsden.network.crt"
      cert: "/mnt/tank/system/root/etc/zrepl/lilan.ramsden.network.crt"
      key: "/mnt/tank/system/root/etc/zrepl/lilan.ramsden.network.key"
      server_cn: "wooly.ramsden.network"
    root_fs: "tank/repl/wooly"
    interval: 15m
    pruning:
      keep_sender:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 30x1d
          regex: "zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 60x1d | 24x30d
          regex: "zrepl_.*"
```

The client servers all have multiple datasets, around 18+ that are being replicated.
