### ISSUE TITLE
pipe2: too many open files

### ISSUE THREAD

**Issue by kevinkk525** [zrepl/zrepl#266]
Lately zrepl status shows me "**rpc error: code = Unknown desc = open /dev/null: too many open files**" or  "**pipe2: too many open files**" for many filesystem entries.
However I am not sure what the reason is, although the error message sounds obvious.

The host system is a ubuntu server machine with standard values, running 6 lxd containers, 1 barely used windows qemu guest and 10 docker containers. None other system has any problem with too many open files, the opened files output is not looking problematic either:
```
more /proc/sys/fs/file-nr
10432   0       1416148
```
Occasionally I get a log entry on the host:
```
localhost zrepl[2358]: 2020-01-20T07:22:21+01:00 [ERRO][pull_source][transportmux]: accept error err="accept tcp [::]:8888: accept4: too many open files" errType="*net.OpError"
```

The client system pulling the snapshots is a ubuntu server in a virtual machine running on Windows 10 with Virtualbox, standard values, nothing else going on:
```
more /proc/sys/fs/file-nr
1344    0       1048575
```
Windows Task Manager says 110,000 Handles, not that problematic either I guess and no other application has any problem.

Zrepl version v0.2.1 GOOS=linux GOARCH=amd64 Compiler=gc from repository

I'm not absolutely sure this is a bug in zrepl but would appreciate an answer.

**Comment by problame** [comment]
Thanks for reporting this issue.
Please post both sides' zrepl.yml (remember to redact potential secrets).
Also: how many filesystems are being pulled from the host?

refs #186

**Comment by kevinkk525** [comment]
Host (without snapshotting part of config):
```
jobs:
- name: pull_source
  type: source
  serve:
    type: tcp
    listen: "0.0.0.0:8888"
    clients: {
      "192.168.178.75" : "backups"
    }
  filesystems: {
      "rpool<": true,
      "rpool/shared/backups": false,
      "rpool/shared/data_kk": true,
      "rpool/shared/musik": true,
      "rpool/shared/filme": true,
      "rpool/shared/isorepo": true,
      "rpool/shared/STORJ3": false,
      "rpool/shared/public": true
    }
  snapshotting:
      type: manual
```

Client:
```
jobs:
- name: pull_servers
  type: pull
  connect:
    type: tcp
    address: "192.168.178.10:8888"
  root_fs: "backup"
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: last_n
      count: 10
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 7x1d
      regex: "zrepl_.*"
```

I'd say it's about 200 filesystems that are being pulled, docker is creating a lot.
