### ISSUE TITLE
Multiple endpoints of the same sink support in the transport

### ISSUE THREAD

**Issue by igsol** [zrepl/zrepl#270]
At first, thanks for superb application.

Would it be possible to add support of multiple destination endpoints in `push` job for `connect` transport?

For instance:

```yaml
jobs:
 - type: push
   connect:
     type: tcp
     address: 
        - "10.23.42.23:8888"     # primary endpoint
        - "192.168.12.34:5678"   # backup endpoint
```

In the above example the sink is the same, but it has 2 different connections via different network links.
Could zrepl use e.g. in round-robin way the supplied endpoints in case if previous one isn't reachable?
