### ISSUE TITLE
ssh transport: connecting side leaks ssh zombie processes if server is not available

### ISSUE THREAD

**Issue by MoritzFago** [zrepl/zrepl#322]
Found my freenas rather unresponsive with >12.000 processes, most of them zombies (<defunct>). They all were descendants of the zrepl deamon.

```yml

jobs:
  - name: namem
    type: pull
    connect:
      type: ssh+stdinserver
      host: hostname
      user: root
      port: 22
      identity_file: /identity
    interval: 10m
    root_fs: "something"

    pruning:
      keep_sender:
        - type: not_replicated
         # keep all snapshots that were not created by zrepl
#        - type: regex
#          negate: true
#          regex: "^zrepl_.*"
        - type: grid
          grid: 1x1h(keep=all)
          regex: "zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
          regex: "zrepl_.*"
        - type: regex
          negate: true
          regex: "^zrepl_.*"
  - name: othername
    type: pull
    connect:
      type: ssh+stdinserver
      host: otherhost
      user: root
      port: 22
      identity_file: file
    interval: 10m
    root_fs: "otherfs"
    pruning:
      keep_sender:
        - type: not_replicated
         # keep all snapshots that were not created by zrepl
        - type: regex
          negate: true
          regex: "^zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
          regex: "zrepl_.*"
        - type: regex
          negate: true
          regex: "^zrepl_.*"
```

freebsd 11.3
client: zrepl version=v0.2.1 GOOS=freebsd GOARCH=amd64 Compiler=gc
