### ISSUE TITLE
failed to create mountpoint

### ISSUE THREAD

**Issue by kevinkk525** [zrepl/zrepl#370]
I just set up zrepl to replicate my new ubuntu20.04 installation to a backup site and it fails with this error:
```
zfs exited with error: exit status 1
            stderr:
            cannot mount '/backup/rpool/ROOT/ubuntu_vzblae': failed to create mountpoint

```
In syslog it logs this:
```
Aug 30 10:04:14 backup zrepl[1100]: [pull_servers][endpoint][XMH7$+xkE$gzxw$gzxw.LFQA./ek9.ge3h]: zfs receive failed opts="zfs.RecvOptions{RollbackAndForceRecv:false, SavePartialRecvState:true}" err="zfs exited with error: exit status 1\nstderr:\ncannot mount '/backup/rpool/ROOT/ubuntu_vzblae/var': failed to create mountpoint\n" local_fs="backup/rpool/ROOT/ubuntu_vzblae/var" proto_fs="rpool/ROOT/ubuntu_vzblae/var"
Aug 30 10:04:14 backup zrepl[1100]: [pull_servers][repl][XMH7$+xkE$gzxw$gzxw.LFQA./ek9]: receive request failed (might also be error on sender) filesystem="rpool/ROOT/ubuntu_vzblae/var" err="zfs exited with error: exit status 1\nstderr:\ncannot mount '/backup/rpool/ROOT/ubuntu_vzblae/var': failed to create mountpoint\n" errType="*zfs.ZFSError" rr="Filesystem:\"rpool/ROOT/ubuntu_vzblae/var\" To:<Name:\"autozsys_9rwwuc\" Guid:6586920582831908394 CreateTXG:2640497 Creation:\"2020-08-30T09:33:47+02:00\" > ClearResumeToken:true ReplicationConfig:<protection:<Initial:GuaranteeResumability Incremental:GuaranteeResumability > > "
```

Additionally it seems that the first replication attempt of a new dataset always fails with an error of being unable to create the dataset. The next iteration then tries to replicate correctly until it hits the error mentioned above.
I have no zrepl snapshotting on the host side yet, only the autozsys from ubuntu.

ubuntu20.04, zrepl 0.3.0 from repository.

host config:
```
jobs:
- name: pull_source
  type: source
  serve:
    type: tcp
    listen: "0.0.0.0:8888"
    clients: {
      "192.168.178.94" : "backup"
    }
  filesystems: {
      "rpool<": true,
      "rpool/docker<": false,
      "rpool/shared<": true
    }
  snapshotting:
      type: manual

```

client config:
```
jobs:
- name: pull_servers
  type: pull
  connect:
    type: tcp
    address: "192.168.178.10:8888"
  root_fs: "backup"
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: last_n
      count: 10
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 7x1d
      regex: "zrepl_.*"
```
