### ISSUE TITLE
zrepl status: Post "http://unix/status": EOF

### ISSUE THREAD

**Issue by dirickxmaarten** [zrepl/zrepl#379]
### Summary
zrepl daemon crashes after all steps (snapshotting, planning, transfer). After the crash, zrepl status reports `Post "http://unix/status": EOF`. The daemon process itself logs an message every 5 seconds: `2020-09-03T14:19:30+02:00 [ERRO][_control][job][m3h8$m3h8]: control handler io error err="write unix /var/run/zrepl/control->: i/o timeout"`

I also noticed that before it eventually crashes, speeds slow down significantly. Starting at 150MB/s, it drops to near-zero. Now and then there are spikes that reach up to 20MB/s.  These are the transfer rates reported by zrepl status. The ascii progressbar happily continues though. I honestly don't know at what point it actually crashes as it takes to long to keep an eye on it. Comparing snapshots on senden and receivers shows no difference, and I conclude it actually finishes the transfer.

The Push server has about 650 filesystems/datasets with each having a couple of hundred of snapshots per dataset.

Note that two distinct zrepl daemons are running on this push server. Their config is stored in /etc/zrepl and /etc/zreplfs3. Zreplfs3 runs without any issues, the issue is only present on the other.

I found somewhat similar behaviour in #262. I'll restart the daemon tomorrow with the logging options: `ZREPL_ACTIVITY_TRACE=/tmp/zrepl.activity.json`
### Version info
**Sender**
OS: FreeBSD 10.3-RELEASE-p21
zrepl: zrepl version=v0.3.0 GOOS=freebsd GOARCH=amd64 Compiler=gc
**receiver**
OS:  CentOS Linux release 8.1.1911 (Core)
zrepl:  zrepl version=v0.3.0 GOOS=linux GOARCH=amd64 Compiler=gc

### Config
**Sender zrepl/zrepl.yml**
```
jobs:
- name: prod_to_backups
  type: push
  connect:
    type: tls
    address: "fs2:8888"
    ca: /etc/zrepl/backups.crt
    cert: /etc/zrepl/prod.crt
    key:  /etc/zrepl/prod.key
    server_cn: "backups"
  filesystems: {
    "pool-09/set10/home<": true,
    "pool-30/set11<": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl
    interval: 1440m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 999999
    keep_receiver:
    - type: last_n
      count: 999999
```
**Sender zreplfs3/zrepl.yml**
```
global:
  control:
    sockpath: /var/run/zreplfs3/control
  serve:
    stdinserver:
      sockdir: /var/run/zreplfs3/stdinserver
jobs:
- name: canopus_to_fs3
  type: push
  connect:
    type: tls
    address: "fs3:8888"
    ca: /etc/zreplfs3/ca.crt
    cert: /etc/zreplfs3/canopus.crt
    key:  /etc/zreplfs3/canopus.key
    server_cn: "fs3"
  filesystems: {
    "ivspool-31/set11<": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl
    interval: 1440m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 999999
    keep_receiver:
    - type: last_n
      count: 999999
```
**Receivers are identical**
```
jobs:
- name: sink
  type: sink
  serve:
     type: tls
     listen: ":8888"
     ca: "/etc/zrepl/prod.crt"
     cert: "/etc/zrepl/backups.crt"
     key: "/etc/zrepl/backups.key"
     client_cns:
       - "prod"
  root_fs: "pool-22/zrepl"
```
