### ISSUE TITLE
Job won't run: attempt does not report done but error report does not report errors...

### ISSUE THREAD

**Issue by helamonster** [zrepl/zrepl#384]
I have zrepl set up between 2 machines using the pull mode with a tcp connection. The source machine is a pfSense server (FreeBSD 11.2-RELEASE-p10) and the destination is an Ubuntu server. When I signal for the job to run I get the following warning message output to syslog:

```
Sep 11 19:07:14 backups zrepl[21761]: 2020-09-11T19:07:14Z [WARN][pull_com_mydomain_dc1_pfsense1][repl][xFhJ$Redx$Redx.MADb.U7x8.cbDF]: attempt does not report done but error report does not report errors, aborting run attempt_number="0"
```
I actually have a few servers (2 pfSense and 2 Ubuntu) for which I am getting the same message. I'm not sure what this means and why the job never seems to start.
I am running the latest release of zrepl (0.3) on both ends.

Target server config (Ubuntu 16.04):
```
global:
  monitoring:
    - type: prometheus
      listen: ':9091'
jobs:
- name: pull_com_mydomain_dc1_pfsense1
  type: pull
  connect:
    type: tcp
    address: "pfsense1.dc1.mydomain.com:8888"
  root_fs: "data/backups/com/mydomain/dc1/pfsense1/CURRENT"
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: regex
      regex: ".*"
```

Source server config (pfSense):
```
global:
  monitoring:
    - type: prometheus
      listen: ':9091'
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- type: source
  name: "com.mydomain.dc1.pfsense1"
  serve:
    type: tcp
    listen: ":8888"
    clients: {
      "10.0.0.16" : "backups.dc1.mydomain.com"
    }
  filesystems: {
    "zpool<": true,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
```

The zrepl daemon is running, which I started with:
```
./zrepl --config zrepl.yml daemon
```
...And I am able to reach the service on port 8888.

Any ideas on why this job won't run?
