### ISSUE TITLE
Active side: Decouple snapshotting and replication intervals

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#386]
Currently, the only way for users to regularly call replication jobs with `snapshotting: manual` is via `zrepl signal wakeup $jobname`.
Since we're pushing for users to be able to decouple snapping and replication by combining snap- and active job types, we should be able to handle this in config.

Config draft:
```yaml
jobs:
- type: push
  [...]
  snapshotting: manual
  replication:
    interval: 10m
```
Behaviours:
a) Implicitly backwards compatible: Replication follows the snapshot interval unless overriden.
b) Strict: Both Intervals/type must always be specified (in applicable job types)
