### ISSUE TITLE
Snap dont prune in receive

### ISSUE THREAD

**Issue by ivanrzk** [zrepl/zrepl#389]
Hi,
I have one hostA int mode push, snap and replicating to another hostB
We have in hostA snap generated manually with openstack with regex @snapshot-*
This is the conf in hostA
```
 snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: regex
      regex: "^(snapshot|autosnap|).*"
    - type: last_n
      count: 24
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
```
In hostA is Ok to keep manually snap but in the hostB dont and is keeping on the receive side.
Ex on hostB:
```
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@zrepl_20200924_140738_000                     
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@zrepl_20200924_141738_000                 
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-95988de2-686c-4fa0-b4ca-bc44aa15bd0e
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-e87657f7-a3ba-4edc-8641-ae7c996cf311
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-eb04b65c-b141-43ba-82c6-e55a9fc0bfa4
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@snapshot-9d3233ea-04aa-4f11-9a9a-d74d3c7697ef
volume-6ab0815b-516c-48de-990a-0ba027ad26f5@zrepl_20200924_142740_000
```
The problem is dont prune the snapshot.* regex in receive side.
What am I doing wrong?
Thx.
Best regards.
