### ISSUE TITLE
ZoL 0.6.5.9-5: send from bookmark on pool dataset fails with 'invalid dataset name'

### ISSUE THREAD

**Issue by MarcusWichelmann** [zrepl/zrepl#396]
After one successful replication, the next replication a few days later failed with the following error:
```
Job: pull_prod-1.xxx                                                                                                                             
    Type: pull                                                                                                                                                
    Replication:                                                                                                                                              
        Attempt #1                                                                                                                                            
        Status: filesystem-error                                                                                                                              
        Problem: one or more of the filesystems encountered errors                                                                                            
        Progress: [>--------------------------------------------------] 0 B / 11.1 GiB @ 0 B/s                                                                
          storage      PLANNING-ERROR (step 0/0, 0 B/0 B)                                                                                                     
            server error: validate send arguments: `From` invalid: zfs exited with error: exit status 1                                                       
            stderr:                                                                                                                                           
            cannot open 'storage#zrepl_CURSOR_G_e6078930438cff56_J_backup_source': invalid dataset name                                                       
          storage/data STEP-ERROR (step 0/178, 0 B/11.1 GiB) parent(s) failed during initial replication: [storage]                                           
    Pruning Sender:                                                                                                                                           
        Status: Done                                                                                                                                          
        Progress: [>] 0/0 snapshots                                                                                                                           
        storage      Completed  (destroy 0 of 178 snapshots)                                                                                                  
        storage/data Completed  (destroy 0 of 179 snapshots)                                                                                                  
    Pruning Receiver:                                                                                                                                         
        Status: Done                                                                                                                                          
        Progress: [>] 0/0 snapshots                                                                                                                           
        storage      Completed  (destroy 0 of 2 snapshots)                                                                                                    
        storage/data Completed  (destroy 0 of 1 snapshots)
```
The replication of another server with nearly the same configuration runs fine.
Do you have any idea what's wrong here?

Source:
```
NAME           USED  AVAIL  REFER  MOUNTPOINT
storage       21.6G  36.0G    19K  none
storage/data  21.5G  36.0G  17.3G  /mnt/data
```
```
jobs:
  - name: backup_source
    type: source
    serve:
      type: tls
      ...
    filesystems: {
      "<": true
    }
    send:
      encrypted: false
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 30m
      hooks:
        - type: command
          path: /etc/zrepl/hooks/lock-mariadb.sh
          timeout: 30s
          err_is_fatal: false
          filesystems: {
            "<": true
          }

```

Target:
```
rpool/backups/servers/prod-1.xxx                     17.3G  4.31T       96K  none
rpool/backups/servers/prod-1.xxx/storage             17.3G  4.31T       88K  none
rpool/backups/servers/prod-1.xxx/storage/data        17.3G  4.31T     17.3G  none
```
```
  - name: pull_prod-1.wichelmann.cloud
    type: pull
    connect:
      type: tls
      ...
    root_fs: "rpool/backups/servers/prod-1.xxx"
    interval: 24h
    pruning:
      keep_sender:
        - type: not_replicated
        - type: regex
          regex: "^manual_.*"
        - type: grid
          regex: "^zrepl_.*"
          grid: 1x1d(keep=all) | 7x1d
      keep_receiver:
        - type: regex
          regex: "^manual_.*"
        - type: grid
          regex: "^zrepl_.*"
          grid: 1x1d(keep=all) | 30x1d | 3x30d

```
