### ISSUE TITLE
Feature Request: Set specific time for replication job

### ISSUE THREAD

**Issue by SoerenBusse** [zrepl/zrepl#397]
We'd like to create backups of our systems at night, when nobody is using it. After reading the documentation I cannot find any solution for running a replication job at a specific time of the day. The only option is to use the "interval" setting with the value "24h", which will run the replication job every 24h after starting the service. 

Let's imagine an unexpected reboot of the backup server at 10am, which will restart all services including the zrepl one and any further replication job will run during the servers "rush hour", which isn't really ideal performance wise.

It would be very good to have a time based replication job feature.

**Comment by problame** [comment]
As a workaround, you can use snapshotting type `manual` + setup a cron job that does the snapshotting and calls `zrepl signal wakeup JOBNAME` to trigger replication at night.

Could you please propose your vision for the YAML config syntax for this feature? I.e. how do you want to specify the times? (hint: Cron-Syntax?)

**Comment by SoerenBusse** [comment]
Thank you for the quick reply.

I think the cron syntax would be a really good idea, because it's easy and well known by many users.

**Comment by schulzh** [comment]
I have a slightly different need for my use case:
Have the snapshotting running all the time according to snapshotting rules (grid etc.) but only replicate at night (so that the upload does not slow down because of replication during the day). Basically have the job behave like `type:snap` during the day and like `type:push` during the night.
I could probably create something like this with two jobs and cron or just set the push url to something invalid during the day but having this integrated would be nice.

**Comment by problame** [comment]
I think @InsanePrawn requested this a couple of times as well.

How about a config syntax like so:

```yaml
- type: push
  snapshotting:
    ...
  replication:
    # replication.trigger defines when we start a replication attempt.
    # If a replication attempt is already in progress when a trigger event occurs,
    # exactly one trigger event is queued so that we do another attempt immediately after
    # the current one finishes (regardless of success or failure).
    # Further trigger events are discarded.
    # For trigger events from replication.trigger.snapshot we log a warning message if they queue up
    # because queuing up most likely indicates that the replication rate cannot keep up with the snapshotting rate / volume.
    trigger:
      on_snapshot: true | false # after we have taken a snapshot (for snapshotting.type = periodic)
      on_signal_wakeup: true | false # when we send the wakeup` signal to the job using `zrepl signal wakeup JOBNAME`
      interval: 10min # every 10 minutes
      cron: "0 3 * * *" # at 3 o clock every day
```

**Comment by schulzh** [comment]
Looks good, but what is the reason behind the `on_signal_wakeup` switch? What would I use the wakeup signal for otherwise?

**Comment by problame** [comment]
Right. The current (implicit) triggers for the replication part of a push job is a wakeup signal or a signal from the snapshotter:

https://github.com/zrepl/zrepl/blob/180c3d9ae1a6e30078d0bdfd58ee73848a0dee01/daemon%2Fjob%2Factive.go#L412-L421

**Comment by schulzh** [comment]
But why the switch then? The wakeup signal is only triggered manually (or is it?); If I don't want it triggering a replication, why would I send it in the first place?

**Comment by problame** [comment]
Yes, it's only triggered manually. The more I think about it a generic `wakeup` signal seems rather ill-guided. Maybe we should change it to `wakeup-replication` or something. @calistoc has added a `snapshot` signal in #418 . So maybe it's time to get rid of `wakeup` completely and have both a `snapshot` and a `replication` signal for push jobs.

**Comment by thefiredragon** [comment]
Dear all, 
I tried this workaround but
could you add the ability to 
```
  snapshotting:
    type: manual
    **prefix: zrepl_**
```
that also manual snapshotting over cron can use own prefix? 
best Regards

**Comment by ahjohannessen** [comment]
@problame I am a having a setup where I have two local pools, one mirrored ssd based for `data` and one mirrored hdd based for `storage` / local different media backup. So, I did that quick start example where I have a job of type snap for `data` and another job of type push to local via sink on `storage` that has snapshotting of type manual. As there is no way, as far as I can tell, to schedule the replication in the yaml file I did this instead:

```bash
#!/usr/bin/env bash
 set -e

 [ "$ZREPL_DRYRUN" = "true" ] && DRYRUN="echo DRYRUN: "

 pre_snapshot() {
     $DRYRUN date
 }

 post_snapshot() {
     $DRYRUN zrepl signal wakeup push_to_local
 }

 case "$ZREPL_HOOKTYPE" in
     pre_snapshot|post_snapshot)
         "$ZREPL_HOOKTYPE"
         ;;
     *)
         printf 'Unrecognized hook type: %s\n' "$ZREPL_HOOKTYPE"
         exit 255
         ;;
 esac
``` 

and added a hook to the snap job:
```yaml
...
  snapshotting:
    type: periodic
    interval: 5m
    prefix: zrepl_
    hooks:
     - type: command
       path: /usr/local/bin/replicate.sh
...
``` 
Is that a prudent way to avoid moving parts like having systemd timer / cron job for that push to local job? At least until that `trigger:` directive is implemented in zrepl?

Thanks a lot for zrepl, takes a bit time to understand, but I definitely appreciate all the thought that has been poured into it.
