### ISSUE TITLE
ZRepl stops working when destination modified

### ISSUE THREAD

**Issue by SoerenBusse** [zrepl/zrepl#434]
Hey there,

we're using zrepl to sync snapshots from our main server to our backup server. For testing the integrity of the backup, I've set a mountpoint at a dataset on the backup server and checked if all important files are in the backup. Afterwards I set the mountpoint back to "none".

This seems to result in an error while doing "zfs send/receive":
```
zfs exited with error: exit status 1                                                                                                                                                                   
            stderr:                                                                                                                                                                                                
            cannot receive incremental stream: destination backup/servers/XXXX/Storage/data has been modified                                                                                    
            since most recent snapshot
```
Normally you would fix this by using the "-F" parameter of "zfs receive". How is it done using "zrepl".

**Comment by SoerenBusse** [comment]
I've solved it by myself: However if anyboy may have the same issue in the future:
I've done a rollback on the backup server to the latest snapshot using `zfs rollback`. To prevent that accessing a file changes the dataset I've disabled atime using `zfs set atime=off <VOLUME>`

**Comment by problame** [comment]
Good that you found the solution yourself. I'm not sure `atime=off` covers all the cases (cc @InsanePrawn  ?)

While I don't consider this a zrepl *bug* it certainly is a usability issue that I'd like to see better addressed.
However, I wouldn't want zrepl to automatically `zfs recv -F` the receiver unless requested by the user.

I could imagine this as another conflict type that we can add to #408 :+1: 

```yaml
type: push # active side
...
conflict_resolution:
  receiver_modified_since_most_recent_snapshot:
    # option 1: fail (current behavior)
    policy: fail
    # option 2: your solution
    policy: rollback-to-most-recent-receive-side-snapshot
```
