### ISSUE TITLE
ssh push job example

### ISSUE THREAD

**Issue by mdimura** [zrepl/zrepl#438]
I am trying to setup zrepl over ssh, with a push+sink and can't quite make it work. I've configured the sender with ssh+stdinserver:
```YAML
jobs:
- name: vms_to_central
  type: push
  connect:
    type: ssh+stdinserver
    host: 192.168.10.11
    user: root
    port: 22
    identity_file: /root/.ssh/id_rsa
...      
```
and receiver:
```YAML
jobs:
- name: dus_vms_sink
  type: sink
  root_fs: "backups"
  serve:
    type: stdinserver
    client_identities:
    - "<sender_hostname>"
```
I guess, there is some obvious mistake in the config, but I can't see it. It works with tcp, but I would prefer ssh. Sorry if there is an answer in the docs, I could not find it.
Is it possible to make setup push+sink config via ssh?
