### ISSUE TITLE
Pruning strategy "keep last N" snapshots crashes

### ISSUE THREAD

**Issue by lgosselin** [zrepl/zrepl#446]
Hi, 

I observe `zrepl` crashes with `last_n` pruning policy. Is there any limitation or forbidden mix in pruning policies?
I have the same output in my syslog with v0.3.1 and v0.4.0-rc1 branch pulled this morning (both recompiled on Ubuntu 20.04 from sources). 

Here is what the **syslog** looks like: 

```
test-backup-server zrepl[153908]: panic: runtime error: slice bounds out of range [10:1]
test-backup-server zrepl[153908]: #011panic: end span: span still has active child spans
test-backup-server zrepl[153908]: goroutine 42 [running]:
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/logging/trace.WithSpan.func2()
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/logging/trace/trace.go:341 +0x308
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/logging/trace.WithTaskAndSpan.func1()
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/logging/trace/trace_convenience.go:40 +0x2e
test-backup-server zrepl[153908]: panic(0xd4ef00, 0xc0031120c0)
test-backup-server zrepl[153908]: #011/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/pruning.KeepLastN.KeepRule(0xa, 0xc000241180, 0xc002fa3200, 0x2e, 0x2e, 0x14fcdc0, 0x0, 0xc0003cd370)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/pruning/keep_last_n.go:60 +0x412
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/pruning.PruneSnapshots(0xc002fa3200, 0x2e, 0x2e, 0xc000264b70, 0x3, 0x3, 0x0, 0x12, 0x2c)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/pruning/pruning.go:31 +0x127
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/pruner.doOneAttempt(0xc000573910, 0xc0005738e8)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/pruner/pruner.go:464 +0xdf2
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/pruner.(*Pruner).prune(0xc003d79540, 0xf13340, 0xc000894030, 0x7f97e02f0210, 0xc0000b5a40, 0x7f97e02ebc20, 0xc0000b5c80, 0xc000264b70, 0x3, 0x3, ...)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/pruner/pruner.go:211 +0x53
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/pruner.(*Pruner).Prune(...)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/pruner/pruner.go:197
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/job.(*ActiveSide).do(0xc000240dc0, 0xf13280, 0xc000032840)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/job/active.go:509 +0x95f
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon/job.(*ActiveSide).Run(0xc000240dc0, 0xf13340, 0xc000265f20)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/job/active.go:424 +0x499
test-backup-server zrepl[153908]: github.com/zrepl/zrepl/daemon.(*jobs).start.func1(0xc000228a80, 0xf13340, 0xc000265350, 0xf19840, 0xc000240dc0)
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/daemon.go:255 +0x171
test-backup-server zrepl[153908]: created by github.com/zrepl/zrepl/daemon.(*jobs).start
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/daemon.go:255 +0x171
test-backup-server zrepl[153908]: created by github.com/zrepl/zrepl/daemon.(*jobs).start
test-backup-server zrepl[153908]: #011/home/lgos/dev/sandboxes/external/zrepl/daemon/daemon.go:251 +0x43e
test-backup-server systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
test-backup-server systemd[1]: zrepl.service: Failed with result 'exit-code'.
```

I'm experimenting in pull mode over tcp+tls.
My active (& crashing) side config looks like this:

```
jobs:
        - name: pull_ds11
          type: pull
          connect:
                  type: tls
                  address: "192.168.122.1:7890"
                  ca: "/etc/zrepl/ca.crt"
                  cert: "/etc/zrepl/test-backup-server.crt"
                  key: "/etc/zrepl/test-backup-server.key"
                  server_cn: "ds11"
          root_fs: rpool/backups/ds11
          interval: 30m
          recv:
                  properties:
                          override: {
                                  "org.openzfs.systemd:ignore": "on",
                                  "mountpoint": "none"
                          }
          pruning:
                  keep_sender:
                          - type: grid
                            grid: 1x1h(keep=all) | 5x1h | 8x1d | 2x30d
                            regex: "^zrepl_.*"
                          - type: regex
                            regex: "^(autozsys|manual).*"

                  keep_receiver:
                          - type: grid
                            grid: 1x1h | 24x1h | 14x1d | 8x1w | 2x30d
                            regex: "^zrepl_.*"
                          - type: regex
                            regex: "^manual_.*"
                            # If uncommented, this part is causing the crash
                            #- type: last_n
                            #count: 10
                            #regex: "^autozsys.*"
          replication:
                  protection:
                          initial: guarantee_resumability
                          incremental: guarantee_incremental
```

I'm currently conducting a series of tests with Ubuntu 20.04, ZFS on root, ZSys and of course some ZFS replication. I came across this project and thought I could probably throw away a few Python & Shell scripts and use it instead. So far it is looking very promising. I think I'm going to adopt it.
