### ISSUE TITLE
Unexpected behavior of zrepl signal [replication|reset|snapshot]

### ISSUE THREAD

**Issue by mafredri** [zrepl/zrepl#451]
Release: `v0.4.0-rc1`

I have a zrepl job defined with `snapshotting.type: manual` where its purpose is to prune snapshots only (snaps generated externally on time machine schedule). From the three (`replication`, `reset`, `snapshot`) I would expect `snapshot` to be the one to trigger the the job (by closest relation?), however, it returns a confusing message:

```
❯ zrepl signal snapshot timemachine
already snapshotting
```

I think something along the lines of `snapshotting is not possible for this job` could be more helpful. Similarly, `reset` does the same:

```
❯ zrepl signal reset timemachine
already reset
```

Finally, `replication` is what activates the job which I find a bit confusing (no replication defined). Not sure what the correct approach here would be. A new signal, `prune`? I don't think it makes sense to reduce the responsibilities of `replication` (i.e. it should probably keep pruning as before), but perhaps it would make sense that we can't signal replication for this type of job?

For completeness, the job is defined as:

```yaml
  - name: timemachine
    type: snap
    filesystems:
      "rpool/data/share/timemachine<": true
      "rpool/data/share/timemachine": false
    snapshotting:
      type: manual
    pruning:
      keep:
        - type: last_n
          count: 15
          regex: "^tm_.*"
        - type: grid
          grid: 7x1d | 2x1w
          regex: "^tm_.*"
```
