### ISSUE TITLE
status fetch: Post "http://unix/status": EOF

### ISSUE THREAD

**Issue by helamonster** [zrepl/zrepl#483]
I've got a zrepl daemon running that `zrepl status` is having trouble connecting to.

Here's my setup:
```
user@server ~ $ uname -a ; lsb_release -a
Linux server.domain.com 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

user@server ~ $ sudo zrepl version
client: zrepl version=v0.4.0 go=go1.15.11 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.4.0 go=go1.15.11 GOOS=linux GOARCH=amd64 Compiler=gc

user@server ~ $ sudo zrepl status --mode raw
Post "http://unix/status": EOF
```
Running the status in the new default mode also gives the following error in the status bar:
`status fetch: Post "http://unix/status": EOF`

The status seems to work fine for a while after starting (or restarting) the zrepl daemon, but it eventually starts having trouble, first momentarily, and eventually permanently (until restarted).

I do have 6 pull jobs configured on this daemon:
```
user@server ~ $ sudo grep '^- name\|^jobs\|^  type' /etc/zrepl/zrepl.yml
jobs:
- name: pull_com_domain_dc2_pfsense1
  type: pull
- name: pull_com_domain_dc2_pfsense2
  type: pull
- name: pull_com_domain_dc2_util
  type: pull
- name: pull_com_domain_dc2_pool
  type: pull
- name: pull_com_domain_dc2_hpool
  type: pull
- name: pull_com_domain_dc1_server-main
  type: pull
```

Looking at the output of `ps` it seems like zrepl is at least doing something (zfs release in this case):
```
user@server ~ $ ps axf
...
2371695 ?        Ssl  159:20 /usr/bin/zrepl --config /etc/zrepl/zrepl.yml daemon
3371907 ?        D      0:00  \_ zfs release zrepl_last_received_J_pull_com_domain_dc2_pfsense1 data/backups/com/domain/dc2/pfsense1/CURRENT/zroot/ROOT@zrepl_20210305_153306_000
...
```
Other times 'ps` shows:
```
2371695 ?        Ssl  159:24 /usr/bin/zrepl --config /etc/zrepl/zrepl.yml daemon
3385401 ?        D      0:00  \_ zfs snapshot rpool/root@zrepl_20210506_213121_000
```
...so its not completely dead, but the status does not work (until the zrepl daemon is restarted). But, obviously, I don't want to keep restarting the daemon (and the zrepl jobs) if it is happily doing the work.

Any ideas on what might be causing this?
I'm pretty sure I was having this problem in 0.3 as well. I was just restarting the daemon when needed, but now that I've got a few jobs running that's not really something I want to keep doing.
I can provide the full config file if needed, but was hoping this might be enough to point me in the right direction.

Thanks,
Jeremy
