### ISSUE TITLE
Concurrency and step errors

### ISSUE THREAD

**Issue by helamonster** [zrepl/zrepl#484]
Increasing concurrency doesn't do entirely what I would expect (and was hoping for). Is this by design?

A job encountering step errors doesn't appear to retry the datasets encountering step errors until all datasets are finished stepping. This causes things to get backed up (meaning both not replicating and keeping old snapshots around) unnecessarily if/when even one dataset takes much longer to step through than others. Shouldn't they be able to retry? Could that be an option or is it fundamentally incompatible with the zrepl design?

Pull job:
```
jobs:
- name: pull_serveralpha-main
  type: pull
  replication:
    concurrency:
      steps: 32
  connect:
    type: tcp
    address: "serveralpha-main.domain.com:8888"
    dial_timeout:  60s
  root_fs: "data/servers/82"
  interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 14x1d
      regex: "zrepl_.*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
      regex: "zrepl_.*"
```

Status:
```
Job: pull_serveralpha-main
Type: pull

Replication:
   Attempt #1
   Status: fan-out-filesystems
   Started: 2021-05-10 15:16:36 -0400 EDT (lasting 3h46m12s)
   Progress: [================================================>--] 176.4 MiB / 182.2 MiB @ 0 B/s
     bpool                                     DONE (step 26/26, 15.8 KiB/15.8 KiB)
     bpool/BOOT                                DONE (step 26/26, 15.8 KiB/15.8 KiB)
     bpool/BOOT/ubuntu                         DONE (step 26/26, 15.8 KiB/15.8 KiB)
     bpool/grub                                DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems                              STEP-ERROR (step 14/26, 8.5 KiB/15.8 KiB) dial tcp 172.16.0.82:8888: i/o timeout
     data/systems/docker                       DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/kvm                          DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/lxd                          DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/lxd/containers               DONE (step 40/40, 24.4 KiB/24.4 KiB)
     data/systems/lxd/containers/myapp         DONE (step 26/26, 103.3 MiB/104.3 MiB)
     data/systems/lxd/custom                   DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/lxd/deleted                  DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/lxd/deleted/containers       DONE (step 38/38, 23.2 KiB/23.2 KiB)
     data/systems/lxd/deleted/custom           DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/lxd/deleted/images           STEP-ERROR (step 14/41, 8.5 KiB/25.0 KiB) dial tcp 172.16.0.82:8888: i/o timeout
     data/systems/lxd/deleted/virtual-machines DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/systems/lxd/images                   STEP-ERROR (step 16/26, 9.8 KiB/15.8 KiB) dial tcp 172.16.0.82:8888: i/o timeout
     data/systems/lxd/virtual-machines         DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/veeam                                DONE (step 26/26, 15.8 KiB/15.8 KiB)
     data/veeam/repo                           DONE (step 26/26, 15.8 KiB/15.8 KiB)
     rpool/ROOT                                DONE (step 26/26, 15.8 KiB/15.8 KiB)
     rpool/ROOT/ubuntu                         DONE (step 26/26, 726.0 KiB/692.4 KiB)
     rpool/ROOT/ubuntu/var                     STEPPING (step 23/26, 72.1 MiB/77.0 MiB) next: @zrepl_20210510_184004_000 => @zrepl_20210510_185004_000 (encrypted=sender-dependent)

Pruning Sender:
   ...

Pruning Receiver:
   ...
```
