### ISSUE TITLE
zrepl cannot resume receive with certain zfs send options enabled even though zfs is capable

### ISSUE THREAD

**Issue by helamonster** [zrepl/zrepl#546]
Subject says it all. I want to enable zrepl resumable send/receives and have all of my datasets send in raw form (not having to uncompress/recompress or unencrypt/reencrypt). Even though I can do this manually, zrepl complains about it being incompatible.

The zrepl error:
```
data/backups/com/domain/subdomain1/server/CURRENT/rootfs PLANNING-ERROR (step 0/0, 0 B/0 B) resume token `rawok`=false and `compressok`=true are incompatible with encryption policy=false        
```

In the associated zrepl job, I have:
```
# rad TO remotebackup.com: No snapshot creation, Prune Source and Destination Snapshots
- name: psh_com_domain_subdomain1_rad_remotebackup.com
  type: push
  connect:
    type: ssh+stdinserver
    host: backups.domain.com
    port: 22
    user: root
    dial_timeout: 60s
    identity_file: /root/.ssh/root@backups.subdomain1.domain.com
    options:
    - "compression=yes"
  send:
    raw: true
    large_blocks: true
    compressed: true
    embbeded_data: true
  filesystems: {
    "data/backups/com/domain/subdomain1/rad/CURRENT/rootfs<": true,
  }
  snapshotting:
    type: manual
  pruning:
    keep_sender:
    - type: regex
      regex: "^readonly"
    - type: not_replicated
    - type: last_n
      count: 12
    - type: grid
      grid: 1x1h(keep=all) | 48x1h | 65x1d | 3x30d
      regex: "^zrepl_"
    keep_receiver:
    - type: regex
      regex: "^readonly"
    - type: last_n
      count: 12
    - type: grid
      grid: 1x1h(keep=all) | 48x1h | 65x1d | 3x30d
      regex: "^zrepl_"
```

With the above config, things work unless a snapshot fails to replicate 100% and then it gives the error above.

I can accomplish the resumed send manually with:
```
zfs send -R -v -e -w -h -L -I data/backups/com/domain/subdomain1/server/CURRENT/rootfs@snap1 data/backups/com/domain/subdomain1/server/CURRENT/rootfs@snap2 | ssh backups.domain.com zfs recv -vusF ...
```
Shouldn't zrepl be able to do the same?
