### ISSUE TITLE
no common snapshot or suitable bookmark between sender and receiver

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#557]
Both servers are FreeBSD 13 p6 on latest branch which still uses zrepl 0.4.0 (upgrade asked).

### Server A config
```yaml
jobs:
- name: to_B
  type: push
  connect:
    type: ssh+stdinserver
    host: server.fr
    user: root
    port: 22
    identity_file: /root/.ssh/id_rsa_zrepl
  filesystems: {
    "zroot<": true,
    "zroot/data<": false,
    "zroot/encrypted<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"

- name: local
  type: snap
  filesystems: {
    "zroot/data<": true,
    "zroot/encrypted<": true,
    "zroot/encrypted/zrepl<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"
```
### Server B config
```yaml
jobs:
- name: from_A
  type: sink
  serve:
    type: stdinserver
    client_identities:
      - "A-push-on-B"
  root_fs: "dpool/data/zrepl"

- name: local
  type: snap
  filesystems: {
    "zroot<": true,
    "dpool/data<": true,
    "dpool/data/zrepl<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"
```

For all datasets, I get those lines in ``/var/log/zrepl.log``
```
Jan 16 19:54:43 iode zrepl[69038]: 2022-01-16T19:54:43+01:00 [ERRO][to_nas][repl][Uv38$EN9y$ytS0$ytS0.UiU5]: conflict filesystem="zroot/ROOT/default" conflict="no common snapshot or suitable bookmark between sender and receiver:\n  sorted sender versions:\n    #zrepl_CURSOR_G_d144fca807a0bebd_J_to_nas\n    @zrepl_20220116_185439_000\n  sorted receiver versions:\n    @zrepl_20220115_000954_000\n    #zrepl_CURSOR_G_14380c7476eda16e_J_to_iode\n    @zrepl_20220115_004957_000\n    @zrepl_20220115_005957_000\n    @zrepl_20220115_183957_000\n    @zrepl_20220115_193959_000\n    @zrepl_20220115_222956_000\n    @zrepl_20220115_232957_000\n    @zrepl_20220116_012959_000\n    @zrepl_20220116_022959_000\n    @zrepl_20220116_033001_000\n    @zrepl_20220116_043959_000\n    @zrepl_20220116_054001_000\n    @zrepl_20220116_064001_000\n    @zrepl_20220116_074002_000\n    @zrepl_20220116_085001_000\n    @zrepl_20220116_103958_000\n    @zrepl_20220116_113959_000\n    @zrepl_20220116_124003_000\n    @zrepl_20220116_134958_000\n    @zrepl_20220116_154001_000\n    @zrepl_20220116_164004_000\n    @zrepl_20220116_175004_000\n    @zrepl_20220116_180001_000\n    @zrepl_20220116_181002_000\n    @zrepl_20220116_182002_000\n    @zrepl_20220116_183005_000\n    @zrepl_20220116_184002_000\n    @zrepl_20220116_185004_000\n"
Jan 16 19:54:43 iode zrepl[69038]: 2022-01-16T19:54:43+01:00 [ERRO][to_nas][repl][Uv38$EN9y$ytS0$ytS0.UiU5]: cannot resolve conflict filesystem="zroot/ROOT/default" problem="no automated way to handle conflict type"
```

**Comment by eoli3n** [comment]
I tried to restart fresh
```bash
# on A
# List holds
$ zfs list -H -r -t snapshot -o name zroot | xargs -n1 zfs holds -H
# Unholds all snapshots
$ zfs list -H -r -t snapshot -o name zroot | xargs -n1 zfs holds -H | awk '{print "zfs release " $2" "$1}' | sh
# Destroy all snapshots
$ zfs list -H -r -t snapshot -o name zroot | xargs -n1 zfs destroy
```
```
# on B
zfs destroy -r dpool/data/zrepl
zfs create dpool/data/zrepl
```

Still same errors in zrepl.log on A

**Comment by problame** [comment]
So, when restarting fresh, you didn't delete the bookmarks, correct?
Check using:
```
A $ zfs list -t bookmark -r -d 1 zroot/ROOT/default
```

**Comment by eoli3n** [comment]
When I restart zrepl service, it waits 5min, is there a way to trigger sync instantly ?

**Comment by problame** [comment]
`zrepl signal wakeup $JOBNAME`, or from `zrepl status`

**Comment by eoli3n** [comment]
So, on both A and B
```bash
$ service zrepl stop
# Unholds all snapshots on all pool
$ zfs list -H -r -t snapshot -o name | xargs -n1 zfs holds -H | awk '{print "zfs release " $2" "$1}' | sh      
# Destroy all snapshots on all pool
$ zfs list -H -r -t snapshot -o name | xargs -n1 zfs destroy      
# Destroy bookmarks on all pools
$ zfs list -t bookmark -H -r -o name | xargs -n1 zfs destroy
$ service zrepl start
```
Then its working well. Now next problem, I want to use the same ssh key to pull from B like
### On A
```yaml
- name: from_B
  type: pull
  connect:
    type: ssh+stdinserver
    host: eoli3n.hd.free.fr
    user: toor
    port: 2222
    identity_file: /root/.ssh/id_rsa_zrepl
  root_fs: zroot/encrypted/zrepl
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"
```
### On B
```yaml
- name: to_A
  type: source
  snapshotting:
    type: manual
  serve:
    type: stdinserver
    client_identities:
      - "iode-pull"
  filesystems: {
    "zroot<": true,
    "dpool/data<": false,
    "dpool/data/git<": true,
    "dpool/data/www<": true
  }
```

It seems that I need to split authorized_command, so in B ``authorized_keys`` I added two lines like
```
command="zrepl stdinserver A-push-on-B",restrict ssh-rsa **************************************** zrepl
command="zrepl stdinserver A-pull-from-B",restrict ssh-rsa **************************************** zrepl
```

Is that the way to ?
