### ISSUE TITLE
use the same ssh key to pull when the key is already used to push

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#560]
### On A
```yaml
jobs:
- name: to_B
  type: push
  connect:
    type: ssh+stdinserver
    host: server.fr
    user: root
    port: 22
    identity_file: /root/.ssh/id_rsa_zrepl
  filesystems: {
    "zroot<": true,
    "zroot/data<": false,
    "zroot/encrypted<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"

- name: local
  type: snap
  filesystems: {
    "zroot/data<": true,
    "zroot/encrypted<": true,
    "zroot/encrypted/zrepl<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"

- name: from_B
  type: pull
  connect:
    type: ssh+stdinserver
    host: server.fr
    user: root
    port: 22
    identity_file: /root/.ssh/id_rsa_zrepl
  root_fs: zroot/encrypted/zrepl
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"
```
### On B
```yaml
jobs:
- name: from_A
  type: sink
  serve:
    type: stdinserver
    client_identities:
      - "A-push-on-B"
  root_fs: "dpool/data/zrepl"

- name: local
  type: snap
  filesystems: {
    "zroot<": true,
    "dpool/data<": true,
    "dpool/data/zrepl<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"

- name: to_A
  type: source
  snapshotting:
    type: manual
  serve:
    type: stdinserver
    client_identities:
      - "A-pull-from-B"
  filesystems: {
    "zroot<": true,
    "dpool/data<": false,
    "dpool/data/git<": true,
    "dpool/data/www<": true
  }
```

It seems that I need to split authorized_keys commands, so in B ``authorized_keys`` I added two lines like
```
command="zrepl stdinserver A-push-on-B",restrict ssh-rsa **************************************** zrepl
command="zrepl stdinserver A-pull-from-B",restrict ssh-rsa **************************************** zrepl
```

Is that the way to ?
