### ISSUE TITLE
push mode creates a parent dataset but pull mode doesn't

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#562]
### On nas
Pushing from iode in ``dpool/data/zrepl`` creates ``dpool/data/zrepl/iode``
```yaml
- name: from_iode 
  type: sink
  root_fs: "dpool/data/zrepl"
[...]
```
```bash
$ root@nas ~# zfs list -r -d2 dpool/data/zrepl
NAME                          USED  AVAIL     REFER  MOUNTPOINT
dpool/data/zrepl             2.54G  1.53T       96K  none
dpool/data/zrepl/iode        2.54G  1.53T       96K  none
dpool/data/zrepl/iode/zroot  2.54G  1.53T       96K  none
```
### On iode
But pulling from nas in ``zroot/encrypted/zrepl`` doesn't create ``zroot/encrypted/zrepl/nas``
```yaml
- name: from_nas
  type: pull
  root_fs: zroot/encrypted/zrepl
[...]
```
```bash
$ root@iode ~# zfs list -r -d1 zroot/encrypted/zrepl
NAME                          USED  AVAIL     REFER  MOUNTPOINT
zroot/encrypted/zrepl        1.98G   441G      208K  /data/zfs/zrepl
zroot/encrypted/zrepl/dpool   154M   441G       96K  none
zroot/encrypted/zrepl/zroot  1.83G   441G      296K  /data/zfs/zrepl/zroot
```
