### ISSUE TITLE
end of chain datasets are placeholders but should not

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#563]
Issue changed, see below

**Comment by eoli3n** [comment]
```bash
$ zfs list -o name,zrepl:placeholder,encryption -r -d 3 zroot/encrypted/zrepl/nas
NAME                                                ZREPL:PLACEHOLDER  ENCRYPTION
zroot/encrypted/zrepl/nas                           -                  aes-256-gcm
zroot/encrypted/zrepl/nas/dpool                     on                 off
zroot/encrypted/zrepl/nas/dpool/data                on                 off
zroot/encrypted/zrepl/nas/dpool/data/git            on                 off
zroot/encrypted/zrepl/nas/dpool/data/www            on                 off
zroot/encrypted/zrepl/nas/zroot                     -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/ROOT                -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/ROOT/default        -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille            -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille/backups    -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille/cache      -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille/jails      -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille/logs       -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille/releases   -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/bastille/templates  -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/tmp                 -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/usr                 -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/usr/home            -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/usr/ports           -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/usr/src             -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/var                 -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/var/audit           -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/var/crash           -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/var/log             -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/var/mail            -                  aes-256-gcm
zroot/encrypted/zrepl/nas/zroot/var/tmp             -                  aes-256-gcm
```
### What should not be a placeholder but is
- ``zroot/encrypted/zrepl/nas/dpool/data/git``
- ``zroot/encrypted/zrepl/nas/dpool/data/www``
### What should be a placeholder but is not
- ``zroot/encrypted/zrepl/nas/zroot/ROOT``

How does zrepl determine if a dataset is a placeholder or not ?

**Comment by eoli3n** [comment]
https://zrepl.github.io/configuration/sendrecvoptions.html#placeholders

> However, for send-plain-encrypt-on-receive, we cannot set -o encryption=off. The reason is that if we did, any of the (non-placeholder) child datasets below the placeholder would inherit encryption=off, thereby silently breaking our encrypt-on-receive use case. So, to cover this use case, we need to create placeholders without specifying -o encryption. This will make zfs create inherit the encryption mode from the parent dataset, and thereby transitively from root_fs.

> The zrepl config provides the recv.placeholder.encryption knob to control this behavior. In undefined mode (default), placeholder creation bails out and asks the user to configure a behavior. In off mode, the placeholder is created with encryption=off, i.e., encrypted-send-to-untrusted-rceiver use case. In inherit mode, the placeholder is created without specifying -o encryption at all, i.e., the send-plain-encrypt-on-receive use case.

"In undefined mode (default), placeholder creation bails out and asks the user to configure a behavior" : zrepl didn't ask anything to me, where would it ask ?

**Comment by eoli3n** [comment]
From matrix:

> How does zrepl determine that a dataset should be a placeholder ?
@InsanePrawn: "if it's excluded from replication but has children to be replicated."

```yaml
  filesystems: {
    "zroot<": true,
    "dpool/data<": false,
    "dpool/data/git": true,
    "dpool/data/www": true
  }
```

So ``dpool/data`` should be a placeholder, but not ``git`` nor ``www```.

**Comment by eoli3n** [comment]
@InsanePrawn told me to try by removing line ``"dpool/data<": false,``.
I confirm that the bug still occurs.

Here are full configs
# pull
```yaml
jobs:
- name: from_nas
  type: pull
  connect:
    type: ssh+stdinserver
    host: server.fr
    user: root
    port: 22
    identity_file: /root/.ssh/id_rsa_nas
  root_fs: zroot/encrypted/zrepl/nas
  #recv:
  #  placeholder:
  #    encryption: inherit
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"
```

# source
```yaml
jobs:
- name: local
  type: snap
  filesystems: {
    "zroot<": true,
    "dpool/data<": true,
    "dpool/data/zrepl<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"

- name: to_iode
  type: source
  snapshotting:
    type: manual
  serve:
    type: stdinserver
    client_identities:
      - "nas"
  filesystems: {
    "zroot<": true,
    "dpool/data/git": true,
    "dpool/data/www": true
  }
```
