### ISSUE TITLE
pull mode: destination pool/dataset has been modified

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#564]
### On A
```yaml
jobs:
- name: from_B
  type: pull
  connect:
    type: ssh+stdinserver
    host: server.fr
    user: root
    port: 22
    identity_file: /root/.ssh/id_rsa_zrepl
  root_fs: zroot/encrypted/zrepl
  interval: 10m
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"
```
### On B
```yaml
jobs:
- name: local
  type: snap
  filesystems: {
    "zroot<": true,
    "dpool/data<": true,
    "dpool/data/zrepl<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d | 1x365d
      regex: "^zrepl_"

- name: to_A
  type: source
  snapshotting:
    type: manual
  serve:
    type: stdinserver
    client_identities:
      - "A-pull-from-B"
  filesystems: {
    "zroot<": true,
    "dpool/data<": false,
    "dpool/data/git<": true,
    "dpool/data/www<": true
  }
```

![pull](https://user-images.githubusercontent.com/14223657/149729129-4877bc80-fe97-4006-97e0-fdc49a445399.png)

The errors are related to the source side. ``zroot/bastille/jails/jekyll/root`` is on the ``source`` side.
Maybe that's because I use the ``snap`` workaround for pull mode ?
https://zrepl.github.io/configuration/prune.html#workaround-using-snap-job

> However, since, jobs are run independently, it is possible that the snap job will prune snapshots that are queued for replication / destruction by the remote pull job that connects to the source job. Symptoms of such race conditions are spurious replication and destroy errors.

In any cases, I do want to keep snapshotting in a separated task. Because of https://github.com/zrepl/zrepl/issues/559, I want to be able to disable ``source`` job, but not ``snap`` one.
