### ISSUE TITLE
[feature request] introduce '>' value for sub datasets only in filesystems key

### ISSUE THREAD

**Issue by eoli3n** [zrepl/zrepl#577]
For 
```
zroot/ROOT
zroot/ROOT/archlinux
zroot/ROOT/voidlinux
```
```yaml
jobs:
- type: snap
  filesystems: {
    "zroot/ROOT<": true,
    "tmp": false
  }
```
Results as snapshotting ``zroot/ROOT`` too.
I would like to be able to only snapshot sub datasets ``archlinux`` and ``voidlinux`` not explicitly, excluding ``ROOT``.

As
```yaml
jobs:
- type: snap
  filesystems: {
    "zroot/ROOT>": true,
    "tmp": false
  }
```
