### ISSUE TITLE
manual snapshot on sink side prevents replication

### ISSUE THREAD

**Issue by Dieken** [zrepl/zrepl#582]
zrepl version=v0.5.0 go=go1.17.6 GOOS=linux GOARCH=amd64 Compiler=gc
Linux manjaro 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux
zfs-2.1.2-1

After I manually create a snapshot on backup pool,  zrepl fails with message:

```
the receiver's latest snapshot is not present on sender
```
I confirmed  `zfs send -I ... | zfs recv ...` works,   so zrepl shouldn't prevent replication.

my /etc/zrepl/zrepl.yml, tailored from /usr/share/zrepl/samples/local.yml,  I add a negate regex to `keep_receiver`.
```
jobs:
  - type: sink
    name: "local_sink"
    root_fs: "b/backup"
    serve:
      type: local
      listener_name: localsink
    recv:
        placeholder:
            encryption: inherit

  - type: push
    name: "backup_system"
    connect:
      type: local
      listener_name: localsink
      client_identity: local_backup
    filesystems: {
      "a/data1<": true,
    }
    snapshotting:
      type: periodic
      interval: 10s
      prefix: zrepl_
    pruning:
      keep_sender:
      - type: not_replicated
      - type: last_n
        count: 10
      keep_receiver:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
        regex: "zrepl_.*"
      - type: regex
        negate: true
        regex: "^zrepl_.*"
```
