### ISSUE TITLE
handle interval & retention grid first interval length

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#59]
I ran into this issue on my personal deployment of zrepl:

```
- name: csnas_local 
  type: pull
  ...
  interval: 4h
  prune:
    policy: grid
    grid: 1x1h (keep=all) | 24x1h | 40x1d | 6x30d
```

The first interval is shorter than the replication interval, which means we will, if remote is on high-freq interval, drop 3h of snapshots immediately after pulling them.
In fact that's another issue: #58

If remote is on >=4h interval (>=pull interval), we get every snapshot but immediately delete it.

We should at least warn if the local pull interval is greater than the first inerval of the retention grid because pull work is lost. Should be via warning on startup and in docs.
