### ISSUE TITLE
Repeated failures: "failed to read from stream"

### ISSUE THREAD

**Issue by callumgare** [zrepl/zrepl#593]
I'm not sure what exactly I'm doing wrong but I haven't yet managed to get zrepl to work reliably for me. Every time I seem to run into the same error:

```
Job: push-to-server-b                                                                                                     
Type: push                                                                                                             
                                                                                                                       
Replication:                                                                                                           
   Attempt #1                                                                                                          
   Status: filesystem-error                                                                                            
   Last Run: 2022-04-15 20:30:42 +1000 AEST (lasted 2h15m59s)                                                          
   Problem: one or more of the filesystems encountered errors                                                          
   Progress: [==================================================>] 233.2 GiB / 230.9 GiB @ 0 B/s                       
     rpool/docker/volumes STEP-ERROR (step 0/1, 233.2 GiB/230.9 GiB) server error: zfs exited with error: exit status 1
      stderr:                                                                                                          
      cannot receive: failed to read from stream                                                                       
      cannot receive new filesystem stream: dataset does not exist
```

I've repeatedly tried again from scratch by removing all snapshots, bookmarks and holds on both sides but no luck.

The config the sending side is:
```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn
  monitoring:
    - type: prometheus
      listen: ':19091'

jobs:
  - name: push-to-server-b
    type: push
    connect:
      type: tls
      address: "server-b.example.com:8888"
      ca: "/etc/zrepl/server-b.example.com.crt"
      cert: "/etc/zrepl/server-a.example.com.crt"
      key:  "/etc/zrepl/server-a.example.com.key"
      server_cn: "server-b.example.com"
    filesystems: {
      # from job snapshot-docker
      "rpool/docker/volumes<": true
    }
    snapshotting:
      type: manual
    pruning:
      keep_sender:
        - type: not_replicated
        - type: grid
          #grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
          grid: 1x1h(keep=all) | 24x1h | 5x1d
          regex: "^zrepl-docker_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl-docker_.*"

  - name: snapshot-docker
    type: snap
    filesystems: {
      "rpool/docker/volumes<": true
    }
    snapshotting:
      type: periodic
      prefix: zrepl-docker_
      interval: 10m
    pruning:
      keep:
        - type: regex
          regex: ".*"
```

And the config on the receiving side is:
```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn
  monitoring:
    - type: prometheus
      listen: ':19091'

jobs:
  - name: receive-from-server-a
    type: sink
    serve:
      type: tls
      listen: ":8888"
      ca: "/etc/zrepl/server-a.example.com.crt"
      cert: "/etc/zrepl/server-b.example.com.crt"
      key: "/etc/zrepl/server-b.example.com.key"
      client_cns:
        - "server-a.example.com"
    root_fs: "faye/zrepl"
```

Anyone have any ideas what might be going wrong? Cheers :)
