### ISSUE TITLE
prune: policy: grid: exception for  keep=all

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#6]
This makes sense but is currently not allowed:

```
  prune:
    policy: grid
    # allow one day of replication lag, then archive
    grid: 1x1d (keep=all) | 24x1h | 40x1d | 6x30d
```
