### ISSUE TITLE
Feature request: Different retention times for different filesystems (via fs specific prefixes or fs specific prune rules)

### ISSUE THREAD

**Issue by callumgare** [zrepl/zrepl#600]
I currently have serverA setup to push a number of filesystems to serverB. Some of those filesystems have data that I'd like to keep snapshots of for a long time, some I only need to keep for a short time. It would be great to have an easy way to specify that. There's two different approaches that occur to me that could work.

You could enable this by allowing the snapshot prefix to be different for different filesystems. That way the existing pruning options could be used for also filtering by filesystems. One advantage of this approach is that since it's a more general solution it could be useful for other use-cases as well (although I can't think of any of the top of my head). An example of this might look like:

```yaml
jobs:
  - name: push-to-serverB
    type: push
    connect:
      ...
    filesystems: {
      "data/very-important": true
      "data/not-so-important" true
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix-per-filesystem: {
        "data/very-important":  zrepl_important_
        "data/not-so-important":  zrepl_not-as-important_
      }
    pruning:
      keep_sender:
        - type: not_replicated
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 5x1d
          regex: "^zrepl_not-as-important_.*"
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 5x1d |  6x30d
          regex: "^zrepl_important_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_not-as-important_.*"
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d | 3x30d
          regex: "^zrepl_important_.*"
```

Alternatively the other option I can think of would be to add a filesystem filter to the pruning rules. For example:

```yaml
jobs:
  - name: push-to-serverB
    type: push
    connect:
      ...
    filesystems: {
      "data/very-important": true
      "data/not-so-important" true
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix: zrepl_
    pruning:
      keep_sender:
        - type: not_replicated
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 5x1d
          regex: "^zrepl_not-as-important_.*"
          filesystems: {
            "data/not-so-important" true
          }
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 5x1d |  6x30d
          regex: "^zrepl_important_.*"
          filesystems: {
            "data/very-important": true
          }
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_not-as-important_.*"
          filesystems: {
            "data/not-so-important" true
          }
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d | 3x30d
          regex: "^zrepl_important_.*"
          filesystems: {
            "data/very-important": true
          }
```

Thanks for your consideration! :)

**Comment by 3nprob** [comment]
You can already kind of achieve the first option by splitting it up into two jobs with different prefixes.

However, I'd also be in favor for (some variation of) the second approach. The benefit here is that it can facilitate decoupling pruning policies and jobs.

One use-case for this: A single pull job has been set up to replicate several filesystems from one source. Months later, we want to set differing replication policies for them, while keeping them similar otherwise. This isn't really possible today AFAICT, since they have the same `prefix` and there is therefore no way the `regex` on snapshot names can differentiate between them.
So allowing to differentiate between fses in pruning policies within the same job (with the same snapshot prefixes) would allow you to change pruning policies per-fs on existing multi-fs jobs. 

Alternative proposal:
Add optional `fs_regex` field to `regex`, `grid`, `last_n` policies. This can be used to differentiate on filesystem level. Your example could look like this:

```
jobs:
  - name: push-to-serverB
    type: push
    connect:
      ...
    filesystems: {
      "data/very-important": true
      "data/not-so-important" true
    }
    snapshotting:
      type: periodic
      interval: 10m
      prefix: zrepl_
    pruning:
      keep_sender:
        - type: not_replicated
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 5x1d
          regex: "^zrepl_.*"
          fs_regex: "data/not-so-important$"
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 5x1d |  6x30d
          regex: "^zrepl_*"
          fs_regex: "data/very-important$"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_.*"
          fs_regex: "data/not-so-important$"
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d | 3x30d
          regex: "^zrepl_.*"
          fs_regex: "data/very-important$"
```

Tangentially related to #102

**Comment by problame** [comment]
> This isn't really possible today AFAICT, since they have the same prefix and there is therefore no way the regex on snapshot names can differentiate between them.
So allowing to differentiate between fses in pruning policies within the same job (with the same snapshot prefixes) would allow you to change pruning policies per-fs on existing multi-fs jobs.

^ That's the use case distilled down

---

```
  keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_.*"
          filesystems: {
            "data/not-so-important" true
          }
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d | 3x30d
          regex: "^zrepl_.*"
          filesystems: {
            "data/very-important": true
          }
```

I like the syntax.
---

> Alternative proposal:
Add optional fs_regex field to regex, grid, last_n policies. This can be used to differentiate on filesystem level. Your example could look like this:

```
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d
          regex: "^zrepl_.*"
          fs_regex: "data/not-so-important$"
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d | 3x30d
          regex: "^zrepl_.*"
          fs_regex: "data/very-important$"
```

The regex is going to be ugly / less predictable than the `filesystems` filter.

---

**Let's settle on an option `filesystems` field for all the pruning rules.**

I'm open to pull requests that extend the existing pruning code to handle this.
The pull request will need to update the documentation as well
