### ISSUE TITLE
No pruning of filesystems without correspondence on sink leads to filling up of disk

### ISSUE THREAD

**Issue by atisharma** [zrepl/zrepl#606]
I recently got into an unexpected situation where I migrated a database to a new server, which uses a zrepl push job, and has a newer major version of zrepl than the sink.

Because the sink had not been upgraded yet, the initial replication of the database dataset could not start. Since there was no initial replication, source snapshots are not pruned (I guess as per issue #126). With 5m snapshots this led to the quick filling up of the disk and in turn to corruption of the database, and I restored from backup (though I suppose Icould have rolled back using the snapshots).

There is an element of user error here, however the documentation does not describe this behaviour. The documentation in `docs/configuration/pruning policies` states 

> Source-side snapshot pruning
> 
> A [source jobs](https://zrepl.github.io/configuration/jobs.html#job-source) takes snapshots on the system it runs on. The corresponding [pull job](https://zrepl.github.io/configuration/jobs.html#job-pull) on the replication target connects to the source job and replicates the snapshots. Afterwards, the pull job coordinates pruning on both sender (the source job side) and receiver (the pull job side).
> 
> There is no built-in way to define and execute pruning on the source side independently of the pull side. The source job will continue taking snapshots which will not be pruned until the pull side connects. This means that extended replication downtime will fill up the source’s zpool with snapshots.
> 
> If the above is a conceivable situation for you, consider using [push mode](https://zrepl.github.io/configuration/jobs.html#job-push), where pruning happens on the same side where snapshots are taken.

The last paragraph led me to believe I would be safe using push mode and that pruning would occur when the the sinkk is offline.

In my opinion, either pruning should occur as specified in `zrepl.yaml` with the initial replication from the first surviving snapshot, or the deviation from that behaviour should be clearly stated in `docs/configuration/pruning policies` in the first section, with the warning that no pruning will occur in any mode unless the initial replication has completed.

**Comment by problame** [comment]
> The last paragraph led me to believe I would be safe using push mode and that pruning would occur when the the sink is offline.

If you're using a `push` job, then the expected behavior is that the sending side (i.e., the one with the `push` job) gets pruned, even if the sink side is unreachable, or even has never been reachable.

Do I understand correctly that you had such a setup, but observed that no snapshots were pruned?

Also: do you have a `not_replicated` keep rule on the sender? That would of course keep all unreplicated snapshots.

**Comment by atisharma** [comment]
Yes, push job, no pruning. I did not have a `not_replicated` flag on the sender. After the first successful full replication, pruning started.

Here is my (abbreviated) sender yaml:

```
global:
  logging:
  - format: human
    level: error
    type: stdout
  - format: logfmt
    level: warn
    type: syslog
jobs:
- connect:
    address: jupiter.letterbox.pw:8888
    type: tcp
  filesystems:
    zbackup<: true
    zdb<: true
    zsol/nixos/var/log<: false
    zsol/nixos/var/mail<: false
    zsol/nixos/var/spool: false
    zsol<: true
    zstorage<: true
    ztrading<: true
  name: sol_push
  pruning:
    keep_receiver:
    - grid: 1x1h(keep=all) | 48x1h | 30x1d | 12x30d
      regex: ^zrepl_
      type: grid
    keep_sender:
    - regex: ^manual_
      type: regex
    - grid: 1x1h(keep=all) | 24x1h | 30x1d | 3x30d
      regex: ^zrepl_
      type: grid
  send:
    encrypted: false
  snapshotting:
    interval: 20m
    prefix: zrepl_
    type: periodic
  type: push
```
