### ISSUE TITLE
Timers don't resume counting after system suspend/resume cycle

### ISSUE THREAD

**Issue by kpfleming** [zrepl/zrepl#611]
I've got zrepl configured this way:

```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
  - name: daily
    type: snap
    filesystems:
      "bpool/boot<": true
      "rpool/root<": true
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 24h
    pruning:
      keep:
        - type: regex
          regex: "^zrepl_.*"
          negate: true
        - type: grid
          regex: "^zrepl_.*"
          grid: 7x24h | 4x168h
```

I set it up for the first time on my laptop on 2022-06-25. After starting the service, it made a set of snapshots for the 'daily' job as expected. Running 'zrepl status' showed that the 'daily' job was waiting until the same time of day on 2022-06-26 to make the next set of snapshots.

On 2022-06-29, after having suspended/resumed the laptop a number of times, I ran 'zrepl status' to see what had been happening. The 'daily' job still showed that it was waiting until the chosen time on 2022-06-26, even though that time had passed three days prior.
