### ISSUE TITLE
high ressource usage / DoS probably caused by zrepl config

### ISSUE THREAD

**Issue by mtippmann** [zrepl/zrepl#623]
Hi, as requested an issue for my problem as reported in the matrix chat - caveat: I'm not sure if zrepl is responsible for the problems but after changing the config back everything was okay again. 

my goal was to sync the ssd pool to the m18 pool - however the problem might totally on my side / wrong configuration. 

```
mt@epithymetikon:~$ zpool version 
zfs-2.1.5-1~20.04.york0
zfs-kmod-2.1.5-1~20.04.york0
``` 

filterd everything related to transportmux: 

[error.log](https://github.com/zrepl/zrepl/files/9184737/error.log)

`zrepl.yaml`: 

```

global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
# Separate job for snapshots and pruning
- name: snapshots
  type: snap
  filesystems:
    'm18<': true # all filesystems
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 1h
  pruning:
    keep:
      # Keep non-zrepl snapshots
      - type: regex
        negate: true
        regex: '^zrepl_'
      # Time-based snapshot retention
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d | 3x30d
        regex: '^zrepl_'


- type: sink
  name: "ssd_sink"
  root_fs: "m18/backup"
  serve:
    type: local
    listener_name: localsink
  recv:
    properties:
      inherit:
        - "mountpoint"
      override: {
        "org.openzfs.systemd:ignore": "on"
      }

- type: push
  name: "backup_ssd"
  connect:
    type: local
    listener_name: localsink
    client_identity: local_backup
  filesystems: {
    "ssd<": true,
  }
  snapshotting:
    type: periodic
    interval: 5m
    prefix: ssd_
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d
      regex: "ssd_.*"

# Source job for backup on acedia.stuko.uni-weimar.de
- name: backup_m18
  type: source
  send:
    send_properties: true
    # https://github.com/zrepl/zrepl/pull/503
    #    compressed: true
  serve:
    type: tls
    listen: :8888
    ca: /etc/zrepl/acedia.stuko.uni-weimar.de.crt
    cert: /etc/zrepl/m18.uni-weimar.de.crt
    key: /etc/zrepl/m18.uni-weimar.de.key
    client_cns:
      - acedia.stuko.uni-weimar.de
  filesystems:
    'm18<': true # all filesystems
  # Snapshots are handled by the separate snap job
  snapshotting:
    type: manual
# see /usr/share/doc/zrepl/examples
# or https://zrepl.github.io/configuration/overview.html
```
