### ISSUE TITLE
atomicity

### ISSUE THREAD

**Issue by silenius** [zrepl/zrepl#630]
Hello,

I have a question regarding snapshots taken by `zrepl` and atomicity. Suppose we'd like to backup two datasets, for example `zroot/pg13/data` and `anotherpool/pg13/wal`. Given the following `snap` job on the machine:

```yaml
jobs:
  - name: somesnapshot
    type: snap
    filesystems: {
      "zroot/pg13/data<": true,
      "anotherpool/pg13/wal": true,
    }
    snapshotting:
       # more here
```
Are snapshots guaranteed to be atomic in such case? For some applications, it is critical.
ZFS guarantees atomicity either through `zfs snapshot -r ds` OR `zfs snapshot ds1@n1 ds2@n2 ...`. In the example above, how does `zrepl` takes the snapshots ? Does it issues two `zfs snapshot` (in which case atomicity is not guaranteed) or only one? 

Thanks
