### ISSUE TITLE
Fan-out: 1 server replicated to N receivers

### ISSUE THREAD

**Issue by silenius** [zrepl/zrepl#631]
Hello,

Unless I am missing something it looks like it is currently impossible to backup N servers to A and B properly. Concretely we have a bunch of servers that need to be backuped to local and off-site storage (we snapshot every 15 min). Backup to off-site storage takes sometimes a lot of time (1 day).
I've read the various documentation about "Fan-out replication" on the zrepl website, it somewhat works but with the setup (https://zrepl.github.io/quickstart/fan_out_replication.html) there is one major issue: snapshots are pruned before they're backuped... am I missing something?

Couldn't zrepl holds snapshots that still need to be backuped?

Thanks!

**Comment by silenius** [comment]
I'm also getting tons of STEP-ERROR with this setup:

     zroot_srv/data                              STEP-ERROR (step 1/10, 624 B/6.1 KiB) zfs exited with error: exit status 1                                                                                                          ▒║
║      stderr:                                                                                                                                                                                                                        ▒║
║      cannot receive incremental stream: destination zroot_srv/data/jails/zsync/srv/zroot_srv/data has been modified                                                                                                                 ▒║
║      since most recent snapshot                                                                                                                                                                                                     ▒║
║                                                                                                                                                                                                                                     ▒║
║     zroot_srv/data/jails                        STEP-ERROR (step 1/15, 624 B/9.1 KiB) zfs exited with error: exit status 1                                                                                                          ▒║
║      stderr:                                                                                                                                                                                                                        ▒║
║      cannot receive incremental stream: destination zroot_srv/data/jails/zsync/srv/zroot_srv/data/jails has been modified                                                                                                           ▒║
║      since most recent snapshot                                                                                                                                                                                                     ▒║
║                                                                                                                                                                                                                                     ▒║
║     zroot_srv/data/jails/amq1                   STEPPING (step 2/2, 624 B/1.2 KiB) next: @zrepl_20220921_200454_000 => @zrepl_20220921_202042_000 (encrypted=sender-dependent)                                                      ▒║
║     zroot_srv/data/jails/certbot                STEPPING (step 1/2, 0 B/1.2 KiB) next: @zrepl_20220921_195001_000 => @zrepl_20220921_200501_000 (encrypted=sender-dependent)                                                        ▒║
║     zroot_srv/data/jails/geoserver1             STEPPING (step 1/2, 0 B/1.2 KiB) next: @zrepl_20220921_195002_000 => @zrepl_20220921_200504_000 (encrypted=sender-dependent)                                                        ▒║
║     zroot_srv/data/jails/geoserver2             STEPPING (step 1/2, 0 B/1.2 KiB) next: @zrepl_20220921_194954_000 => @zrepl_20220921_200507_000 (encrypted=sender-dependent)                                                        ▒║
║     zroot_srv/data/jails/geoserver3             STEPPING (step 2/2, 624 B/1.2 KiB) next: @zrepl_20220921_200457_000 => @zrepl_20220921_202042_000 (encrypted=sender-dependent)                                                      ▒║
║     zroot_srv/data/jails/home                   STEPPING (step 2/2, 624 B/1.2 KiB) next: @zrepl_20220921_200454_000 => @zrepl_20220921_202048_000 (encrypted=sender-dependent)                                                      ▒║
║     zroot_srv/data/jails/mail                   STEPPING (step 2/2, 299.5 MiB/299.8 MiB) next: @zrepl_20220921_200459_000 => @zrepl_20220921_202055_000 (encrypted=sender-dependent)                                                ▒║
║     zroot_srv/data/jails/mailman                STEPPING (step 2/2, 624 B/1.2 KiB) next: @zrepl_20220921_200458_000 => @zrepl_20220921_202056_000 (encrypted=sender-dependent)                                                      ▒║
║     zroot_srv/data/jails/nextcloud              STEPPING (step 1/2, 0 B/1.2 KiB) next: @zrepl_20220921_194958_000 => @zrepl_20220921_200500_000 (encrypted=sender-dependent)                                                        ▒║
║     zroot_srv/data/jails/pg11                   STEP-ERROR (step 1/12, 624 B/7.3 KiB) zfs exited with error: exit status 1                                                                                                          ▒║
║      stderr:                                                                                                                                                                                                                        ▒║
║      cannot receive incremental stream: destination zroot_srv/data/jails/zsync/srv/zroot_srv/data/jails/pg11 has been modified                                                                                                      ▒║
║      since most recent snapshot                                                                                                                                                                                                     ▒║
║                                                                                                                                                                                                                                     ▒║

(sorry for the ouput, it's a copy/paste of the zrepl status)

**Comment by silenius** [comment]
this is my config:

# Machine to be backuped:

```yaml
global:
  logging:
    - type: "stdout"
      level:  "error"
      format: "human"
    - type: "syslog"
      level:  "info"
      format: "logfmt"

jobs:
  - name: snap_zroot_srv
    type: snap
    filesystems: {
      "zroot_srv<": true,
      "zroot_srv/data/jails/zsync<": false,
      "zroot_srv/jails/zsync<": false
    }
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 15m
    pruning:
      keep:
        - type: regex
          negate: true
          regex: '^zrepl_'
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 7x1d
          regex: "^zrepl_"
  - name: sync_srv_zsync
    type: source
    snapshotting:
      type: manual
    serve:
      type: tcp
      listen: "srv.lan:8888"
      clients: {
        "192.168.0.39": "srv.lan"
      }
    filesystems: {
      "zroot_srv<": true,
      "zroot_srv/data/jails/zsync<": false,
      "zroot_srv/jails/zsync<": false
    }
```

# Backup machine:

(FreeBSD jail with jailed dataset)

```yaml
global:
  logging:
    - type: "stdout"
      level:  "error"
      format: "human"
    - type: "syslog"
      level:  "info"
      format: "logfmt"

jobs:
  - name: sync_srv_zsync 
    type: pull
    connect:
      type: tcp
      address: "srv.lan:8888"
    root_fs: "zroot_srv/data/jails/zsync/srv"
    interval: 5m
    pruning:
      keep_sender:
        - type: regex
          regex: ".*"
      keep_receiver:
      - type: regex
        negate: true
        regex: '^zrepl_'
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d
        regex: '^zrepl_'
```

**Comment by kpfleming** [comment]
Your pruning rules need to be setup so that all snapshots will kept for at least as long as it takes to do a replication. If it can take 24 hours to replicate, and you're creating snapshots every 15 minutes, you can't keep just one per hour for that first 24 hour period.

Change your pruning rules to keep *all* snapshots for 48 hours, or something like that, and then start pruning.

**Comment by kpfleming** [comment]
You may also want to add a ['not-replicated'](https://zrepl.github.io/configuration/prune.html#policy-not-replicated) rule to your pruning configuration.

**Comment by silenius** [comment]
> Your pruning rules need to be setup so that all snapshots will kept for at least as long as it takes to do a replication. If it can take 24 hours to replicate, and you're creating snapshots every 15 minutes, you can't keep just one per hour for that first 24 hour period.
> 
> Change your pruning rules to keep _all_ snapshots for 48 hours, or something like that, and then start pruning.

Thanks, that makes sense. I thought there was some kind of protection on the zrepl side to ensure that incremental replication will always find required snapshots. I'll give a try with a `not_replicated` policy. I wonder if it will work with one `snap` job + two `source` jobs on the server side and two `pull` jobs (one local, one remote) from the backup machines. For example, if snapshots have been replicated on storageA (through a `pull` job) but not yet (or in progress...) on storageB will `not_replicated` policy succeed?

**Comment by silenius** [comment]
also, a `not_replicated` policy can't be used in a `snap` job (got a ```cannot build jobs from config: cannot build job "snap_zroot_srv": cannot build snapjob pruning rules: single-site pruner cannot support `not_replicated` keep rule```)

**Comment by silenius** [comment]
I'm still having the same error, even with `grid: 1x12h(keep=all) | 24x1h | 7x1d` (I'm testing on my local machine, initial replication took ~6h00 and no shapshot have been deleted) .. so something doesn't work

**Comment by silenius** [comment]
I still have errors despite the fact that I kept all the snapshots on both sides. It looks like some snapshots aren't transfered properly, for example:

```
║     zroot_srv/var/log                           STEP-ERROR (step 1/47, 1.0 MiB/109.3 MiB) zfs exited with error: exit status 1                                                                                  ▒║
║      stderr:                                                                                                                                                                                                    ▒║
║      cannot receive incremental stream: destination zroot_srv/data/jails/zsync/srv/zroot_srv/var/log has been modified                                                                                          ▒║
║      since most recent snapshot                                                                                                                                                                                 ▒║
```

But when I'm listing snapshots I'm getting:
```
~/ zfs list -t snapshot|grep var/log
zroot_srv/data/jails/zsync/srv/zroot_srv/var/log@zrepl_20220922_194508_000                            9.98M      -     12.3M  -
zroot_srv/var/log@zrepl_20220922_194508_000                                                            302K      -     12.3M  -
zroot_srv/var/log@zrepl_20220922_200008_000                                                            203K      -     12.4M  -
zroot_srv/var/log@zrepl_20220922_201651_000                                                            215K      -     12.4M  -
zroot_srv/var/log@zrepl_20220922_203114_000                                                            232K      -     12.4M  -
zroot_srv/var/log@zrepl_20220922_204517_000                                                            221K      -     12.5M  -
(...)
```

(zroot_srv/var/log is the source on host A, zroot_srv/data/jails/zsync/srv/zroot_srv/var/log is the target on host B which is a FreeBSD jail with a jailed dataset)

Here is my config:

**host A (machine to backup):**

```yaml
global:
  logging:
    - type: "stdout"
      level:  "error"
      format: "human"
    - type: "syslog"
      level:  "info"
      format: "logfmt"

jobs:
  - name: snap_zroot_srv
    type: snap
    filesystems: {
      "zroot_srv<": true,
      "zroot_srv/data/jails/zsync<": false,
      "zroot_srv/jails/zsync<": false
    }
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 15m
    pruning:
      keep:
        - type: regex
          negate: true
          regex: '^zrepl_'
        - type: grid
          grid: 1x12h(keep=all) | 24x1h | 7x1d
          regex: "^zrepl_"
  - name: sync_srv_zsync
    type: source
    snapshotting:
      type: manual
    serve:
      type: tcp
      listen: "srv.lan:8888"
      clients: {
        "192.168.0.39": "zrepl.lan"
      }
    filesystems: {
      "zroot_srv<": true,
      "zroot_srv/data/jails/zsync<": false,
      "zroot_srv/jails/zsync<": false
    }
```

**Host B (backup machine):**

```yaml
global:
  logging:
    - type: "stdout"
      level:  "error"
      format: "human"
    - type: "syslog"
      level:  "info"
      format: "logfmt"

jobs:
  - name: sync_srv_zsync 
    type: pull
    connect:
      type: tcp
      address: "srv.lan:8888"
    root_fs: "zroot_srv/data/jails/zsync/srv"
    interval: 5m
    pruning:
      keep_sender:
        - type: regex
          regex: ".*"
      keep_receiver:
      - type: regex
        negate: true
        regex: '^zrepl_'
      - type: grid
        grid: 1x12h(keep=all) | 24x1h | 30x1d
        regex: '^zrepl_'
```
