### ISSUE TITLE
Push job: parent(s) failed during initial replication

### ISSUE THREAD

**Issue by marceldegraaf** [zrepl/zrepl#650]
I'm trying to set up a backup scheme that's a combination of the "Local Snapshot" and the "Continuous Backup of a Server" examples. Specifically, this is what I'm trying to accomplish:

1. Every 10 minutes create a snapshot from my local `/home` directory (which has its own zpool). This is represented by the `local-backup` job below (using the `dump/zrepltest` filesystem to test with, for now);
2. Push these snapshots to a separate, local backup zpool. This is represented by the `local-sink` job below;
3. From the backup zpool, push snapshots to a remote server periodically, which is configured in the `remote-push` job below

Creating snapshots on the local zpool works, although I noticed a few intermediate placeholders are created in the process:

```
$ zfs list

tank/zrepl                        1.34M  35.5T      153K  /mnt/zrepl
tank/zrepl/server                 1.19M  35.5T      153K  none
tank/zrepl/server/dump            1.04M  35.5T      153K  none
tank/zrepl/server/dump/zrepltest   907K  35.5T      300K  none
```

This seems to trip up the `remote-push` job, which fails with `PLANNING-ERROR` status for each of the intermediate placeholders, and then fails with a `STEP-ERROR` on the actual dataset because `parent(s) failed during initial replication`:

```
Attempt #1
Status: filesystem-error
Last Run: 2022-11-10 14:01:32 +0100 CET (lasted 0s)
Problem: one or more of the filesystems encountered errors
Progress: [==================================================>] 0 B / 0 B @ 0 B/s
  tank/zrepl                       PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
  tank/zrepl/server                PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
  tank/zrepl/server/dump           PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
  tank/zrepl/server/dump/zrepltest STEP-ERROR (step 0/0, 0 B/0 B) parent(s) failed during initial replication: [tank/zrepl/server]
``` 

If I update the `remote-push` job to only act on the specific filesystem `tank/zrepl/server/dump/zrepltest` it works, but I'd rather have the configuration as `tank/zrepl<` to make sure I don't miss any snapshots for other local datasets in the future.

Is what I want possible? Thanks!

```yaml
global:
  logging:
    - type: "stdout"
      level:  "warn"
      format: "human"

jobs:
  # This job creates snapshots and sends them to the
  # local sink on the tank zpool.
  - name: local-backup
    type: push
    connect:
      type: local
      listener_name: tank_sink
      client_identity: server
    filesystems: {
      "dump/zrepltest<": true
    }
    send:
      encrypted: true
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 10m
      timestamp_format: dense
      hooks:
        - type: command
          path: /etc/zrepl/hook.sh
          timeout: 5s
          err_is_fatal: false
    pruning:
      keep_sender:
        - type: not_replicated
        - type: last_n
          count: 10
        - type: regex
          negate: true
          regex: "^zrepl_.*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 30x1d | 12x30d
          regex: "^zrepl_.*"

  # This job configures the local sink on the tank zpool.
  - name: local-sink
    type: sink
    root_fs: "tank/zrepl"
    recv:
      placeholder:
        encryption: off
    serve:
      type: local
      listener_name: tank_sink

  # This job pushes snapshots from local sink to remote sink.
  - name: remote-push
    type: push
    connect:
      type: tls
      address: "backup.server.com:8888"
      ca: "/etc/zrepl/backup.server.com.crt"
      cert: "/etc/zrepl/server.crt"
      key: "/etc/zrepl/server.key"
      server_cn: "backup.server.com"
    filesystems: {
      "tank/zrepl<": true
    }
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    snapshotting:
      type: manual
    pruning:
      keep_sender:
        - type: regex
          regex: ".*"
      keep_receiver:
        - type: regex
          regex: ".*"
```
