### ISSUE TITLE
RFC: Filesystem Groups

### ISSUE THREAD

**Issue by InsanePrawn** [zrepl/zrepl#681]
## Idea

Features like #634 need a way to group filesystems. While we can introduce more and more place in the config to add filesystem[filter]s, I think there might be a better solution.

1. Introduce a global filesystem field that you can reference.
2. Introduce a special character to mark identifiers. I will be using `$` in my examples but am open to suggestion.
3. Decide whether we want to allow mixing group references and inline filesystem filters or force users to use group references always.

IMO these concepts should only affect the local config file layout, the config layer should probably resolve the groups back into concrete dataset filters where possible while the higher levels of code should keep working as they are.

### Simplest case

Based on https://github.com/zrepl/zrepl/blob/58c08c855fb14889c990317f96b41b9de8e87dbe/config/samples/push.yml

```yml
filesystems:
  default: {
      "zroot/<": true,
      "zroot/tmp": false
    }

jobs:
  - type: push
    name: "push"
    filesystems:
      - "$default": true
    connect:
      type: tcp
      address: "backup-server.foo.bar:8888"
    snapshotting:
      type: manual
    send:
      encrypted: false
    pruning:
[...]
```
This is how a normal config would look if we force user to use groups (we could then drop the `$` marker since it's enforce that group reference **must** be used. For validation, we could error out on group "names" that contain special characters like `/` and `<` to force users to migrate).
Alternatively, the user could split the two filters into two groups and use them like so, but why bother:
```yml
[...]
job:
  - type: push
    name: "push"
    filesystems:
      - "$zroot": true
      - "$tmp": false
```

### More useful example

Here's a bigger example, which is stripped from the ansible-generated config on my production LXD hosts.
- Hosts run a backup sink on `zroot/backups`
- Hosts also run a  push job for pushing their own datasets (excluding `zroot/backups`) to other hosts
- Care has to be taken not to snapshot lxd datasets

```yml
filesystem_groups:
  backups: {
    'zroot/backups': true,
    'zroot/backups<': true,
  }
  os: {
    'zroot/os': true,
    'zroot/os<': true,
    'zroot/ROOT': true, # some hosts use zroot/ROOT instead of zroot/os. yay inconsistency!
    'zroot/ROOT<': true,
  }
  data: {
    'zroot/data': true,
    'zroot/data<': true,
    'zroot/data/lxd_pools/default/deleted<': false,
    'zroot/data/lxd_pools/default/images<': false,
  }

jobs:
- name: 'backup_pruner'
  type: snap
  filesystems:
    - "$backups": true
  snapshotting:
    type: manual
  pruning:
    keep:
    - negate: true
      regex: ^(zrepl_|snapshot-).*$
      type: regex
    - grid: 1x6h(keep=all) | [...]
      regex: ^(zrepl_|snapshot-).*$
      type: grid

- name: 'default_sink'
  type: sink
  root_fs: 'zroot/backups'
  recv:
    properties:
      inherit:
      - compression
      override:
        mountpoint: none
  serve:
    [...]

- name: 'default_push_to_vmhost01'
  type: push
  filesystems:
    - "$os": true
    - "$data": true
    - "$backups": false
  snapshotting:
    type: manual
  [...]
  pruning:
    keep_receiver: &id001
    - regex: .*
      type: regex
    keep_sender: *id001
  connect:
    [...]
  replication:
    [...]

- name: 'default_snapjob'
  type: snap
  filesystems:
    - "$os": true
    - "$data": true
    - "$backups": false
  snapshotting:
    type: periodic
    interval: 15m
    prefix: 'zrepl_'
  pruning:
    keep:
    - negate: true
      regex: ^zrepl_.*$
      type: regex
    - grid: 1x4h(keep=all) | [...]
      regex: ^zrepl_.*$
      type: grid


[...]
```

You can probably imagine how unwieldly that generated config currently looks.

## Extended filesystem usage in Jobs

Additionally, i propose we add syntax to make members of the **job**'s filesystem list optionally dicts, enabling advanced configs like so:

```yml
- name: 'default_snapjob'
  type: snap
  filesystems:
    - "$data": true
    - "$backups": false
    - name: "$mysql" # if we allow mixing groups and literal fsf filter, this could be a dataset path/filter without the `$`
      include: true # equal to the bool passed in the existing short notation. naming is up for discussion.
      hooks:
        # TBD: should hooks also become things to be referenced? remove the job-global hooks config in? let them coexist?
        [...]
      atomic: true
```
