### ISSUE TITLE
Resumable sends with encrypted datasets 

### ISSUE THREAD

**Issue by phaer** [zrepl/zrepl#689]
Hi,
Is it possible to get resume-able uploads of a single, encrypted dataset without decrypting it?

I am trying to set up a new replication where I need to transfer a ~500GB dataset over a neither fast nor reliable link. The config below seems to work fine, as an upload is started and visible on the server. However, if stop and restart zrepl on the sender to check whether interrupted uploads can be resumed, zrepl starts to send the whole dataset from the beginning.

https://zrepl.github.io/configuration/sendrecvoptions.html#job-send-options and `man zfs-send` seem to suggest, that `saved: true` could help, but that seems incompatible with compressed and raw sends, according to https://github.com/openzfs/zfs/pull/9007/files#diff-cf9364a9cff2478f377b7c4f69664b4140102fa2642e79d12d9d35f8b525a3bdR4350#L4350

# sender
`uname -a`: `Linux my-client 5.15.99 #1-NixOS SMP Fri Mar 10 08:40:15 UTC 2023 x86_64 GNU/Linux`
`zfs version`: `zfs-2.1.9-1 zfs-kmod-2.1.9-1`

<details>
<summary>zrepl.yaml</summary>

```yaml
jobs:
- name: backups
  type: push
  connect:
    type: tcp
    address: "receiver:8888"
  send:
    encrypted: true
    compressed: true

  filesystems: {
    "rpool/safe<": true,
    "rpool/safe/persist/containers<": false,
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    - type: regex
      negate: true
      regex: "^zrepl_.*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
    - type: regex
      negate: true
      regex: "^zrepl_.*"

```

</details>

# receiver
`uname -a`: `Linux receiver 5.15.99 #1-NixOS SMP Fri Mar 10 08:40:15 UTC 2023 x86_64 GNU/Linux`
`zfs version`: `zfs-2.1.9-1 zfs-kmod-2.1.9-1`

<details>
<summary>zrepl.yaml</summary>

```yaml
jobs:
- name: sink
  type: sink
  serve:
      type: tcp
      listen: ":8888"
      listen_freebind: true
      clients: {
        "100.0.0.1": "my-client",
      }
  root_fs: "rpool/safe/zrepl/sink"
  recv:
    placeholder:
      encryption: off
    bandwidth_limit:
      max: 100 MiB 
```

</details>
