### ISSUE TITLE
The `regex` prune rule should allow multiple regexes

### ISSUE THREAD

**Issue by skirmess** [zrepl/zrepl#693]
You might want to keep two kind of snapshots with different expiration rules.

E.g.:

- `backup_` snapshots where you keep the `last_n`
- `zrepl_` snapshots which you expire with a `grid`

Instead of:

```
  pruning:
    keep:
      # Keep non-zrepl snapshots
      - type: regex
        negate: true
        regex: '\A(?:backup_|zrepl_[0-9][0-9][0-9][0-9]-[01][0-9]-[0123][0-9]-[012][0-9][0-6][0-9][0-6][0-9]Z\z)'
```

it would be easier and less error prone to write it like this

```
  pruning:
    keep:
      # Keep non-zrepl snapshots
      - type: regex
        negate: true
        regex:
          - '\Abackup_'
          - '\Azrepl_[0-9][0-9][0-9][0-9]-[01][0-9]-[0123][0-9]-[012][0-9][0-6][0-9][0-6][0-9]Z\z'
```

The rule would keep every snapshot that doesn't match both snapshots.
