### ISSUE TITLE
Need some clarification on configuration for backing a laptop up to a remote system

### ISSUE THREAD

**Issue by Halfwalker** [zrepl/zrepl#716]
Currently playing with the *tcp* transport
The laptop is named "_halflapp_" (how original).

The backup box in the office is named "_halfwalker_" with an encrypted dataset "*backup/laptop*" - this is the config

```
  - type: sink
    name: machine_backups
    root_fs: "backup/laptop"
    serve:
      type: tcp
      listen: ":8448"
      clients: {
        "10.0.130.60": "halflapp",
      }
    recv:
      properties:
        override: {
          "canmount": "noauto"
        }
      placeholder:
        encryption: inherit
```

**Q.1** - _does the client spec HAVE to be an IP address ?_  

As a laptop, it gets a different IP every day in the office ...  From the docs if I use a cidr range then the backup path will have the current IP in it, correct ?
With the laptop getting a different IP all the time, that would mean multiple backup paths I think ?

This is the zrepl config on the laptop.  There is a snap-only job that runs on a typical 15min cadence, then a script that will send a signal to zrepl to trigger the following push job

```
  - type: push
    name: home_to_backup
    connect:
      type: tcp
      address: halfwalker.datto.lan:8448
    filesystems: {
       "halflapp/home/alice<": true,
    }
    send:
      encrypted: true
      send_properties: true
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    snapshotting:
      type: manual
    pruning:
      # no-op prune rule on sender (keep all snapshots), snapshot job takes care of this
      keep_sender:
      - type: regex
        regex: ".*"
      keep_receiver:
      # longer retention on the backup drive, we have more space there
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d | 12x30d
        regex: "^zrepl_.*"
      # retain all non-zrepl/non-apt snapshots on the backup drive
      - type: regex
        negate: true
        regex: "^zrepl_.*"
```

The config is obviously not quite right - notice how the path has "_halflapp_" in there twice ...

```
backup/laptop                                                         6.49G  192K   228G   none
backup/laptop/halflapp                                                6.49G  192K   228G   none
backup/laptop/halflapp/halflapp                                       6.49G  192K   228G   none
backup/laptop/halflapp/halflapp/home                                  6.49G  192K   228G   none
backup/laptop/halflapp/halflapp/home/alice                            6.49G  6.49G  228G   /home/alice
backup/laptop/halflapp/halflapp/home/alice@zrepl_2023-06-08_14:00:05  0B     6.49G  -      -
```

**Q.2** What is the proper way to specify the filesystem patterns to have the replication drop into *backup/laptop/_<machine>_* ?

I think it sounds like I should be using the *tls* transport which will identify the laptop by the cert CN name ...

**Comment by Halfwalker** [comment]
Switched to the **tls** transport - that's working nicely now without needing hard-coded IPs.  I still think being able to use dhcp names or some other identifier would help the **tcp** transport out ...

Still have the wrong/long path though - I'm certain it's a simple misconfig and misunderstanding of how to specify the datasets to send and to receive into.

**Comment by Halfwalker** [comment]
Figured out the apparent duplication of `halflapp` above ...  One is the client identity, the other is the poolname
```
backup/laptop/halflapp/halflapp/home/deano
|-----------| |------||------------------|
       ^         ^           ^
       |         |           +----- dataset being backed up
       |         +----------------- client identity
       +--------------------------- target dataset
```

**Comment by Halfwalker** [comment]
Hrm - now a question on the actual retention and pruning for a grid spec.  The laptop has 2 jobs, a snap/prune only one `snaphome` and a push job `home_to_bondi`.  That push job is triggered by a cronjob every hour.

`snaphome` pruning spec - very bog-standard.  I would assume that any time you looked at the snapshots, you would see the newest 4x being 15mins apart, then up to 24x each within a 1-hour block _over the last 24 hours from **this** point in time_, and up to 30x each within a 24-hour block _over the last 30 days from **this** point in time._
```
    pruning:
      keep:
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d
        regex: "^zrepl_.*"
      - type: regex
        negate: true
        regex: "^zrepl_.*"
```

The push job `home_to_bondi` has a very similar spec, just adding a set of 12x 30-day buckets
```
    pruning:
      # no-op prune rule on sender (keep all snapshots), snapshot job takes care of this
      keep_sender:
      - type: regex
        regex: ".*"
      keep_receiver:
      # longer retention on the backup drive, we have more space there
      - type: grid
        grid: 1x1h(keep=all) | 24x1h | 30x1d | 12x30d
        regex: "^zrepl_.*"
      # retain all non-zrepl snapshots on the backup system
      - type: regex
        negate: true
        regex: "^zrepl_.*"
```

While the laptop is on and connected to the network with the `bondi` backup system, things seem to move along as expected.  But if the laptop is off overnight for example, it seems to prune more than expected from the backup system.

For example, here are the snaps from last night
```
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-08_00:56:02
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-09_14:16:10
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_14:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_15:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_16:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_17:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_18:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:28:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:43:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:58:45 
```
and then this morning after the push job ran
```
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-08_00:56:02
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-09_14:16:10
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_14:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_18:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_16:43:46
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_18:45:03 
```
Basically, it looks like this is what it did
```
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-08_00:56:02
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-09_14:16:10
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_14:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_15:13:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_16:13:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_17:13:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_18:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:28:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:43:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_16:43:46  <<< added
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_18:45:03  <<< added 
```
And then after a few hours it looks like this
```
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-08_00:56:02
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-09_14:16:10
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_14:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_15:13:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_16:13:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_17:13:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_18:13:45  <<< Newly removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:13:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:28:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:43:45  <<< removed
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-10_19:58:45
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_16:43:46  <<< added
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_18:45:03  <<< added 
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_19:15:03  <<< Newly added
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_19:30:03  <<< Newly added
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_19:45:03  <<< Newly added
bondi3/zrepl/halflapp/halflapp/home/alice@zrepl_2023-06-11_20:00:03  <<< Newly added
```
What's weird is it doesn't match with the actual snaps on the laptop
```
halflapp/home/alice@zrepl_2023-06-07_20:43:34  <<< Not on backup
halflapp/home/alice@zrepl_2023-06-09_15:58:52  <<< Not on backup
halflapp/home/alice@zrepl_2023-06-10_15:58:45  <<< Not on backup
halflapp/home/alice@zrepl_2023-06-11_16:43:46
halflapp/home/alice@zrepl_2023-06-11_18:45:03
halflapp/home/alice@zrepl_2023-06-11_19:45:03  <<< Not on backup
halflapp/home/alice@zrepl_2023-06-11_20:30:03
halflapp/home/alice@zrepl_2023-06-11_20:45:03
halflapp/home/alice@zrepl_2023-06-11_21:00:03
halflapp/home/alice@zrepl_2023-06-11_21:15:03
```
