### ISSUE TITLE
i/o timeout errors while transferring snapshots via TCP + TLS

### ISSUE THREAD

**Issue by SoerenBusse** [zrepl/zrepl#719]
We're using zrepl to replicate ZFS snapshots from our main server to our backup server. To do this, we've configured the TCP + TLS transport using the configuration below. Occasionally, without it being reproducible, the replication will fail with the following error.

```
Jun 19 02:41:47 -backup zrepl[897]: [pull_main][repl][Uv38$mJje$mJje.SkxN.ma7g.teSu]: most recent error in this attempt attempt_number="0" err="could not send protocol banner: read tcp 10.16.100.2:38240->10.12.100.1:17666: i/o timeout"
Jun 19 02:41:47 backup zrepl[897]: [pull_main][repl][Uv38$mJje$mJje.SkxN.ma7g.teSu]: most recent error cannot be solved by reconnecting, aborting run attempt_number="0"
```

If you analyse the packet capture while this error is occurring, it looks as if zrepl is not responding to the "Server Hello" message from the server. Because of this, the Server retransmits the packets several times. Then the zrepl client closes the connection with a FIN/ACK.

![image](https://github.com/zrepl/zrepl/assets/7796567/694216be-a93f-4906-a191-1ee15e38e72a)

What is a bit strange is, that I see a TCP transmission on each TCP stream, when the zrepl server sends a TCP FIN (33225 was the original packet, and the retransmission was 33227). 

![image](https://github.com/zrepl/zrepl/assets/7796567/ed703ead-31b1-4818-bf6f-43f500a9a498)

As I see the original TCP message as well as the TCP retransmissions, I'd rule out the network as the source of the issue.

The error occurred more frequently, when we used a 10G SFP+ module compared to a 1G SFP module in our backup server.

**Main server:**
```
client: zrepl version=v0.6.0 go=go1.19.2 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.6.0 go=go1.19.2 GOOS=linux GOARCH=amd64 Compiler=gc
Linux master-1 5.10.0-0.deb10.16-amd64
6fbecd97d02a358aad77fc73c878d0da43eb8730  /usr/bin/zrepl
```
```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
  - name: backup_source
    type: source
    serve:
      type: tls
      listen: "10.12.100.1:17666"
      listen_freebind: true
      ca: /etc/zrepl/ca.crt
      cert: /etc/zrepl/main.crt
      key: /etc/zrepl/main.crt
      client_cns:
        - "backup.domain.tld"
    filesystems: {
      "<": true,
      "Storage/var<": false,
      "Storage/tmp<": false,
      "Storage/log<": false
    }
    send:
      encrypted: false
    snapshotting:
      type: periodic
      prefix: zrepl_
      interval: 15m
```

**Backup Server:**
```
client: zrepl version=v0.6.0 go=go1.19.2 GOOS=linux GOARCH=amd64 Compiler=gc
server: zrepl version=v0.6.0 go=go1.19.2 GOOS=linux GOARCH=amd64 Compiler=gc
Linux backup 5.15.60-2-pve
6fbecd97d02a358aad77fc73c878d0da43eb8730  /usr/bin/zrepl
```
```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn
  monitoring:
    - type: prometheus
      listen: ":9811"
      listen_freebind: true

jobs:
  - name: pull_main
    type: pull
    connect:
      type: tls
      address: "10.12.100.1:17666"
      ca: /etc/zrepl/pki/ca.crt
      cert: /etc/zrepl/pki/issued/backup.crt
      key: /etc/zrepl/pki/private/backup.key
      server_cn: "main.domain.tld"
    root_fs: "backup/servers/main"
    interval: 24h
    pruning:
      keep_sender:
        - type: not_replicated
        - type: regex
          regex: "^(manual_|autosnap_|zfs-auto-snap_daily-|zfs-auto-snap_monthly-).*"
        - type: grid
          regex: "^zrepl_.*"
          grid: 2x1d(keep=all) | 14x1d | 4x7d | 2x30d
      keep_receiver:
        - type: regex
          regex: "^(manual_|autosnap_|zfs-auto-snap_daily-|zfs-auto-snap_monthly-).*"
        - type: grid
          regex: "^zrepl_.*"
          grid: 2x1d(keep=all) | 30x1d | 12x7d | 12x30d | 3x365d
    recv:
      placeholder:
        encryption: inherit
```
