### ISSUE TITLE
pull / fan-out-filesystems takes forever

### ISSUE THREAD

**Issue by silenius** [zrepl/zrepl#723]
Hello,

I'm currently using zrepl 0.6 to backup 3 servers (`troubadour.lan`, `chouffe.prod.lan`, `chimay.prod.lan`) to 2 hosts (`zsync.lan` (local backup), `zsync2.lan` (offsite backup)) and, although initial replication works fine and fast, after ~3 months of usage `zrepl` is getting slower and slower to the point that it takes forever now. 

Here is a screenshot:
![shot-2023-07-09_13-39-43](https://github.com/zrepl/zrepl/assets/1225348/34d85c24-852a-4c5d-af4a-50fa62734264)
 (as you can see it tooks more than 4 hours to transfer 800 MB).

Do you have any idea of what could be the cause of this?

One important thing: the problem happens *only* for `troubadour.lan` (running 12.4-RELEASE and has many datasets)

Here is my config:

zsync.lan (local backup machine):
```
global:
  control:
    sockpath: /var/run/zrepl/control
  logging:
  - format: human
    level: error
    type: stdout
  - format: logfmt
    level: info
    type: syslog
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
jobs:
- connect:
    address: troubadour.lan:21888
    type: tcp
  interval: 1h
  name: sync_troubadour_local
  pruning:
    keep_receiver:
    - negate: true
      regex: ^zrepl_.*
      type: regex
    - grid: 1x24h(keep=all) | 24x1h | 7x1d
      regex: ^zrepl_.*
      type: grid
    keep_sender:
    - regex: .*
      type: regex
  root_fs: zroot_jupiler/data/jails/zsync/troubadour
  type: pull
- connect:
    address: chimay.prod.lan:21888
    type: tcp
  interval: 1h
  name: sync_chimay_local
  pruning:
    keep_receiver:
    - negate: true
      regex: ^zrepl_.*
      type: regex
    - grid: 1x24h(keep=all) | 24x1h | 7x1d
      regex: ^zrepl_.*
      type: grid
    keep_sender:
    - regex: .*
      type: regex
  root_fs: zroot_jupiler/data/jails/zsync/chimay
  type: pull
- connect:
    address: chouffe.prod.lan:21888
    type: tcp
  interval: 1h
  name: sync_chouffe_local
  pruning:
    keep_receiver:
    - negate: true
      regex: ^zrepl_.*
      type: regex
    - grid: 1x24h(keep=all) | 24x1h | 7x1d
      regex: ^zrepl_.*
      type: grid
    keep_sender:
    - regex: .*
      type: regex
  root_fs: zroot_jupiler/data/jails/zsync/chouffe
  type: pull
```

zsync2.lan (offsite):
```
global:
  control:
    sockpath: /var/run/zrepl/control
  logging:
  - format: human
    level: error
    type: stdout
  - format: logfmt
    level: info
    type: syslog
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
jobs:
- connect:
    address: troubadour.lan:21889
    type: tcp
  interval: 1h
  name: sync_troubadour_remote
  pruning:
    keep_receiver:
    - negate: true
      regex: ^zrepl_.*
      type: regex
    - grid: 1x24h(keep=all) | 24x1h | 30x1d
      regex: ^zrepl_.*
      type: grid
    keep_sender:
    - regex: .*
      type: regex
  root_fs: zroot_stout/data/jails/zsync/troubadour
  type: pull
- connect:
    address: chimay.prod.lan:21889
    type: tcp
  interval: 1h
  name: sync_chimay_remote
  pruning:
    keep_receiver:
    - negate: true
      regex: ^zrepl_.*
      type: regex
    - grid: 1x24h(keep=all) | 24x1h | 30x1d
      regex: ^zrepl_.*
      type: grid
    keep_sender:
    - regex: .*
      type: regex
  root_fs: zroot_stout/data/jails/zsync/chimay
  type: pull
- connect:
    address: chouffe.prod.lan:21889
    type: tcp
  interval: 1h
  name: sync_chouffe_remote
  pruning:
    keep_receiver:
    - negate: true
      regex: ^zrepl_.*
      type: regex
    - grid: 1x24h(keep=all) | 24x1h | 30x1d
      regex: ^zrepl_.*
      type: grid
    keep_sender:
    - regex: .*
      type: regex
  root_fs: zroot_stout/data/jails/zsync/chouffe
  type: pull
```

troubadour.lan:
```
global:
  control:
    sockpath: /var/run/zrepl/control
  logging:
  - format: human
    level: error
    type: stdout
  - format: logfmt
    level: info
    type: syslog
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
jobs:
- filesystems:
    zroot/data/jails/pg11-prod-slave<: false
    zroot<: true
  name: snap_zroot
  pruning:
    keep:
    - negate: true
      regex: ^zrepl_
      type: regex
    - grid: 1x24h(keep=all)
      regex: ^zrepl_
      type: grid
  snapshotting:
    interval: 15m
    prefix: zrepl_
    type: periodic
  type: snap
- filesystems:
    zroot/data/jails/pg11-prod-slave<: false
    zroot<: true
  name: sync_troubadour_local
  serve:
    clients:
      10.209.1.56: zsync.lan
    listen: troubadour.lan:21888
    type: tcp
  snapshotting:
    type: manual
  type: source
- filesystems:
    zroot/data/jails/pg11-prod-slave<: false
    zroot<: true
  name: sync_troubadour_remote
  serve:
    clients:
      10.198.76.4: zsync2.lan
    listen: troubadour.lan:21889
    type: tcp
  snapshotting:
    type: manual
  type: source
```

chouffe.prod.lan:
```
global:
  control:
    sockpath: /var/run/zrepl/control
  logging:
  - format: human
    level: error
    type: stdout
  - format: logfmt
    level: info
    type: syslog
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
jobs:
- filesystems:
    zroot/data/jails/pg11/backups<: false
    zroot/data/jails/pg13/backups<: false
    zroot/data/jails/pg96/backups<: false
    zroot<: true
  name: snap_zroot_chouffe
  pruning:
    keep:
    - negate: true
      regex: ^zrepl_
      type: regex
    - grid: 1x24h(keep=all)
      regex: ^zrepl_
      type: grid
  snapshotting:
    interval: 15m
    prefix: zrepl_
    type: periodic
  type: snap
- filesystems:
    zroot/data/jails/pg11/backups<: false
    zroot/data/jails/pg13/backups<: false
    zroot/data/jails/pg96/backups<: false
    zroot<: true
  name: sync_chouffe_remote
  serve:
    clients:
      10.198.76.4: zsync2.lan
    listen: chouffe.prod.lan:21889
    type: tcp
  snapshotting:
    type: manual
  type: source
- filesystems:
    zroot/data/jails/pg11/backups<: false
    zroot/data/jails/pg13/backups<: false
    zroot/data/jails/pg96/backups<: false
    zroot<: true
  name: sync_chouffe_local
  serve:
    clients:
      10.209.1.56: zsync.lan
    listen: chouffe.prod.lan:21888
    type: tcp
  snapshotting:
    type: manual
  type: source
```

chimay.prod.lan:
```
global:
  control:
    sockpath: /var/run/zrepl/control
  logging:
  - format: human
    level: error
    type: stdout
  - format: logfmt
    level: info
    type: syslog
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
jobs:
- filesystems:
    zroot_chimay<: true
  name: snap_zroot_chimay
  pruning:
    keep:
    - negate: true
      regex: ^zrepl_
      type: regex
    - grid: 1x24h(keep=all)
      regex: ^zrepl_
      type: grid
  snapshotting:
    interval: 15m
    prefix: zrepl_
    type: periodic
  type: snap
- filesystems:
    zroot_chimay<: true
  name: sync_chimay_remote
  serve:
    clients:
      10.198.76.4: zsync2.lan
    listen: chimay.prod.lan:21889
    type: tcp
  snapshotting:
    type: manual
  type: source
- filesystems:
    zroot_chimay<: true
  name: sync_chimay_local
  serve:
    clients:
      10.209.1.56: zsync.lan
    listen: chimay.prod.lan:21888
    type: tcp
  snapshotting:
    type: manual
  type: source
```

Thank you!
