### ISSUE TITLE
zrepl daemon ignores alternate "--config" location.

### ISSUE THREAD

**Issue by reefland** [zrepl/zrepl#727]
The value of `${CONFIG}` is  `/config/zrepl.yml`  testing on a env not using systemd.

Test the yaml contents, no issue:
```
# /usr/bin/zrepl --config "${CONFIG}" configcheck
```

When I try to have the daemon use that config file:
```
# /usr/bin/zrepl --config "${CONFIG}" daemon &

could not parse config: yaml: unmarshal errors:
  line 0: field jobs is required but has zero value
```

* The `zrepl daemon --help` indicates that should work.
* When I reference an environment using systemd it uses that parameter `ExecStart=/usr/bin/zrepl --config /etc/zrepl/zrepl.yml daemon`

So on a hunch, I copy my file to the default location:
```
# cp "${CONFIG}" /etc/zrepl/zrepl.yml
```

And still tell `zrepl` to NOT use the default location, but now it fires up no problem.
```
# /usr/bin/zrepl --config "${CONFIG}" daemon &
```

Seems to ignore the value of the `--config` and only uses the default location.  However, if I specify a filename that does not exist, it correctly showed an error.  So validates the parameter but then ignores it?

The contents of `/config/zrepl.yml`:
```
global:
  control:
    sockpath: /var/run/zrepl/control
  serve:
    stdinserver:
      sockdir: /var/run/zrepl/stdinserver
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
  - type: sink
    name: zrepl_sink_server
    root_fs: "zrepl/sink"
    serve:
      type: tls
      listen: ":8448"
      listen_freebind: true
      ca: /config/ca.crt
      cert: /config/sink-srv.crt
      key: /config/sink-srv.key
      client_cns:
        - "dldsk01"
    recv:
      properties:
        override: {
          "canmount": "noauto"
        }
      placeholder:
        encryption: inherit
```
