### ISSUE TITLE
Encrypted send to untrusted target not quite working ... pretty sure it's a simple config issue

### ISSUE THREAD

**Issue by Halfwalker** [zrepl/zrepl#742]
Encrypted send to untrusted target not quite working ...

I have a backup dataset `bondi3/zrepl` on a server **bondi** that receives laptop backups.  The dataset is encrypted, and laptop sends are plain, so they're re-encrypted on **bondi**.  For offsite backups, I want to replicate this to a backup dataset `wider/zrepl` on remote server **widey**.  Should be fairly simple ...

The two laptop sub-datasets under `bondi3/zrepl` - both look like this
```
bondi3/zrepl/ryzen2/ryzen22/home/alice  encryption             aes-256-gcm            -
bondi3/zrepl/ryzen2/ryzen22/home/alice  keylocation            none                   default
bondi3/zrepl/ryzen2/ryzen22/home/alice  keyformat              passphrase             -
bondi3/zrepl/ryzen2/ryzen22/home/alice  pbkdf2iters            350000                 -
bondi3/zrepl/ryzen2/ryzen22/home/alice  encryptionroot         bondi3/zrepl 
bondi3/zrepl/ryzen2/ryzen22/home/alice  keystatus              available
```

**bondi** zrepl.yml *source* job
```
  - type: source
    name: laptop_source
    filesystems:
      "bondi3/zrepl<": true
    snapshotting:
      type: manual
    send:
      encrypted: true
    serve:
      type: tls
      listen: :8541
      ca: /etc/zrepl/ca.crt
      cert: /etc/zrepl/bondi.crt
      key: /etc/zrepl/bondi.key
      client_cns:
        - widey
```

**widey** zrepl.yml *pull* job
```
  - name: pull_bondi
    type: pull
    connect:
      type: tls
      address: 192.168.2.104:8541
      ca: /etc/zrepl/ca.crt
      cert: /etc/zrepl/widey.crt
      key: /etc/zrepl/widey.key
      server_cn: bondi
    root_fs: wider/zrepl
    interval: 1h
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_resumability
    recv:
      properties:
        override: {
          "readonly": "on",
          "mountpoint": "none",
          "canmount": "noauto"
        }
      # encryption off as per encrypted-send-to-untrusted-receiver
      # https://zrepl.github.io/master/configuration/sendrecvoptions.html#placeholders
      placeholder:
        encryption: off
    pruning:
      keep_sender:
        - type: regex
          regex: '.*'
      keep_receiver:
        - type: regex
          negate: true
          regex: '^zrepl_'
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 30x1d | 12x30d
          regex: '^zrepl_'
```

Except the two laptop backups (*halflapp* and *ryzen2*) fail ... this is the status on the remote **widey**
```
bondi3/zrepl                              PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
bondi3/zrepl/halflapp                     PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
bondi3/zrepl/halflapp/halflapp            PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
bondi3/zrepl/halflapp/halflapp/home       PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
bondi3/zrepl/halflapp/halflapp/home/alice STEP-ERROR (step 1/1, 0 B/6.8 GiB) parent(s) failed during initial replication: [bondi3/zrepl bondi3/zrepl/halflapp/halflapp]
     :
bondi3/zrepl/ryzen2                       PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
bondi3/zrepl/ryzen2/ryzen22               PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions
bondi3/zrepl/ryzen2/ryzen22/home          PLANNING-ERROR (step 0/0, 0 B/0 B) sender does not have any versions 
bondi3/zrepl/ryzen2/ryzen22/home/alice    STEP-ERROR (step 1/1, 0 B/44.1 GiB) parent(s) failed during initial replication: [bondi3/zrepl bondi3/zrepl/ryzen2/ryzen22]
```
