### ISSUE TITLE
Feature request: Allow disable pruning for push and pull jobs

### ISSUE THREAD

**Issue by Halfwalker** [zrepl/zrepl#745]
In several setups one can use the following to essentially disable pruning
```
    pruning:
      # no-op prune rule on sender (keep all snapshots), snapshot job takes care of this
      keep_sender:
      - type: regex
        regex: ".*"
```
and that works fine.  But in some cases the `plan` phase can take a long time, especially if the sender side is a large system where a typical `zfs list` can take time.

Maybe have a disable feature so it doesn't even attempt it
```
    pruning:
      # pruning is handled elsewhere
      keep_sender:
      - type: disable
```
