### ISSUE TITLE
receiving jobs with overlapping root filesystems are forbidden

### ISSUE THREAD

**Issue by dsh2dsh** [zrepl/zrepl#751]
Hi,

I see next error trying to start zrepl:
```
cannot build jobs from config: receiving jobs with overlapping root filesystems are forbidden
```

In my config I have two sinks with the same `root_fs`:
```
  - name: "zdisk"
    type: "sink"
    root_fs: "zdisk/zrepl"
    serve:
      type: "local"
      listener_name: "zdisk"

  - name: "tls-zdisk"
    type: "sink"
    root_fs: "zdisk/zrepl"
    serve:
      type: "tls"
```

The first one is for local snapshots and the second is for remote snapshots. Could somebody explain, what is the reason to forbid same `root_fs` in different sinks? During replication they use different dataset names anyway, because different client names.

Thanks.
