### ISSUE TITLE
STEP-ERROR (step 1/1, 44.2 KiB/42.6 KiB) server error: cannot get placeholder state of : zfs exited with error: exit status 1

### ISSUE THREAD

**Issue by battlezone** [zrepl/zrepl#777]
I am having issues trying to setup zrepl. When sending a wakeup signal to my job I get the following error in zrepl status:

> STEP-ERROR (step 1/1, 44.2 KiB/42.6 KiB) server error: cannot get placeholder state of : zfs exited with error: exit status 1

Journalctl shows the following:

> [pc_to_backups][repl][GnEa$alsc$3lss$3lss.jlaz.JCKr]: receive request failed (might also be error on sender) filesystem="tank" rr="Filesystem:\"tank\" To:{Name:\"zrepl_20240308_095657_000\" Guid:109652840907449951 CreateTXG:1502835 Creation:\"2024-03-08T10:56:57+01:00\"} ClearResumeToken:true ReplicationConfig:{protection:{Initial:GuaranteeResumability Incremental:GuaranteeResumability}}" err="server error: cannot get placeholder state of : zfs exited with error: exit status 1\nstderr:\ncannot open '': empty component or misplaced '@' or '#' delimiter in name\n" errType="*dataconn.RemoteHandlerError"

My push job config is:
```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: pc_to_backups
  type: push
  connect:
    type: tcp
    address: "192.168.1.5:8888"
  filesystems: {
    "tank<": true,
    "tank/var/tmp<": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 60m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
```

And my sink config is:
```
global:
  logging:
    - type: syslog
      format: human
      level: warn

jobs:
- name: sink
  type: sink
  serve:
      type: tcp
      listen: ":8888"
      clients: {
        "192.168.1.1" : "Arch-pc"
        }
  root_fs: "/media/backups/pc"
```

My ZFS version is: 
```
zfs-2.2.3-1
zfs-kmod-2.2.3-1
```

**Comment by problame** [comment]
Hey, apologies for the delayed reply.

Did you ever manage to root cause or fix the issue?

**Comment by VegaDeftwing** [comment]
I seem to be having a similar issue. I'm on Proxmox, 
zfs-2.2.4-pve1
zfs-kmod-2.2.4-pve1

<img width="1536" alt="image" src="https://github.com/user-attachments/assets/ec48a76b-8ecc-4aab-afad-805f9a47054d">

The configs are the same as https://zrepl.github.io/quickstart/continuous_server_backup.html except changing the locations/names to "triode" (my main server) and "homebak" (My backup)

```yaml
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
#  - name: foo
#    type: bar

# see /usr/share/doc/zrepl/examples
# or https://zrepl.github.io/configuration/overview.html
- name: triode_to_homebak
  type: push
  connect:
    type: tls
    address: "100.99.252.122:8888"
    ca: /etc/zrepl/homebak.crt
    cert: /etc/zrepl/triode.crt
    key:  /etc/zrepl/triode.key
    server_cn: "homebak"
  filesystems: {
    "Primary<": true,
    "rpool<": true
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 10m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: last_n
      count: 10
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: "^zrepl_"
```

And,

```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: sink
  type: sink
  serve:
      type: tls
      listen: ":8888"
      ca: "/etc/zrepl/triode.crt"
      cert: "/etc/zrepl/homebak.crt"
      key: "/etc/zrepl/homebak.key"
      client_cns:
        - "triode"
  root_fs: "/Secondary/zrepl/sink"
```

`/Secondary/zrepl/sink` is path to a folder on the backup server where I want things to go, I found the docs for how `root_fs` a tad confusing, so I'm less than certain that's correct, but otherwise I'm not sure what's going on.
