### ISSUE TITLE
Feature request: TLS with client auth for Prometheus monitoring endpoint

### ISSUE THREAD

**Issue by Coder686375** [zrepl/zrepl#780]
The Prometheus monitoring endpoint does not currently support secure connections:

https://github.com/zrepl/zrepl/blob/ebc46cf1c04a00ee779013d3e72dab07fce454e3/config/config.go#L454-L458

Support for this could be added by accepting TLS connection settings such as those available in `TLSServe`:

https://github.com/zrepl/zrepl/blob/ebc46cf1c04a00ee779013d3e72dab07fce454e3/config/config.go#L372-L381

Here's an example configuration:

```yml
global:
  monitoring:
  - type: prometheus+tlsclientauth
    listen: "MyServer:9811"
    listen_freebind: true
    ca: "/etc/ssl/certs/MyCA Public Key.pem"
    cert: "/etc/ssl/certs/MyServer Public Key.pem"
    key: "/etc/ssl/private/MyServer Private Key.pem"
    client_cns:
    - "MyClient1"
    - "MyClient2"
```
