### ISSUE TITLE
Sendoptions - encrypted:true does not send with raw "-w"

### ISSUE THREAD

**Issue by aheahe** [zrepl/zrepl#805]
With this configuration

```dockerfile
jobs:
- name: myjobname
  type: source
  send:
    encrypted: true
``` 

According to the documentation (https://zrepl.github.io/configuration/sendrecvoptions.html#send-options), with "encrypted=true", zrepl should

"invoke the zfs send subcommand with the -w option (raw sends)."

However, zrepl does not do that. The send command is issued without the -w option, resulting in a "plain send." I verified this by checking the running processes with "ps."

To make it work as intended, I had to add "raw: true."

Using Zrepl version 0.6.1-2 on Debian 12

**Comment by problame** [comment]
Sorry for the delayed reply to such a sensitive issue.

---

I cannot reproduce your problem for initial replication.

Here's the configuration I used to try to reproduce (click to expand)

<details>

```yaml
cs@zrepl-1:[/etc/zrepl]: cat zrepl.yml
global:
  logging:

    - type: "stdout"
      level:  "debug"
      format: "human"

  monitoring:
    - type: prometheus
      listen: ":9091"

jobs:
- type: pull
  name: mypull
  connect:
    type: local
    listener_name: mysrc_listener
    client_identity: mypull
  root_fs: "p2/mypull"
  interval: manual
  replication:
    protection:
      initial: guarantee_resumability
      incremental: guarantee_resumability
  recv:
    placeholder:
      encryption: off
  pruning:
    keep_sender:
    - type: regex
      regex: ".*"
    keep_receiver:
    - type: regex
      regex: ".*"

- type: source
  name: mysrc
  filesystems:
    "p1/unencrypted": true
    "p1/encrypted": true
  snapshotting:
    type: manual
  send:
    encrypted: true
  serve:
    type: local
    listener_name: mysrc_listener

```

</details>
