### ISSUE TITLE
pull job is lasting forever - Request: job timeout

### ISSUE THREAD

**Issue by ole-db** [zrepl/zrepl#824]
client: zrepl version=v0.6.1 go=go1.21.12 GOOS=freebsd GOARCH=amd64 Compiler=gc
server: zrepl version=v0.6.1 go=go1.21.12 GOOS=freebsd GOARCH=amd64 Compiler=gc

Sometimes I find Jobs that are lasting forever:

```
Type: pull
Replication:
   Attempt #1
   Status: fan-out-filesystems
   Started: 2024-09-17 14:04:32 +0200 CEST (lasting 188h55m8s)
   Progress: [>--------------------------------------------------] 0 B / 41.3 MiB @ 0 B/s
```

So I have to reset them manually. I don't know what triggers this. 
But to deal with problems like this I suggest to add a timeout to jobs.
