### ISSUE TITLE
Stuck with 2-year-old step-holds blocking pruning while replication otherwise working

### ISSUE THREAD

**Issue by gdevenyi** [zrepl/zrepl#826]
version zrepl-0.6.1-2 on Ubuntu 20.04.5

Config
```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: syslog
      format: human
      level: warn

jobs:
- name: cicss05_to_cicss06
  type: push
  replication:
    concurrency:
      steps: 4
      size_estimates: 8
  connect:
    type: tls
    address: "cicss06:8888"
    ca: /etc/zrepl/cicss06.crt
    cert: /etc/zrepl/cicss05.crt
    key:  /etc/zrepl/cicss05.key
    server_cn: "cicss06"
  filesystems: {
    "<": true,
    "data": false,
    "data/scratch2": false
  }
  snapshotting:
    type: periodic
    prefix: zrepl_
    interval: 15m
  pruning:
    keep_sender:
    - type: not_replicated
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 30x1d | 6x30d
      regex: ".*"
    keep_receiver:
    - type: grid
      grid: 1x1h(keep=all) | 30x1d | 3x30d
      regex: ".*"
```

I have a set of dangling step-holds on a bunch of filesystems, one example:
`step-hold "zrepl_STEP_J_prod_to_backup" on data/frqs@zrepl_20221104_191520_000`

which are much much older than the other snapshots around (which are being replicated and pruned properly)

Every round of snapshot/replication zrepl throws errors:
` data/frqs              ERROR: destroys failed @zrepl_20221104_191520_000: dataset is busy`

I'm realizing here, that these step-holds (and cursors?) have a different job name "prod_to_backup" than the job names, would this arise from renaming the jobs?

Are these safe to destroy using the zrepl abstraction tools?
