### ISSUE TITLE
monitoring endpoint doesn't work anymore

### ISSUE THREAD

**Issue by colttt** [zrepl/zrepl#827]
Hi,

since v0.6.1 the monitoring endpoint doesn't work anymore, my config-file looks like:
```
global:
  logging:
    # use syslog instead of stdout because it makes journald happy
    - type: stdout
      format: human
      level: info
  monitoring:
    - type: prometheus
      listen: ':9811'

[...]
```
in the browser and with curl I got a 404:
```
curl http://192.168.50.12:9811/
404 page not found
```
