### ISSUE TITLE
transport tcp: allow client to specify its `client_identity` to enable dynamic IPs

### ISSUE THREAD

**Issue by problame** [zrepl/zrepl#832]
# Problem

Currently, the `serve` (sink,source) side determines the `client_identity` exclusively based on the client IP address.

This doesn't work well in
- environment with dynamic client IPs (DHCP, VPNs)
- NAT

# Solution

Allow the client to announce its identity and if the server has opted in, accept that.

```yaml
connect:
  type: tcp
  client_identity: laptop
  address: backupserver.yak-bebop.ts.net:1234 # 100.64.23.42:1234
```

```yaml
serve:
  listen: ...
  clients:
    # old way, needs to be supported
    "192.168.122.123": "mysql01"
    "10.23.42.0/24": "cluster-*"
    # this feature
    "client:laptop": "laptop"
    # future
    "rdns:somebox.example.net": "sombebox"      
```

Syntax is up for debate.

(cf https://zrepl.github.io/configuration/transports.html#tcp-transport )

# Implementation Constraints

It's ok to break the network protocol, just bump the protocol version:

https://github.com/zrepl/zrepl/blob/908807bd59d8fa76bf4db51b4ca64466fba65ae1/internal/rpc/versionhandshake/versionhandshake.go#L192-L195

I don't think there's a way to avoid breaking the protocol.

# Refs

refs https://github.com/zrepl/zrepl/issues/817
