### ISSUE TITLE
multiple sink jobs with overlapping root fs

### ISSUE THREAD

**Issue by Darukutsu** [zrepl/zrepl#868]
I don't understand why I can't do this, there was https://github.com/zrepl/zrepl/pull/752 for different jobs but why not also this.

I think this is totally understandable config... and even if I remove arch-daru from zfs_tcp_sink it still shows same error `cannot build jobs from config: receiving jobs with overlapping root filesystems are forbidden`

Both sinks create named dataset and it's up to user to not be stupid to run both conflicting jobs at same time.
I'm currently doing it by commenting tcp_sink or ssh_sink, when needed and restarting server service.

Server conf:
```
global:
  logging:
    - type: "stdout"
      level:  "error"
      format: "human"
    - type: "syslog"
      level:  "info"
      format: "logfmt"

jobs:
  - name: zfs_tcp_sink
    type: sink
    root_fs: "f001/backup"
    serve:
      type: tcp
      listen: ":8888"
      listen_freebind: true # optional, default false
      clients: {
        "192.168.0.1" :                 "opnsense",
        "192.168.130.130" :               "arch-daru",
      }
    recv:
      placeholder:
        encryption: off

  - name: zfs_ssh_sink
    type: sink
    root_fs: "f001/backup"
    serve:
      type: stdinserver
      client_identities:
        - "arch-daru"
    recv:
      placeholder:
        encryption: off
```

On arch-daru I have separate zfs_tcp_push and zfs_ssh_push jobs which are both set to manual.
